#!/usr/bin/env node
/** extras/*.js × 15言語に 8 新loc 追加 */
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const EXTRAS_DIR = resolve(__dirname, "app", "content", "extras");

const T = {
  es: {
    "弘法山古墳": `Túmulo del Monte Kobo, en Matsumoto, es uno de los túmulos en forma de ojo de cerradura más antiguos del este de Japón (finales del siglo III). A 650 m de altitud, unos 4.000 cerezos florecen a mediados de abril. La cima ofrece un panorama de Matsumoto y los Alpes del Norte nevados enmarcados por los cerezos.`,
    "安養寺": `Anyo-ji es un antiguo templo Jodo Shinshu en Matsumoto. Su cerezo llorón centenario despliega cascadas rosa pálido hasta el suelo a mediados de abril. El contraste entre el sereno salón principal de madera y los cerezos crea una escena pictórica, querida por los lugareños.`,
    "松本市新村": `Niimura, al oeste de Matsumoto, es una zona rural donde la línea Alpico Kotsu Kamikochi pasa entre arrozales, huertos y canales con las crestas de los Alpes del Norte al fondo: el campo japonés clásico. Caminos con cerezos en primavera, arrozales verdes a inicios de verano y arroz maduro en otoño con los Alpes nevados.`,
    "城山公園(松本市)": `El Parque Joyama en Matsumoto, a 650 m, está entre los «100 Mejores Lugares de Sakura de Japón». Unos 400 cerezos florecen mientras la plaza panorámica abarca el centro de Matsumoto, los Alpes del Norte y el monte Norikura. Cerezos con Alpes nevados componen una vista primaveral única de Matsumoto.`,
    "中町通り(松本市)": `La calle Nakamachi es un distrito histórico de almacenes «kura» en la antigua ciudad-castillo de Matsumoto. Muros blancos con baldosas «namako» negras conservan el ambiente de finales de Edo y Meiji. Cafés, talleres y galerías habitan los kura renovados: distrito vivo y turístico ideal para pasear y fotografiar.`,
    "高島公園(諏訪市)": `El Parque Takashima en Suwa se levanta sobre las ruinas del castillo Takashima, sede del clan Suwa. Llamado «Castillo Flotante de Suwa», su torre reconstruida y unos 100 cerezos en torno al foso florecen a mediados de abril. La torre reflejada en el foso con los cerezos es una escena primaveral icónica de Suwa.`,
    "諏訪湖": `El Lago Suwa, en el centro de Nagano a 759 m, es el mayor lago de la prefectura. Famoso por el «Omiwatari», cordones de hielo que emergen en pleno invierno, y los fuegos artificiales de verano. La inspiración del lago en la película «Your Name».`,
    "立石公園": `El Parque Tateishi, a 934 m sobre el Lago Suwa, ofrece un panorama del lago con Yatsugatake e incluso el Monte Fuji al fondo. De noche, Suwa centellea como un joyero. Famoso como sitio de peregrinaje del filme «Your Name», es fotogénico a toda hora.`,
  },
  fr: {
    "弘法山古墳": `Le Tumulus du Mont Kobo, à Matsumoto, est l'un des plus anciens tumuli en forme de trou de serrure de l'est du Japon (fin du IIIe siècle). À 650 m d'altitude, environ 4 000 cerisiers fleurissent à mi-avril. Le sommet offre un panorama de Matsumoto et des Alpes du Nord enneigées encadré par les cerisiers.`,
    "安養寺": `Anyo-ji est un ancien temple Jodo Shinshu à Matsumoto. Son cerisier pleureur centenaire laisse tomber jusqu'au sol des cascades rose pâle à mi-avril. Le contraste entre le sereine pavillon principal en bois et les cerisiers compose une scène picturale, chérie des habitants.`,
    "松本市新村": `Niimura, à l'ouest de Matsumoto, est une zone rurale où la ligne Alpico Kotsu Kamikochi traverse rizières, vergers et canaux avec les crêtes des Alpes du Nord en toile de fond — la campagne japonaise classique. Allées de cerisiers au printemps, rizières vertes au début de l'été, riz mûr en automne avec les Alpes enneigées.`,
    "城山公園(松本市)": `Le Parc Joyama à Matsumoto, à 650 m, figure parmi les «100 Meilleurs Lieux de Sakura du Japon». Environ 400 cerisiers fleurissent tandis que le belvédère embrasse le centre de Matsumoto, les Alpes du Nord et le mont Norikura. Cerisiers et Alpes enneigées composent une vue printanière unique à Matsumoto.`,
    "中町通り(松本市)": `La rue Nakamachi est un quartier historique de bâtiments «kura» dans l'ancienne ville-château de Matsumoto. Murs blancs et tuiles «namako» noires conservent l'atmosphère de la fin d'Edo et de Meiji. Cafés, ateliers et galeries occupent les kura rénovés : un quartier vivant et touristique idéal pour flâner et photographier.`,
    "高島公園(諏訪市)": `Le Parc Takashima à Suwa s'élève sur les ruines du château Takashima, siège du clan Suwa. Surnommé «Château Flottant de Suwa», sa tour reconstruite et une centaine de cerisiers autour des douves fleurissent à mi-avril. La tour reflétée dans les douves avec les cerisiers est une scène printanière emblématique de Suwa.`,
    "諏訪湖": `Le Lac Suwa, au centre de Nagano à 759 m, est le plus grand lac de la préfecture. Célèbre pour l'«Omiwatari», crêtes de glace qui surgissent au cœur de l'hiver, et les feux d'artifice estivaux. Inspiration du lac du film «Your Name».`,
    "立石公園": `Le Parc Tateishi, à 934 m au-dessus du Lac Suwa, offre un panorama sur le lac avec Yatsugatake et même le Mont Fuji à l'horizon. La nuit, Suwa scintille comme un écrin. Célèbre comme lieu de pèlerinage du film «Your Name», il est photogénique à toute heure.`,
  },
  de: {
    "弘法山古墳": `Das Kobo-Hügelgrab in Matsumoto ist eines der ältesten schlüssellochförmigen Hügelgräber Ostjapans (späte 3. Jahrhundert). Auf 650 m gelegen, blühen etwa 4.000 Kirschbäume Mitte April. Der Gipfel bietet ein Panorama von Matsumoto und den schneebedeckten Nordalpen, eingerahmt von Kirschblüten.`,
    "安養寺": `Anyo-ji ist ein alter Jodo-Shinshu-Tempel in Matsumoto. Sein hundertjähriger Trauerkirschbaum lässt Mitte April blassrosa Kaskaden bis zum Boden fallen. Der Kontrast zwischen der ruhigen hölzernen Haupthalle und den Kirschblüten ergibt eine malerische Szene, von Einheimischen geliebt.`,
    "松本市新村": `Niimura im Westen Matsumotos ist eine ländliche Gegend, wo die Alpico-Kotsu-Kamikochi-Linie an Reisfeldern, Obstgärten und Bewässerungskanälen vorbeiführt — gerahmt von den Kämmen der Nordalpen, klassisches japanisches Landleben. Kirschalleen im Frühling, grüne Reisfelder im Frühsommer, reifer Reis im Herbst mit verschneiten Alpen.`,
    "城山公園(松本市)": `Der Joyama-Park in Matsumoto auf 650 m gehört zu Japans «100 besten Sakura-Orten». Etwa 400 Kirschbäume blühen, während die Aussichtsplattform Matsumoto, die Nordalpen und den Berg Norikura umfasst. Kirschblüten mit verschneiten Alpen ergeben eine einzigartige Frühlingsansicht Matsumotos.`,
    "中町通り(松本市)": `Die Nakamachi-Straße ist ein historisches Viertel mit «kura»-Speicherbauten in der alten Burgstadt Matsumoto. Weiße Putzwände mit schwarzen «Namako»-Kachelmustern bewahren die Stimmung der späten Edo- und Meiji-Zeit. Renovierte Kura beherbergen Cafés, Werkstätten und Galerien — ein lebendiges Viertel zum Schlendern und Fotografieren.`,
    "高島公園(諏訪市)": `Der Takashima-Park in Suwa steht auf den Ruinen der Takashima-Burg, dem Sitz des Suwa-Clans. Einst «Suwas schwimmende Burg» genannt; sein rekonstruierter Turm und etwa 100 Kirschbäume rund um den Burggraben blühen Mitte April. Der im Graben gespiegelte Turm mit Kirschblüten ist eine ikonische Frühlingsszene Suwas.`,
    "諏訪湖": `Der Suwa-See in der zentralen Nagano-Präfektur auf 759 m ist der größte See der Präfektur. Berühmt für «Omiwatari» — Eisrücken, die im tiefen Winter aus der Oberfläche aufsteigen — und das sommerliche Feuerwerk. Vorbild für den See im Film «Your Name».`,
    "立石公園": `Der Tateishi-Park, 934 m über dem Suwa-See, bietet ein Panorama über den See mit Yatsugatake und sogar dem Berg Fuji im Hintergrund. Nachts funkelt Suwa wie eine Schmuckschatulle. Berühmt als Pilgerstätte für den Film «Your Name», ist er zu jeder Stunde fotogen.`,
  },
  pt: {
    "弘法山古墳": `O Túmulo do Monte Kobo, em Matsumoto, é um dos mais antigos túmulos em forma de buraco de fechadura do leste do Japão (fim do século III). A 650 m de altitude, cerca de 4.000 cerejeiras florescem em meados de abril. O cume oferece um panorama de Matsumoto e dos Alpes do Norte nevados emoldurados pelas cerejeiras.`,
    "安養寺": `Anyo-ji é um antigo templo Jodo Shinshu em Matsumoto. Sua cerejeira chorona centenária faz cascatas rosa pálido caírem até o chão em meados de abril. O contraste entre o sereno salão principal de madeira e as cerejeiras cria uma cena pictórica, amada pelos locais.`,
    "松本市新村": `Niimura, a oeste de Matsumoto, é uma área rural onde a linha Alpico Kotsu Kamikochi passa entre arrozais, pomares e canais com as cristas dos Alpes do Norte ao fundo — campo japonês clássico. Caminhos de cerejeiras na primavera, arrozais verdes no início do verão, arroz maduro no outono com Alpes nevados.`,
    "城山公園(松本市)": `O Parque Joyama em Matsumoto, a 650 m, está entre os «100 Melhores Locais de Sakura do Japão». Cerca de 400 cerejeiras florescem enquanto a praça mirante abrange o centro de Matsumoto, os Alpes do Norte e o monte Norikura. Cerejeiras com Alpes nevados compõem uma vista primaveril única de Matsumoto.`,
    "中町通り(松本市)": `A rua Nakamachi é um distrito histórico de armazéns «kura» na antiga cidade-castelo de Matsumoto. Paredes brancas com azulejos «namako» pretos preservam a atmosfera do final de Edo e Meiji. Cafés, oficinas e galerias ocupam os kura renovados — distrito vivo e turístico ideal para passear e fotografar.`,
    "高島公園(諏訪市)": `O Parque Takashima em Suwa ergue-se sobre as ruínas do castelo Takashima, sede do clã Suwa. Outrora chamado «Castelo Flutuante de Suwa», sua torre reconstruída e cerca de 100 cerejeiras em torno do fosso florescem em meados de abril. A torre refletida no fosso com cerejeiras é uma cena primaveril icônica de Suwa.`,
    "諏訪湖": `O Lago Suwa, no centro de Nagano a 759 m, é o maior lago da prefeitura. Famoso pelo «Omiwatari», cristas de gelo que emergem no auge do inverno, e pelos fogos de artifício de verão. Inspiração para o lago do filme «Your Name».`,
    "立石公園": `O Parque Tateishi, a 934 m acima do Lago Suwa, oferece um panorama do lago com Yatsugatake e até o Monte Fuji ao fundo. À noite, Suwa cintila como uma joalheira. Famoso como local de peregrinação do filme «Your Name», é fotogênico a qualquer hora.`,
  },
  it: {
    "弘法山古墳": `Il Tumulo del Monte Kobo, a Matsumoto, è uno dei più antichi tumuli a forma di buco della serratura del Giappone orientale (fine III secolo). A 650 m di altitudine, circa 4.000 ciliegi fioriscono a metà aprile. La cima offre un panorama di Matsumoto e delle Alpi Settentrionali innevate incorniciato dai ciliegi.`,
    "安養寺": `Anyo-ji è un antico tempio Jodo Shinshu a Matsumoto. Il suo ciliegio piangente centenario lascia cadere fino a terra cascate rosa pallido a metà aprile. Il contrasto tra la sala principale lignea serena e i ciliegi crea una scena pittorica, amata dagli abitanti del luogo.`,
    "松本市新村": `Niimura, a ovest di Matsumoto, è una zona rurale dove la linea Alpico Kotsu Kamikochi passa tra risaie, frutteti e canali con le creste delle Alpi Settentrionali sullo sfondo — la classica campagna giapponese. Vialetti di ciliegi in primavera, risaie verdi a inizio estate, riso maturo in autunno con Alpi innevate.`,
    "城山公園(松本市)": `Il Parco Joyama a Matsumoto, a 650 m, è tra i «100 Migliori Luoghi di Sakura del Giappone». Circa 400 ciliegi fioriscono mentre la piazza panoramica abbraccia il centro di Matsumoto, le Alpi Settentrionali e il monte Norikura. Ciliegi e Alpi innevate compongono una vista primaverile unica di Matsumoto.`,
    "中町通り(松本市)": `La via Nakamachi è un quartiere storico di edifici «kura» nell'antica città-castello di Matsumoto. Muri bianchi con piastrelle «namako» nere conservano l'atmosfera di fine Edo e Meiji. Caffè, botteghe e gallerie occupano i kura rinnovati — un quartiere vivo e turistico ideale per passeggiare e fotografare.`,
    "高島公園(諏訪市)": `Il Parco Takashima a Suwa sorge sulle rovine del castello Takashima, sede del clan Suwa. Detto «Castello Galleggiante di Suwa», la sua torre ricostruita e circa 100 ciliegi attorno al fossato fioriscono a metà aprile. La torre riflessa nel fossato con i ciliegi è una scena primaverile iconica di Suwa.`,
    "諏訪湖": `Il Lago Suwa, nel centro di Nagano a 759 m, è il lago più grande della prefettura. Famoso per l'«Omiwatari», creste di ghiaccio che emergono in pieno inverno, e per i fuochi d'artificio estivi. Ispirazione del lago nel film «Your Name».`,
    "立石公園": `Il Parco Tateishi, a 934 m sopra il Lago Suwa, offre un panorama sul lago con Yatsugatake e persino il Monte Fuji sullo sfondo. Di notte, Suwa scintilla come uno scrigno di gioielli. Famoso come luogo di pellegrinaggio del film «Your Name», è fotogenico a ogni ora.`,
  },
  ru: {
    "弘法山古墳": `Курган Кобояма в Мацумото — один из старейших курганов в форме замочной скважины восточной Японии (конец III века). На высоте 650 м около 4000 сакур цветут в середине апреля. Вершина открывает панораму Мацумото и заснеженных Северных Альп в обрамлении сакуры.`,
    "安養寺": `Анъё-дзи — старый храм школы Дзёдо-синсю в Мацумото. Столетняя плакучая сакура в саду в середине апреля роняет до земли каскады бледно-розовых цветов. Контраст спокойного деревянного главного зала и сакуры создаёт живописную сцену, любимую местными жителями.`,
    "松本市新村": `Ниимура к западу от Мацумото — сельская местность, где линия Альпико Косу Камикоти проходит мимо рисовых полей, фруктовых садов и каналов на фоне хребтов Северных Альп — классическая японская деревня. Аллеи сакур весной, зелёные поля в начале лета, спелый рис осенью с заснеженными Альпами.`,
    "城山公園(松本市)": `Парк Дзёяма в Мацумото на высоте 650 м входит в «100 лучших мест сакуры Японии». Около 400 сакур цветут, а смотровая площадка охватывает центр Мацумото, Северные Альпы и гору Норикура. Сакура и заснеженные Альпы составляют уникальный весенний вид Мацумото.`,
    "中町通り(松本市)": `Улица Накамати — исторический квартал амбаров «кура» в старом замковом городе Мацумото. Белые штукатурные стены с чёрной плиткой «намако» хранят атмосферу позднего периода Эдо и Мэйдзи. Кафе, мастерские и галереи занимают обновлённые кура — живой и туристический квартал, идеальный для прогулок и съёмки.`,
    "高島公園(諏訪市)": `Парк Такасима в Суве стоит на руинах замка Такасима, резиденции клана Сува. Прозванный «Плавучим замком Сувы», его реконструированная башня и около 100 сакур вокруг рва зацветают в середине апреля. Башня, отражённая во рву с сакурой, — знаковая весенняя сцена Сувы.`,
    "諏訪湖": `Озеро Сува в центральной части Нагано на высоте 759 м — крупнейшее озеро префектуры. Знаменито «Омивата́ри» — ледяными гребнями, поднимающимися из поверхности в середине зимы — и летним фейерверком. Прообраз озера в фильме «Твоё имя».`,
    "立石公園": `Парк Татэйси на высоте 934 м над озером Сува открывает панораму на озеро с Яцугатакэ и даже горой Фудзи вдали. Ночью Сува сверкает как шкатулка с драгоценностями. Известный как место паломничества к фильму «Твоё имя», он фотогеничен в любое время.`,
  },
  ar: {
    "弘法山古墳": `تل كوبو الجنائزي في ماتسوموتو من أقدم التلال الجنائزية على شكل ثقب المفتاح في شرق اليابان (أواخر القرن الثالث). على ارتفاع 650 م، تتفتح نحو 4000 شجرة كرز في منتصف أبريل. تطل القمة على بانوراما ماتسوموتو وجبال الألب الشمالية المغطاة بالثلوج المؤطرة بأزهار الكرز.`,
    "安養寺": `أنيوجي معبد قديم لطائفة جودو شينشو في ماتسوموتو. شجرة الكرز الباكية المئوية تسقط شلالات وردية شاحبة حتى الأرض في منتصف أبريل. التباين بين القاعة الرئيسية الخشبية الهادئة وأزهار الكرز يخلق مشهداً تصويرياً يحبه السكان المحليون.`,
    "松本市新村": `نيمورا غرب ماتسوموتو منطقة ريفية يمر فيها خط ألبيكو كوتسو كاميكوتشي بحقول الأرز والبساتين والقنوات على خلفية قمم جبال الألب الشمالية — ريف ياباني كلاسيكي. ممرات الكرز ربيعاً، حقول أرز خضراء أوائل الصيف، أرز ناضج خريفاً مع جبال الألب الثلجية.`,
    "城山公園(松本市)": `حديقة جوياما في ماتسوموتو على ارتفاع 650 م، ضمن «أفضل 100 موقع ساكورا في اليابان». نحو 400 شجرة كرز تتفتح بينما تطل ساحة المرصد على وسط ماتسوموتو وجبال الألب الشمالية وجبل نوريكورا. أزهار الكرز مع جبال الألب الثلجية تكون مشهداً ربيعياً فريداً لماتسوموتو.`,
    "中町通り(松本市)": `شارع ناكاماتشي حي تاريخي لمباني «كورا» المخزنية في بلدة ماتسوموتو القلعية القديمة. جدران بيضاء مع بلاط «ناماكو» أسود تحفظ أجواء أواخر إيدو وميجي. مقاهٍ وورش وغاليريهات في الكورا المجددة — حي حي وسياحي مثالي للتجول والتصوير.`,
    "高島公園(諏訪市)": `حديقة تاكاشيما في سووا ترتفع على أنقاض قلعة تاكاشيما، مقر عشيرة سووا. كانت تُسمى «قلعة سووا العائمة»، برجها المُعاد بناؤه ونحو 100 شجرة كرز حول الخندق تتفتح في منتصف أبريل. البرج المنعكس في الخندق مع الكرز مشهد ربيعي أيقوني لسووا.`,
    "諏訪湖": `بحيرة سووا في وسط ناغانو على ارتفاع 759 م أكبر بحيرة في المحافظة. مشهورة بـ«أوميواتاري» — حواف جليدية تنهض من السطح في أعماق الشتاء — وبألعاب نارية صيفية. إلهام البحيرة في فيلم «Your Name».`,
    "立石公園": `حديقة تاتيشي على ارتفاع 934 م فوق بحيرة سووا تقدم بانوراما للبحيرة مع ياتسوغاتاكي وحتى جبل فوجي في الأفق. ليلاً تلمع سووا كصندوق مجوهرات. مشهورة كموقع حج لفيلم «Your Name»، وفوتوجينية في كل ساعة.`,
  },
  hi: {
    "弘法山古墳": `मात्सुमोतो में कोबो पर्वत समाधि पूर्वी जापान की सबसे पुरानी keyhole-आकार की समाधियों में से एक है (तीसरी सदी के अंत में निर्मित)। 650 मीटर की ऊँचाई पर लगभग 4000 चेरी पेड़ अप्रैल मध्य में खिलते हैं। शिखर से मात्सुमोतो और बर्फ ढके उत्तरी आल्प्स का चेरी फूलों से घिरा पैनोरमा दिखता है।`,
    "安養寺": `अन्यो-जी मात्सुमोतो में एक पुराना जोडो शिंशू मंदिर है। सदी पुराना रोता हुआ चेरी पेड़ अप्रैल मध्य में हल्का गुलाबी झरना ज़मीन तक गिराता है। शांत लकड़ी का मुख्य हॉल और चेरी फूलों का विरोधाभास एक चित्रात्मक दृश्य बनाता है, स्थानीय लोगों का प्रिय स्थान।`,
    "松本市新村": `मात्सुमोतो के पश्चिम में नीमुरा एक ग्रामीण क्षेत्र है जहाँ अल्पिको कोत्सू कामिकोची लाइन धान के खेतों, बागानों और नहरों के बीच से गुज़रती है, उत्तरी आल्प्स की पृष्ठभूमि के साथ — क्लासिक जापानी ग्रामीण परिदृश्य। वसंत में चेरी मार्ग, ग्रीष्मारंभ में हरे खेत, शरद में पकी धान और बर्फीले आल्प्स।`,
    "城山公園(松本市)": `मात्सुमोतो के जोयामा पार्क की ऊँचाई 650 मीटर है और यह «जापान के 100 सर्वश्रेष्ठ साकुरा स्थलों» में शामिल है। लगभग 400 चेरी पेड़ खिलते हैं, और दर्शन चौक से मात्सुमोतो शहर, उत्तरी आल्प्स और नोरिकुरा पर्वत का पैनोरमा दिखता है। चेरी और बर्फीले आल्प्स मिलकर मात्सुमोतो का अनूठा वसंत दृश्य रचते हैं।`,
    "中町通り(松本市)": `नकामाची स्ट्रीट पुरानी मात्सुमोतो किला नगरी का «कुरा» गोदाम-शैली का ऐतिहासिक क्षेत्र है। काले «नामाको» टाइल पैटर्न वाली सफेद दीवारें एडो अंत और मेईजी काल का माहौल संरक्षित करती हैं। नवीकृत कुरा में कैफे, शिल्प की दुकानें और गैलरीज़ — टहलने और फोटो खींचने के लिए आदर्श।`,
    "高島公園(諏訪市)": `सुवा का ताकाशिमा पार्क सुवा कुल के निवास ताकाशिमा कैसल के अवशेष पर बना है। «सुवा का तैरता हुआ कैसल» कहलाता था; पुनर्निर्मित मीनार और खाई के चारों ओर लगभग 100 चेरी पेड़ अप्रैल मध्य में खिलते हैं। खाई में प्रतिबिंबित मीनार और चेरी सुवा का प्रतीकात्मक वसंत दृश्य।`,
    "諏訪湖": `नागानो के मध्य में 759 मीटर ऊँचाई पर सुवा झील प्रांत की सबसे बड़ी झील है। शीत ऋतु में सतह से उठने वाली बर्फ की मेड़ें «ओमिवातारी» और गर्मियों की आतिशबाजी के लिए प्रसिद्ध। फिल्म «Your Name» की झील की प्रेरणा।`,
    "立石公園": `सुवा झील के 934 मीटर ऊपर ताते्इशी पार्क झील का यात्सुगाताके और यहाँ तक कि माउंट फुजी तक का पैनोरमा देता है। रात को सुवा गहनों के डिब्बे की तरह जगमगाता है। फिल्म «Your Name» के तीर्थ स्थल के रूप में प्रसिद्ध, हर समय फोटोजेनिक।`,
  },
  th: {
    "弘法山古墳": `สุสานเขาโคโบในมัตสึโมโตะเป็นหนึ่งในสุสานรูปรูกุญแจเก่าแก่ที่สุดในญี่ปุ่นตะวันออก (สร้างปลายศตวรรษที่ 3) อยู่ที่ความสูง 650 ม. มีต้นซากุระราว 4,000 ต้นบานกลางเดือนเมษายน ยอดให้ทัศนียภาพเมืองมัตสึโมโตะและเทือกเขาแอลป์เหนือที่มีหิมะปกคลุมในกรอบดอกซากุระ`,
    "安養寺": `วัดอันโยจิเป็นวัดเก่าแก่นิกายโจโดะชินชูในมัตสึโมโตะ ต้นซากุระร้องไห้อายุเกินร้อยปีปล่อยม่านดอกสีชมพูจางลงสู่พื้นกลางเมษายน ความตัดกันระหว่างวิหารหลักไม้สงบนิ่งกับดอกซากุระสร้างฉากภาพวาด เป็นที่รักของคนท้องถิ่น`,
    "松本市新村": `นีมุระทางตะวันตกของมัตสึโมะโตะเป็นพื้นที่ชนบทที่สาย Alpico Kotsu Kamikochi ผ่านนาข้าว สวนผลไม้ คลอง และสันเขาแอลป์เหนือ — ชนบทญี่ปุ่นคลาสสิก เส้นทางซากุระในฤดูใบไม้ผลิ นาเขียวต้นฤดูร้อน ข้าวสุกฤดูใบไม้ร่วงพร้อมแอลป์หิมะ`,
    "城山公園(松本市)": `สวนโจยามะในมัตสึโมโตะที่ความสูง 650 ม. ติดอันดับ «100 จุดซากุระยอดเยี่ยมของญี่ปุ่น» ต้นซากุระราว 400 ต้นบานพร้อมจุดชมวิวที่กว้างถึงใจกลางมัตสึโมโตะ เทือกเขาแอลป์เหนือ และภูเขาโนริคุระ ดอกซากุระกับเทือกเขาแอลป์หิมะรวมเป็นทัศนียภาพฤดูใบไม้ผลิเอกลักษณ์ของมัตสึโมโตะ`,
    "中町通り(松本市)": `ถนนนากามาจิเป็นย่านประวัติศาสตร์ของอาคารคลังเก็บแบบ «คุระ» ในเมืองปราสาทเก่ามัตสึโมโตะ ผนังปูนขาวกับลวดลาย «นามาโกะ» สีดำเก็บบรรยากาศปลายเอโดะและเมจิ ร้านกาแฟ ร้านงานฝีมือ และแกลเลอรีในคุระที่ปรับปรุงใหม่ — ย่านมีชีวิตและท่องเที่ยวเหมาะสำหรับเดินถ่ายภาพ`,
    "高島公園(諏訪市)": `สวนทาคาชิมะในสึวะตั้งบนซากปราสาททาคาชิมะ ที่นั่งของตระกูลสึวะ เคยเรียกว่า «ปราสาทลอยน้ำของสึวะ» หอคอยที่สร้างใหม่และต้นซากุระราว 100 ต้นรอบคูเมืองบานกลางเมษายน หอคอยสะท้อนในคูเมืองพร้อมซากุระเป็นทัศนียภาพฤดูใบไม้ผลิเอกลักษณ์ของสึวะ`,
    "諏訪湖": `ทะเลสาบสึวะในใจกลางนากาโนที่ความสูง 759 ม. เป็นทะเลสาบที่ใหญ่ที่สุดในจังหวัด มีชื่อเสียงเรื่อง «โอมิวาตาริ» — สันน้ำแข็งที่ผุดจากผิวน้ำกลางฤดูหนาว และเทศกาลพลุฤดูร้อน เป็นแรงบันดาลใจของทะเลสาบในภาพยนตร์ «Your Name»`,
    "立石公園": `สวนทาเทอิชิที่ความสูง 934 ม. เหนือทะเลสาบสึวะให้ทัศนียภาพทะเลสาบกับยัตสึงาตาเกะและแม้แต่ภูเขาฟูจิที่ขอบฟ้า กลางคืนสึวะส่องประกายเหมือนกล่องอัญมณี มีชื่อเสียงในฐานะสถานที่แสวงบุญของภาพยนตร์ «Your Name» ถ่ายภาพได้ทุกเวลา`,
  },
  vi: {
    "弘法山古墳": `Mộ cổ núi Kobo ở Matsumoto là một trong những mộ cổ hình lỗ khóa cổ nhất Đông Nhật Bản (xây cuối thế kỷ III). Ở độ cao 650 m, khoảng 4.000 cây hoa anh đào nở rộ giữa tháng Tư. Đỉnh cho toàn cảnh Matsumoto và dãy Alps Bắc tuyết phủ trong khung hoa anh đào.`,
    "安養寺": `Anyo-ji là chùa Jodo Shinshu cổ ở Matsumoto. Cây hoa anh đào rủ trăm năm tuổi thả những thác hoa hồng nhạt xuống tận đất giữa tháng Tư. Sự tương phản giữa chánh điện gỗ thanh tịnh và hoa anh đào tạo nên cảnh tượng như tranh, được người địa phương yêu mến.`,
    "松本市新村": `Niimura ở phía tây Matsumoto là vùng nông thôn nơi tuyến Alpico Kotsu Kamikochi đi qua ruộng lúa, vườn cây và kênh tưới với những đỉnh núi Alps Bắc làm hậu cảnh — quê hương Nhật Bản cổ điển. Đường hoa anh đào mùa xuân, ruộng xanh đầu hè, lúa chín mùa thu cùng Alps tuyết.`,
    "城山公園(松本市)": `Công viên Joyama ở Matsumoto cao 650 m, nằm trong «100 địa điểm sakura tốt nhất Nhật Bản». Khoảng 400 cây hoa anh đào nở rộ trong khi quảng trường ngắm cảnh ôm trọn trung tâm Matsumoto, Alps Bắc và núi Norikura. Hoa anh đào với Alps tuyết tạo nên cảnh xuân độc đáo của Matsumoto.`,
    "中町通り(松本市)": `Phố Nakamachi là khu lịch sử với kiến trúc kho «kura» ở thành phố lâu đài cổ Matsumoto. Tường trắng với họa tiết ngói «namako» đen lưu giữ không khí cuối Edo và Meiji. Quán cà phê, xưởng thủ công và phòng tranh chiếm các kura được tu sửa — khu vực sống động lý tưởng để dạo và chụp ảnh.`,
    "高島公園(諏訪市)": `Công viên Takashima ở Suwa nằm trên di tích thành Takashima, dinh của gia tộc Suwa. Từng được gọi là «Lâu đài nổi của Suwa», tháp được tái dựng và khoảng 100 cây hoa anh đào quanh hào nở rộ giữa tháng Tư. Tháp phản chiếu trong hào với hoa anh đào là cảnh xuân biểu tượng của Suwa.`,
    "諏訪湖": `Hồ Suwa ở trung tâm Nagano cao 759 m là hồ lớn nhất tỉnh. Nổi tiếng với «Omiwatari» — những gờ băng nổi lên từ mặt hồ giữa mùa đông sâu — và pháo hoa mùa hè. Cảm hứng cho hồ trong phim «Your Name».`,
    "立石公園": `Công viên Tateishi cao 934 m bên trên hồ Suwa cho toàn cảnh hồ với Yatsugatake và cả núi Phú Sĩ phía xa. Đêm Suwa lấp lánh như hộp trang sức. Nổi tiếng là điểm hành hương của phim «Your Name», đẹp ảnh ở mọi thời khắc.`,
  },
  id: {
    "弘法山古墳": `Makam Kuno Gunung Kobo di Matsumoto adalah salah satu makam berbentuk lubang kunci tertua di Jepang timur (akhir abad ke-3). Pada ketinggian 650 m, sekitar 4.000 pohon sakura mekar pertengahan April. Puncaknya menawarkan panorama Matsumoto dan Pegunungan Alpen Utara bersalju yang dibingkai bunga sakura.`,
    "安養寺": `Anyo-ji adalah kuil Jodo Shinshu kuno di Matsumoto. Pohon sakura menangis seabad jatuhkan air terjun bunga merah muda pucat hingga tanah pertengahan April. Kontras antara aula utama kayu tenang dan sakura menciptakan adegan seperti lukisan, dicintai warga setempat.`,
    "松本市新村": `Niimura di barat Matsumoto adalah area pedesaan tempat jalur Alpico Kotsu Kamikochi melewati sawah, kebun buah dan saluran irigasi dengan punggung Alpen Utara di latar — pedesaan Jepang klasik. Jalan-jalan sakura di musim semi, sawah hijau awal musim panas, padi matang musim gugur dengan Alpen bersalju.`,
    "城山公園(松本市)": `Taman Joyama di Matsumoto pada 650 m termasuk dalam «100 Lokasi Sakura Terbaik Jepang». Sekitar 400 pohon sakura mekar sementara plaza pengamatan mencakup pusat Matsumoto, Alpen Utara, dan Gunung Norikura. Sakura dengan Alpen bersalju menjadi pemandangan musim semi unik Matsumoto.`,
    "中町通り(松本市)": `Jalan Nakamachi adalah distrik bersejarah bangunan gudang «kura» di kota kastil tua Matsumoto. Dinding plester putih dengan pola ubin «namako» hitam mempertahankan suasana akhir Edo dan Meiji. Kafe, bengkel, dan galeri menempati kura yang direnovasi — distrik hidup yang ideal untuk berjalan dan memotret.`,
    "高島公園(諏訪市)": `Taman Takashima di Suwa berdiri di atas reruntuhan Kastil Takashima, kediaman klan Suwa. Pernah disebut «Kastil Mengapung Suwa», menara yang direkonstruksi dan sekitar 100 pohon sakura di sekitar parit mekar pertengahan April. Menara terpantul di parit dengan sakura adalah pemandangan musim semi ikonik Suwa.`,
    "諏訪湖": `Danau Suwa di Nagano tengah pada 759 m adalah danau terbesar prefektur. Terkenal akan «Omiwatari» — punggungan es yang muncul dari permukaan di tengah musim dingin — dan kembang api musim panas. Inspirasi danau di film «Your Name».`,
    "立石公園": `Taman Tateishi pada 934 m di atas Danau Suwa menawarkan panorama danau dengan Yatsugatake dan bahkan Gunung Fuji di kejauhan. Pada malam hari Suwa berkilau seperti kotak perhiasan. Terkenal sebagai lokasi ziarah film «Your Name», fotogenik setiap waktu.`,
  },
  tr: {
    "弘法山古墳": `Matsumoto'daki Kobo Dağı Höyüğü, doğu Japonya'nın en eski anahtar deliği biçimli höyüklerinden biridir (3. yüzyıl sonu). 650 m yükseklikte yaklaşık 4.000 kiraz ağacı Nisan ortasında çiçek açar. Zirvede Matsumoto ve karla kaplı Kuzey Alpleri'nin kiraz çiçekleriyle çerçevelenmiş panoraması bulunur.`,
    "安養寺": `Anyo-ji, Matsumoto'da eski bir Jodo Shinshu tapınağıdır. Yüz yıllık ağlayan kiraz ağacı Nisan ortasında soluk pembe çağlayanları yere kadar düşürür. Sakin ahşap ana salon ve kiraz çiçeklerinin kontrastı resimsi bir sahne yaratır, yerel halkın sevdiği bir mekândır.`,
    "松本市新村": `Matsumoto'nun batısındaki Niimura, Alpico Kotsu Kamikochi hattının pirinç tarlaları, meyve bahçeleri ve sulama kanallarının arasından Kuzey Alpleri sırtlarıyla geçtiği kırsal bir bölgedir — klasik Japon kırsalı. İlkbaharda kiraz yolları, yaz başında yeşil tarlalar, sonbaharda olgun pirinç ile karlı Alpler.`,
    "城山公園(松本市)": `Matsumoto'daki Joyama Parkı 650 m yükseklikte ve Japonya'nın «En İyi 100 Sakura Yeri» arasında. Yaklaşık 400 kiraz ağacı çiçek açarken gözlem alanı Matsumoto merkezini, Kuzey Alpleri'ni ve Norikura Dağı'nı kapsar. Kiraz çiçekleri ve karlı Alpler Matsumoto'ya özgü ilkbahar manzarasını oluşturur.`,
    "中町通り(松本市)": `Nakamachi Sokağı, eski kale-kent Matsumoto'da «kura» depo binalarının tarihi mahallesidir. Siyah «namako» fayans desenli beyaz alçı duvarlar geç Edo ve Meiji havasını korur. Kahveler, atölyeler ve galeriler yenilenmiş kura'larda yer alır — yürüyüş ve fotoğraf için ideal canlı turistik mahalle.`,
    "高島公園(諏訪市)": `Suwa'daki Takashima Parkı, Suwa klanının ikametgahı Takashima Kalesi'nin kalıntıları üzerinde yer alır. Bir zamanlar «Suwa'nın Yüzen Kalesi» denilen yeniden inşa edilmiş kulesi ve hendek çevresindeki yaklaşık 100 kiraz ağacı Nisan ortasında çiçek açar. Hendekte yansıyan kule ve kiraz Suwa'nın ikonik ilkbahar sahnesidir.`,
    "諏訪湖": `Nagano'nun ortasında 759 m yükseklikteki Suwa Gölü, ilin en büyük gölüdür. Kış ortasında yüzeyden yükselen buz sırtları «Omiwatari» ve yaz havai fişekleriyle ünlüdür. «Your Name» filmindeki gölün ilhamı.`,
    "立石公園": `Suwa Gölü'nün 934 m üzerindeki Tateishi Parkı, gölün Yatsugatake ve hatta uzaktan Fuji Dağı manzarasını sunar. Geceleri Suwa mücevher kutusu gibi parıldar. «Your Name» filminin hac yeri olarak ünlü, her saatte fotojenik.`,
  },
  nl: {
    "弘法山古墳": `Het Kobo-berg Grafheuvel in Matsumoto is een van de oudste sleutelgatvormige grafheuvels in oost-Japan (eind 3e eeuw). Op 650 m hoogte bloeien zo'n 4.000 kersenbomen half april. De top biedt een panorama van Matsumoto en de besneeuwde Noordelijke Alpen omlijst door kersenbloesem.`,
    "安養寺": `Anyo-ji is een oude Jodo Shinshu-tempel in Matsumoto. De honderdjarige treurkers laat half april bleekroze cascades tot aan de grond hangen. Het contrast tussen de serene houten hoofdhal en de kersenbloesem schept een schilderachtig tafereel, geliefd bij de lokale bewoners.`,
    "松本市新村": `Niimura, ten westen van Matsumoto, is een landelijk gebied waar de Alpico Kotsu Kamikochi-lijn rijstvelden, boomgaarden en irrigatiekanalen passeert met de kammen van de Noordelijke Alpen op de achtergrond — klassiek Japans platteland. Kersenpaden in lente, groene rijstvelden in vroege zomer, rijpe rijst in herfst met besneeuwde Alpen.`,
    "城山公園(松本市)": `Joyama-park in Matsumoto op 650 m hoort bij Japans «100 Beste Sakura-plekken». Zo'n 400 kersenbomen bloeien terwijl het uitkijkplein heel Matsumoto-centrum, de Noordelijke Alpen en de Norikura omarmt. Kersenbloesem met besneeuwde Alpen vormt een unieke Matsumoto-lentevisie.`,
    "中町通り(松本市)": `Nakamachi-straat is een historisch district van «kura»-pakhuizen in de oude kasteelstad Matsumoto. Witte stucmuren met zwarte «namako»-tegelpatronen behouden de sfeer van laat-Edo en Meiji. Cafés, ateliers en galerieën bewonen de gerenoveerde kura — een levendig, toeristisch district ideaal voor wandelen en fotograferen.`,
    "高島公園(諏訪市)": `Takashima-park in Suwa staat op de ruïnes van Kasteel Takashima, zetel van de Suwa-clan. Ooit «Suwa's drijvend kasteel» genoemd, blozen de gereconstrueerde toren en zo'n 100 kersenbomen rond de slotgracht half april. De toren weerspiegeld in de slotgracht met kersenbloesem is een iconisch Suwa-lentebeeld.`,
    "諏訪湖": `Het Suwameer in centraal Nagano op 759 m is het grootste meer van de prefectuur. Beroemd om «Omiwatari» — ijsruggen die in diepe winter uit het oppervlak rijzen — en zomervuurwerk. Inspiratie voor het meer in de film «Your Name».`,
    "立石公園": `Tateishi-park, 934 m boven het Suwameer, biedt een panorama van het meer met Yatsugatake en zelfs de Fuji op de achtergrond. 's Nachts schittert Suwa als een juwelendoosje. Beroemd als pelgrimsoord van «Your Name», fotogeniek op elk uur.`,
  },
  pl: {
    "弘法山古墳": `Kurhan Kobo w Matsumoto to jeden z najstarszych kurhanów w kształcie dziurki od klucza we wschodniej Japonii (koniec III wieku). Na wysokości 650 m, około 4.000 wiśni kwitnie w połowie kwietnia. Szczyt oferuje panoramę Matsumoto i ośnieżonych Alp Północnych obramowanych kwiatami wiśni.`,
    "安養寺": `Anyo-ji to stara świątynia Jodo Shinshu w Matsumoto. Stuletnia wiśnia płacząca opada w połowie kwietnia bladoróżowymi kaskadami aż do ziemi. Kontrast spokojnej drewnianej sali głównej z kwiatami wiśni tworzy malarską scenę, ukochaną przez mieszkańców.`,
    "松本市新村": `Niimura na zachód od Matsumoto to wiejski obszar, gdzie linia Alpico Kotsu Kamikochi mija pola ryżowe, sady i kanały na tle grzbietów Alp Północnych — klasyczna japońska wieś. Wiśniowe alejki wiosną, zielone pola wczesnym latem, dojrzały ryż jesienią z ośnieżonymi Alpami.`,
    "城山公園(松本市)": `Park Joyama w Matsumoto na 650 m należy do «100 Najlepszych Miejsc Sakura Japonii». Około 400 wiśni kwitnie, a plac widokowy obejmuje centrum Matsumoto, Alpy Północne i górę Norikura. Wiśnie z ośnieżonymi Alpami tworzą wyjątkowy widok wiosenny Matsumoto.`,
    "中町通り(松本市)": `Ulica Nakamachi to historyczna dzielnica budynków magazynowych «kura» w starym mieście-zamku Matsumoto. Białe tynkowane ściany z czarnym wzorem płytek «namako» zachowują atmosferę późnego Edo i Meiji. Kawiarnie, warsztaty i galerie zajmują odnowione kura — żywa i turystyczna dzielnica idealna do spacerów i fotografowania.`,
    "高島公園(諏訪市)": `Park Takashima w Suwa stoi na ruinach zamku Takashima, siedzibie klanu Suwa. Niegdyś zwany «Pływającym Zamkiem Suwa», jego odbudowana wieża i około 100 wiśni wokół fosy kwitnie w połowie kwietnia. Wieża odbita w fosie z kwiatami wiśni to ikoniczna scena wiosenna Suwa.`,
    "諏訪湖": `Jezioro Suwa w środkowej Nagano na 759 m to największe jezioro prefektury. Znane z «Omiwatari» — lodowych grzbietów wynurzających się z powierzchni w środku zimy — i letnich fajerwerków. Inspiracja dla jeziora w filmie «Your Name».`,
    "立石公園": `Park Tateishi na 934 m nad Jeziorem Suwa oferuje panoramę jeziora z Yatsugatake i nawet górą Fuji w oddali. Nocą Suwa lśni jak szkatułka klejnotów. Słynny jako miejsce pielgrzymek do filmu «Your Name», fotogeniczny o każdej porze.`,
  },
  sv: {
    "弘法山古墳": `Kobo-bergets gravhög i Matsumoto är en av östra Japans äldsta nyckelhålsformade gravhögar (sent 300-tal). På 650 m höjd blommar ungefär 4.000 körsbärsträd i mitten av april. Toppen ger en panorama över Matsumoto och de snötäckta Norra Alperna inramade av körsbärsblommor.`,
    "安養寺": `Anyo-ji är ett gammalt Jodo Shinshu-tempel i Matsumoto. Det hundraåriga sörjande körsbärsträdet låter blekrosa kaskader falla ända ner till marken i mitten av april. Kontrasten mellan den rofyllda trähuvudhallen och körsbärsblommorna skapar en målerisk scen, älskad av de lokala invånarna.`,
    "松本市新村": `Niimura, väster om Matsumoto, är ett lantligt område där Alpico Kotsu Kamikochi-linjen passerar risfält, fruktodlingar och bevattningskanaler med Norra Alpernas åsar i bakgrunden — den klassiska japanska landsbygden. Körsbärsstigar på våren, gröna risfält i tidig sommar, mogen ris i höst med snötäckta Alper.`,
    "城山公園(松本市)": `Joyama-parken i Matsumoto på 650 m hör till Japans «100 Bästa Sakura-platser». Omkring 400 körsbärsträd blommar medan utsiktstorget omfattar Matsumotos centrum, Norra Alperna och berget Norikura. Körsbärsblommor med snötäckta Alper formar en unik vårsyn för Matsumoto.`,
    "中町通り(松本市)": `Nakamachi-gatan är ett historiskt distrikt med «kura» lagerbyggnader i den gamla slottsstaden Matsumoto. Vita putsade väggar med svart «namako» kakelmönster bevarar slutet av Edo- och Meiji-stämningen. Kaféer, verkstäder och gallerier upptar de renoverade kura — ett levande, turistdistrikt perfekt för promenad och fotografering.`,
    "高島公園(諏訪市)": `Takashima-parken i Suwa står på ruinerna av Takashima-slottet, Suwa-klanens säte. En gång kallat «Suwas flytande slott», dess återuppbyggda torn och cirka 100 körsbärsträd runt vallgraven blommar i mitten av april. Tornet speglat i vallgraven med körsbärsblommor är en ikonisk vårsyn för Suwa.`,
    "諏訪湖": `Suwasjön i centrala Nagano på 759 m är prefekturens största sjö. Berömd för «Omiwatari» — isåsar som reser sig från ytan mitt i vintern — och sommarfyrverkerier. Inspiration till sjön i filmen «Your Name».`,
    "立石公園": `Tateishi-parken på 934 m över Suwasjön erbjuder en panorama över sjön med Yatsugatake och till och med berget Fuji i fjärran. På natten glimmar Suwa som ett smyckeskrin. Berömd som pilgrimsplats för filmen «Your Name», fotogen vid alla tider.`,
  },
};

const LANGS = Object.keys(T);
let totalAdded = 0;
for (const lang of LANGS) {
  const path = resolve(EXTRAS_DIR, `${lang}.js`);
  let content = readFileSync(path, "utf-8");
  const block = Object.entries(T[lang])
    .map(([k, v]) => `    "${k}": \`${v}\`,`)
    .join("\n");
  const marker = "  },\n};";
  const lastIdx = content.lastIndexOf(marker);
  if (lastIdx === -1) { console.error(`✗ ${lang}: marker not found`); continue; }
  content = content.slice(0, lastIdx) + `${block}\n  },\n};` + content.slice(lastIdx + marker.length);
  writeFileSync(path, content, "utf-8");
  totalAdded += Object.keys(T[lang]).length;
  console.log(`✓ ${lang}.js: +${Object.keys(T[lang]).length} entries`);
}
console.log(`\n=== ${LANGS.length}言語 × 8 loc = ${totalAdded}エントリ追加 ===`);
