/**
 * ブログ記事 20本のメタデータ.
 * - slug, date, locs (関連LOC_I18Nキー)
 * - title: 20言語 (ja/en は完備、他は en フォールバック前提で順次追加)
 * - excerpt: 20言語 (簡潔)
 * - bodyJa / bodyEn: 本文 (HTML/プレーン文字列、改行で段落)
 * - 他言語 body は en フォールバック
 */

export const POSTS = [
  {
    slug: "mt-fuji-arakurayama",
    date: "2026-04-12",
    locs: ["新倉山浅間公園", "河口湖"],
    hero: "wcrs6gq9eutte8fwrzpp",
    title: { ja: "新倉山浅間公園で撮る、富士山と五重塔と桜の三段構図", en: "Mt. Fuji + Pagoda + Cherry Blossoms: Shooting the Iconic Three-Tier Composition at Arakurayama Sengen Park" },
    excerpt: { ja: "「日本」と聞いて誰もが思い浮かべる、あの一枚を撮るための完全ガイド。アクセスから時間帯、構図、機材まで。", en: "The complete guide to shooting Japan's most iconic cherry-blossom-and-Fuji frame: access, timing, composition, and gear." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "takato-castle-cherry",
    date: "2026-04-13",
    locs: ["高遠城址公園"],
    hero: "jfvqos5wbosqddnnrgxo",
    title: { ja: "「天下第一の桜」高遠城址公園 — 1500本のタカトオコヒガンザクラ撮影ガイド", en: "«No.1 Cherry Under Heaven»: Photographing 1,500 Takato Kohigan Cherry Trees at Takato Castle Park" },
    excerpt: { ja: "薄紅色の固有種で日本三大桜に数えられる高遠の桜。混雑回避、ライトアップ、北アルプス背景の構図まで。", en: "A pale-pink endemic species and one of Japan's three great sakura sites. Crowd avoidance, illumination, and composition with the Central Alps." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "lake-kawaguchi-fuji",
    date: "2026-04-12",
    locs: ["河口湖"],
    hero: "bsesdqubicdiilhcynyh",
    title: { ja: "河口湖の「逆さ富士」を撮る — 風と光と季節の方程式", en: "Shooting the «Inverted Fuji» Reflection at Lake Kawaguchi: The Equation of Wind, Light, and Season" },
    excerpt: { ja: "湖面に映る富士山。鏡のような水面を捉える条件と、春の桜・冬の冠雪の組合せベスト。", en: "Mt. Fuji mirrored in the lake. The conditions for glassy water, plus the best season pairings — spring blossoms and winter snow." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "lake-suwa-omiwatari",
    date: "2026-04-13",
    locs: ["諏訪湖", "立石公園"],
    hero: "h4oyzzdqaydnwqtu6ni0",
    title: { ja: "諏訪湖の御神渡り — 神が渡る氷の道を撮る冬の朝", en: "Lake Suwa's Omiwatari: Photographing the Path of the Gods on Winter Mornings" },
    excerpt: { ja: "湖面の氷がせり上がる神秘的な現象。御神渡りが現れる条件と、立石公園からの絶景撮影点。", en: "A mystical phenomenon where lake ice rises into ridges. Conditions for Omiwatari and the best vantage from Tateishi Park above." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "matsumoto-castle-seasons",
    date: "2026-04-12",
    locs: ["松本城"],
    hero: "u5izvsliyoqm6rr0xnzh",
    title: { ja: "国宝・松本城 四季の撮影 — 烏城と北アルプスを一枚に", en: "National Treasure Matsumoto Castle Through the Seasons: Framing the Crow Castle with the Northern Alps" },
    excerpt: { ja: "現存12天守の漆黒の名城。桜・新緑・紅葉・雪化粧、それぞれの構図と時間帯を解説。", en: "One of Japan's 12 surviving original keeps. Compositions and timing for sakura, fresh greens, autumn foliage, and snow." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "komatsunagi-cherry-stars",
    date: "2026-04-13",
    locs: ["駒つなぎの桜"],
    hero: "bykxlizpdzufezqttzca",
    title: { ja: "駒つなぎの桜と星空 — 阿智村に立つ樹齢400年の一本桜", en: "The Komatsunagi Cherry Tree Under the Stars: A 400-Year-Old Solitary Sakura in Achi Village" },
    excerpt: { ja: "源義経が馬を繋いだという伝説の一本桜。棚田の水鏡と銀河を一枚に収める撮影テクニック。", en: "A legendary cherry tree said to have tethered Yoshitsune's horse. Techniques for capturing the rice-paddy reflection with the Milky Way." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "achi-stargazing",
    date: "2026-04-13",
    locs: ["長野県天空の楽園"],
    hero: "bxt5gtw3rnuqxrx46ppl",
    title: { ja: "日本一の星空 阿智村 — 標高1400mの「天空の楽園」で星を撮る", en: "Japan's No.1 Starry Sky in Achi Village: Stargazing Photography at 1,400 m «Tenku no Rakuen»" },
    excerpt: { ja: "環境省が日本一と認定した星空。新月期と冬の透明度、ナイトツアー予約のコツ。", en: "Officially Japan's clearest night sky. New-moon timing, winter transparency, and night-tour booking tips." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "sapporo-snow-festival",
    date: "2026-02-08",
    locs: ["さっぽろ雪まつり"],
    hero: "usvnljzznwmqu93sftg1",
    title: { ja: "さっぽろ雪まつり完全撮影ガイド — 200万人が訪れる白銀の祭典", en: "The Complete Photographer's Guide to the Sapporo Snow Festival: Two Million Visitors and a Silver Spectacle" },
    excerpt: { ja: "巨大雪像、市民像、氷彫刻、夜のライトアップ。三脚・低ISO・防寒の実践テクニック。", en: "Massive sculptures, citizen-built works, ice carvings, and night illumination. Practical tripod, low-ISO, and cold-weather techniques." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "shiretoko-drift-ice",
    date: "2025-02-15",
    locs: ["知床"],
    hero: "sgqomcwsuq18xc1oyr3g",
    title: { ja: "知床の流氷を撮る — 1月〜3月、世界自然遺産の冬", en: "Shooting Drift Ice at Shiretoko: January–March in a UNESCO Natural Heritage Winter" },
    excerpt: { ja: "オホーツクから流れ着く氷原。ウトロ発のクルーズと陸上撮影、それぞれのベストポジション。", en: "Ice fields drifting from the Sea of Okhotsk. Best vantage from cruise boats out of Utoro, and from land." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "furano-lavender",
    date: "2025-07-20",
    locs: ["富良野"],
    hero: "hvnlsmmmikzqkmooht8u",
    title: { ja: "富良野ラベンダー畑の絶景 — 7月中旬の紫の絨毯を狙う", en: "Furano's Lavender Fields: Targeting the Purple Carpet of Mid-July" },
    excerpt: { ja: "ファーム富田を中心とした花畑。早朝の光線、構図、混雑回避のための時間帯。", en: "Flower fields centered on Farm Tomita. Morning light, composition, and the timing that avoids crowds." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "shirakawa-go-snow",
    date: "2024-02-10",
    locs: ["白川郷"],
    hero: "qvsgt1aw6o4iwewvhmdc",
    title: { ja: "白川郷の雪景色 — 世界遺産・合掌造りに降り積もる冬", en: "Shirakawa-go in Snow: Winter on a UNESCO Gassho-zukuri Village" },
    excerpt: { ja: "茅葺き屋根に積もる雪、ライトアップの幻想、展望台からの俯瞰。冬撮影の入門。", en: "Snow piled on thatched roofs, the magic of evening illumination, and the elevated view from the observation deck." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "kyoto-autumn-temples",
    date: "2025-11-20",
    locs: ["東福寺", "清水寺", "金閣寺"],
    hero: "",
    title: { ja: "京都の紅葉と寺社 — 11月、千年の都を歩く", en: "Kyoto's Autumn Foliage and Temples: November in the Thousand-Year Capital" },
    excerpt: { ja: "東福寺の通天橋、清水寺、金閣寺。混雑を避けて朝イチで巡るルートと時間配分。", en: "Tofuku-ji's Tsutenkyo, Kiyomizu-dera, and Kinkaku-ji. An early-morning route plan that beats the crowds." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "kiyomizu-illumination",
    date: "2025-11-25",
    locs: ["清水寺"],
    hero: "",
    title: { ja: "清水寺 紅葉ライトアップ — 京都の夜、舞台に灯る秋", en: "Kiyomizu-dera Autumn Illumination: Kyoto Nights, the Lit Stage of Fall" },
    excerpt: { ja: "13mの懸造り舞台と紅葉を青空の時間帯に撮る。三脚不可の制約下での実践設定。", en: "Shooting the 13 m wooden stage with autumn leaves at blue hour. Practical settings under the no-tripod restriction." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "byodoin-phoenix-hall",
    date: "2024-12-05",
    locs: ["平等院鳳凰堂"],
    hero: "",
    title: { ja: "平等院鳳凰堂 — 10円玉に刻まれた1000年の対称美", en: "Byodo-in Phoenix Hall: A Thousand Years of Symmetry Engraved on the 10-Yen Coin" },
    excerpt: { ja: "阿字池に映る鳳凰堂。風のない朝の鏡面と、紅葉・雪との季節構図。", en: "The hall reflected in Aji Pond. Mirror-still mornings, plus seasonal pairings with autumn leaves and snow." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "ise-jingu-pilgrimage",
    date: "2025-09-15",
    locs: ["伊勢神宮", "おはらい町・おかげ横丁"],
    hero: "",
    title: { ja: "伊勢神宮 参拝と撮影 — 神域の杜を歩く", en: "Ise Jingu Pilgrimage and Photography: Walking the Sacred Grove" },
    excerpt: { ja: "外宮・内宮の参拝順路、撮影マナー、おかげ横丁の食と街並み。日本の心を巡る一日。", en: "Outer/Inner shrine route, photography etiquette, and the food and streets of Okage Yokocho. A day at Japan's spiritual heart." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "miyakojima-blue",
    date: "2025-07-08",
    locs: ["宮古島"],
    hero: "wt6ow9shewohl0dm0lnj",
    title: { ja: "宮古ブルーを撮る — 与那覇前浜と伊良部大橋、3540mの絶景", en: "Capturing Miyako Blue: Yonaha Maehama and the 3,540 m Irabu Bridge" },
    excerpt: { ja: "日本一の透明度を誇る海。PLフィルター、時間帯、ドローンと地上の使い分け。", en: "Japan's clearest waters. Polarizing filters, timing, and the trade-offs between aerial and ground perspectives." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "chichibugahama-uyuni",
    date: "2025-08-20",
    locs: ["父母ヶ浜"],
    hero: "",
    title: { ja: "父母ヶ浜「日本のウユニ塩湖」を撮る — 香川の干潟夕景", en: "Chichibugahama, the «Uyuni of Japan»: Shooting Kagawa's Tidal Sunset Reflections" },
    excerpt: { ja: "干潮+夕暮れ+無風の三条件。鏡のような水面に人物シルエットを写す撮影設計。", en: "Low tide + twilight + windless: three conditions converging. Designing silhouette shots on the mirror tidepool." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "himeji-castle-spring",
    date: "2024-04-05",
    locs: ["姫路城"],
    hero: "",
    title: { ja: "姫路城 春 — 世界遺産・白鷺城と1000本の桜", en: "Himeji Castle in Spring: UNESCO White Heron Castle and 1,000 Cherry Trees" },
    excerpt: { ja: "白漆喰の天守と桜のコントラスト。三の丸広場・西の丸からの王道構図と裏ビュー。", en: "White-plaster keep against pink blossoms. Classic compositions from Sannomaru and Nishinomaru, plus lesser-known angles." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "otaru-canal-night",
    date: "2025-12-15",
    locs: ["小樽"],
    hero: "yh7e0rhvhnzzxj5esa5f",
    title: { ja: "小樽運河の夜 — ガス灯が灯るノスタルジー", en: "Otaru Canal at Night: A Nostalgia Lit by Gas Lamps" },
    excerpt: { ja: "石造倉庫とガス灯の温かい光。雪の運河、青の時間帯、長秒露光のテクニック。", en: "Stone warehouses and warm gaslight. The snowy canal, blue hour, and long-exposure techniques." },
    bodyJa: "",
    bodyEn: "",
  },
  {
    slug: "noboribetsu-jigokudani",
    date: "2025-10-15",
    locs: ["登別"],
    hero: "",
    title: { ja: "登別 地獄谷 — 火山と湯けむりの撮影地", en: "Noboribetsu Jigokudani: A Volcanic, Steam-Veiled Photo Spot" },
    excerpt: { ja: "硫黄の蒸気と紅葉、エメラルドの大湯沼。北海道随一の温泉郷で湯けむりを撮る。", en: "Sulfur steam, autumn foliage, and the emerald Oyunuma. Shooting steam in Hokkaido's premier onsen valley." },
    bodyJa: "",
    bodyEn: "",
  },
];

export const POST_SLUGS = POSTS.map((p) => p.slug);
export const getPost = (slug) => POSTS.find((p) => p.slug === slug);
export const getPostTitle = (post, lang) => post.title[lang] || post.title.en || post.slug;
export const getPostExcerpt = (post, lang) => post.excerpt[lang] || post.excerpt.en || "";
export const getPostBody = (post, lang) => {
  if (lang === "ja" && post.bodyJa) return post.bodyJa;
  return post.bodyEn || "";
};
