// 自動生成: node scripts/generate-collections-meta.mjs (手で編集しない)
// ④ コレクションの軽い部分だけ。画面 (client component) はこちらを読む。
// 紹介文 (desc) と撮影のコツ (guide) は入れない — サーバー側でしか使わず、
// 全ページの初期JSに約93KB 載っていたため。元データは app/collections.js。
// ずれは scripts/check-data.mjs が毎ビルド確かめる。
export const COLLECTION_SLUGS = ["cherry-blossoms","autumn-foliage","snow","castles","temples-shrines","hot-springs","coastal","night-views","waterfalls","lakes","birds","animals"];

export const COLLECTION_META = {
 "cherry-blossoms": {
  "locs": [
   "新倉山浅間公園",
   "高遠城址公園",
   "駒つなぎの桜",
   "城山公園(松本市)",
   "高島公園(諏訪市)",
   "弘法山古墳",
   "安養寺"
  ],
  "name": {
   "ja": "桜",
   "en": "Cherry Blossoms",
   "zh": "樱花",
   "zh-tw": "櫻花",
   "ko": "벚꽃",
   "es": "Cerezos en flor",
   "fr": "Cerisiers en fleurs",
   "de": "Kirschblüten",
   "pt": "Cerejeiras em flor",
   "it": "Ciliegi in fiore",
   "ru": "Цветение сакуры",
   "ar": "أزهار الكرز",
   "hi": "चेरी के फूल",
   "th": "ดอกซากุระ",
   "vi": "Hoa anh đào",
   "id": "Bunga Sakura",
   "tr": "Kiraz Çiçekleri",
   "nl": "Kersenbloesem",
   "pl": "Kwitnące wiśnie",
   "sv": "Körsbärsblommor",
   "fa": "شکوفه‌های گیلاس",
   "he": "פריחת הדובדבן",
   "bn": "চেরি ফুল",
   "tl": "Bulaklak ng Cherry",
   "uk": "Цвітіння сакури"
  }
 },
 "autumn-foliage": {
  "locs": [
   "東福寺",
   "清水寺",
   "金閣寺"
  ],
  "name": {
   "ja": "紅葉",
   "en": "Autumn Foliage",
   "zh": "红叶",
   "zh-tw": "紅葉",
   "ko": "단풍",
   "es": "Follaje de otoño",
   "fr": "Feuillage d'automne",
   "de": "Herbstlaub",
   "pt": "Folhagem de outono",
   "it": "Foliage autunnale",
   "ru": "Осенняя листва",
   "ar": "أوراق الخريف",
   "hi": "शरद पर्णसमूह",
   "th": "ใบไม้เปลี่ยนสี",
   "vi": "Lá thu",
   "id": "Dedaunan Musim Gugur",
   "tr": "Sonbahar Yaprakları",
   "nl": "Herfstkleuren",
   "pl": "Jesienne liście",
   "sv": "Höstlöv",
   "fa": "برگ‌های پاییزی",
   "he": "שלכת הסתיו",
   "bn": "শরতের পাতা",
   "tl": "Dahon ng Taglagas",
   "uk": "Осіннє листя"
  }
 },
 "snow": {
  "locs": [
   "さっぽろ雪まつり",
   "白川郷",
   "知床",
   "摩周湖",
   "洞爺湖",
   "登別",
   "美幌峠",
   "小樽"
  ],
  "name": {
   "ja": "雪景色",
   "en": "Snow",
   "zh": "雪景",
   "zh-tw": "雪景",
   "ko": "설경",
   "es": "Nieve",
   "fr": "Neige",
   "de": "Schnee",
   "pt": "Neve",
   "it": "Neve",
   "ru": "Снежные пейзажи",
   "ar": "الثلوج",
   "hi": "बर्फ़",
   "th": "หิมะ",
   "vi": "Tuyết",
   "id": "Salju",
   "tr": "Kar Manzaraları",
   "nl": "Sneeuwlandschappen",
   "pl": "Śnieg",
   "sv": "Snölandskap",
   "fa": "مناظر برفی",
   "he": "נופי שלג",
   "bn": "তুষার দৃশ্য",
   "tl": "Tanawing Niyebe",
   "uk": "Засніжені краєвиди"
  }
 },
 "castles": {
  "locs": [
   "姫路城",
   "松本城",
   "松山城",
   "高知城",
   "高遠城址公園",
   "高島公園(諏訪市)",
   "金沢"
  ],
  "name": {
   "ja": "城",
   "en": "Castles",
   "zh": "城",
   "zh-tw": "城",
   "ko": "성",
   "es": "Castillos",
   "fr": "Châteaux",
   "de": "Burgen",
   "pt": "Castelos",
   "it": "Castelli",
   "ru": "Замки",
   "ar": "القلاع",
   "hi": "किले",
   "th": "ปราสาท",
   "vi": "Lâu đài",
   "id": "Kastil",
   "tr": "Kaleler",
   "nl": "Kastelen",
   "pl": "Zamki",
   "sv": "Slott",
   "fa": "قلعه‌ها",
   "he": "טירות",
   "bn": "দুর্গ",
   "tl": "Mga Kastilyo",
   "uk": "Замки"
  }
 },
 "temples-shrines": {
  "locs": [
   "清水寺",
   "清水寺周辺",
   "金閣寺",
   "平等院鳳凰堂",
   "東福寺",
   "伊勢神宮",
   "おはらい町・おかげ横丁",
   "夫婦岩",
   "法隆寺",
   "法隆寺 夢殿",
   "安養寺"
  ],
  "name": {
   "ja": "寺と神社",
   "en": "Temples & Shrines",
   "zh": "寺院与神社",
   "zh-tw": "寺院與神社",
   "ko": "사찰과 신사",
   "es": "Templos y santuarios",
   "fr": "Temples et sanctuaires",
   "de": "Tempel & Schreine",
   "pt": "Templos e santuários",
   "it": "Templi e santuari",
   "ru": "Храмы и святилища",
   "ar": "المعابد والأضرحة",
   "hi": "मंदिर और तीर्थ",
   "th": "วัดและศาลเจ้า",
   "vi": "Đền chùa",
   "id": "Kuil dan Wihara",
   "tr": "Tapınaklar ve Türbeler",
   "nl": "Tempels en heiligdommen",
   "pl": "Świątynie i sanktuaria",
   "sv": "Tempel och helgedomar",
   "fa": "معابد و زیارتگاه‌ها",
   "he": "מקדשים ומקדשי שינטו",
   "bn": "মন্দির ও উপাসনালয়",
   "tl": "Mga Templo at Dambana",
   "uk": "Храми та святині"
  }
 },
 "hot-springs": {
  "locs": [
   "道後温泉",
   "別府",
   "湯布院",
   "登別",
   "洞爺湖"
  ],
  "name": {
   "ja": "温泉",
   "en": "Hot Springs",
   "zh": "温泉",
   "zh-tw": "溫泉",
   "ko": "온천",
   "es": "Aguas termales",
   "fr": "Sources thermales",
   "de": "Heiße Quellen",
   "pt": "Águas termais",
   "it": "Terme",
   "ru": "Горячие источники",
   "ar": "الينابيع الساخنة",
   "hi": "गर्म झरने",
   "th": "ออนเซ็น",
   "vi": "Suối nước nóng",
   "id": "Pemandian Air Panas",
   "tr": "Kaplıcalar",
   "nl": "Warmwaterbronnen",
   "pl": "Gorące źródła",
   "sv": "Varma källor",
   "fa": "چشمه‌های آب گرم",
   "he": "מעיינות חמים",
   "bn": "উষ্ণ প্রস্রবণ",
   "tl": "Mainit na Bukal",
   "uk": "Гарячі джерела"
  }
 },
 "coastal": {
  "locs": [
   "父母ヶ浜",
   "桂浜",
   "宮古島",
   "沖縄",
   "夫婦岩",
   "鳴門海峡",
   "大鳴門橋",
   "来島海峡大橋",
   "亀老山展望台",
   "室蘭"
  ],
  "name": {
   "ja": "海岸",
   "en": "Coastal",
   "zh": "海岸",
   "zh-tw": "海岸",
   "ko": "해안",
   "es": "Costa",
   "fr": "Côtes",
   "de": "Küsten",
   "pt": "Costa",
   "it": "Coste",
   "ru": "Побережья",
   "ar": "السواحل",
   "hi": "तट",
   "th": "ชายฝั่ง",
   "vi": "Bờ biển",
   "id": "Pesisir",
   "tr": "Sahiller",
   "nl": "Kustlandschappen",
   "pl": "Wybrzeża",
   "sv": "Kuster",
   "fa": "سواحل",
   "he": "חופים",
   "bn": "সমুদ্রতট",
   "tl": "Baybayin",
   "uk": "Узбережжя"
  }
 },
 "night-views": {
  "locs": [
   "横浜",
   "立石公園",
   "中町通り(松本市)",
   "東京",
   "品川",
   "札幌",
   "福岡"
  ],
  "name": {
   "ja": "夜景",
   "en": "Night Views",
   "zh": "夜景",
   "zh-tw": "夜景",
   "ko": "야경",
   "es": "Vistas nocturnas",
   "fr": "Vues nocturnes",
   "de": "Nachtansichten",
   "pt": "Vistas noturnas",
   "it": "Viste notturne",
   "ru": "Ночные виды",
   "ar": "المناظر الليلية",
   "hi": "रात्रि दृश्य",
   "th": "วิวกลางคืน",
   "vi": "Quang cảnh đêm",
   "id": "Pemandangan Malam",
   "tr": "Gece Manzaraları",
   "nl": "Nachtaanzichten",
   "pl": "Widoki nocne",
   "sv": "Nattvyer",
   "fa": "مناظر شبانه",
   "he": "נופי לילה",
   "bn": "রাতের দৃশ্য",
   "tl": "Tanawin sa Gabi",
   "uk": "Нічні краєвиди"
  }
 },
 "waterfalls": {
  "locs": [
   "三段滝公園",
   "にこ淵"
  ],
  "name": {
   "ja": "滝",
   "en": "Waterfalls",
   "zh": "瀑布",
   "zh-tw": "瀑布",
   "ko": "폭포",
   "es": "Cascadas",
   "fr": "Cascades",
   "de": "Wasserfälle",
   "pt": "Cachoeiras",
   "it": "Cascate",
   "ru": "Водопады",
   "ar": "الشلالات",
   "hi": "जलप्रपात",
   "th": "น้ำตก",
   "vi": "Thác nước",
   "id": "Air Terjun",
   "tr": "Şelaleler",
   "nl": "Watervallen",
   "pl": "Wodospady",
   "sv": "Vattenfall",
   "fa": "آبشارها",
   "he": "מפלים",
   "bn": "জলপ্রপাত",
   "tl": "Mga Talon",
   "uk": "Водоспади"
  }
 },
 "lakes": {
  "locs": [
   "摩周湖",
   "洞爺湖",
   "河口湖",
   "諏訪湖"
  ],
  "name": {
   "ja": "湖",
   "en": "Lakes",
   "zh": "湖泊",
   "zh-tw": "湖泊",
   "ko": "호수",
   "es": "Lagos",
   "fr": "Lacs",
   "de": "Seen",
   "pt": "Lagos",
   "it": "Laghi",
   "ru": "Озёра",
   "ar": "البحيرات",
   "hi": "झीलें",
   "th": "ทะเลสาบ",
   "vi": "Hồ",
   "id": "Danau",
   "tr": "Göller",
   "nl": "Meren",
   "pl": "Jeziora",
   "sv": "Sjöar",
   "fa": "دریاچه‌ها",
   "he": "אגמים",
   "bn": "হ্রদ",
   "tl": "Mga Lawa",
   "uk": "Озера"
  }
 },
 "birds": {
  "locs": [],
  "name": {
   "ja": "鳥",
   "en": "Birds",
   "zh": "鸟类",
   "zh-tw": "鳥類",
   "ko": "새",
   "es": "Aves",
   "fr": "Oiseaux",
   "de": "Vögel",
   "pt": "Aves",
   "it": "Uccelli",
   "ru": "Птицы",
   "ar": "الطيور",
   "hi": "पक्षी",
   "th": "นก",
   "vi": "Chim",
   "id": "Burung",
   "tr": "Kuşlar",
   "nl": "Vogels",
   "pl": "Ptaki",
   "sv": "Fåglar",
   "fa": "پرندگان",
   "he": "ציפורים",
   "bn": "পাখি",
   "tl": "Mga Ibon",
   "uk": "Птахи"
  }
 },
 "animals": {
  "locs": [],
  "name": {
   "ja": "動物",
   "en": "Animals",
   "zh": "动物",
   "zh-tw": "動物",
   "ko": "동물",
   "es": "Animales",
   "fr": "Animaux",
   "de": "Tiere",
   "pt": "Animais",
   "it": "Animali",
   "ru": "Животные",
   "ar": "الحيوانات",
   "hi": "जानवर",
   "th": "สัตว์",
   "vi": "Động vật",
   "id": "Hewan",
   "tr": "Hayvanlar",
   "nl": "Dieren",
   "pl": "Zwierzęta",
   "sv": "Djur",
   "fa": "حیوانات",
   "he": "חיות",
   "bn": "প্রাণী",
   "tl": "Mga Hayop",
   "uk": "Тварини"
  }
 }
};

/** コレクション名。その言語に無ければ英語、それも無ければ slug */
export function getCollectionName(slug, lang) {
  const n = COLLECTION_META[slug]?.name;
  return n ? (n[lang] || n.en || slug) : slug;
}

/** そのコレクションに割り当てた撮影地 (タグが無い写真の判定に使う) */
export const getCollectionLocs = (slug) => COLLECTION_META[slug]?.locs || [];
