/**
 * 撮影地 → 関連イベントマップ (schema.org Event 用)
 * 各 loc に対して 0個以上のイベント (祭り、ライトアップ、シーズン)。
 * 名称・概要は ja/en (他言語は en フォールバック)。
 * 開催日は2026年シーズン (毎年シーズン繰り上げ更新を想定)。
 */
export const EVENTS = {
  "さっぽろ雪まつり": [{
    nameJa: "さっぽろ雪まつり 2026",
    nameEn: "Sapporo Snow Festival 2026",
    descJa: "札幌大通公園・すすきの・つどーむの3会場で開催される日本最大級の雪と氷の祭典。15mを超える巨大雪像と夜のライトアップが見どころ。",
    descEn: "Japan's largest snow-and-ice festival across three Sapporo venues — Odori Park, Susukino, and Tsudome. Massive 15m+ sculptures and night illumination.",
    startDate: "2026-02-04",
    endDate: "2026-02-11",
    placeName: "大通公園・すすきの・つどーむ (Sapporo, Hokkaido)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "高遠城址公園": [{
    nameJa: "高遠さくら祭り 2026",
    nameEn: "Takato Sakura Festival 2026",
    descJa: "「天下第一の桜」と称される高遠城址公園で約1500本のタカトオコヒガンザクラが咲く春の祭典。夜のライトアップも開催。",
    descEn: "Spring festival at Takato Castle Park with ~1,500 Takato Kohigan cherry trees, dubbed «No.1 cherry under heaven.» Includes evening illumination.",
    startDate: "2026-04-01",
    endDate: "2026-04-15",
    placeName: "高遠城址公園 (Ina, Nagano)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "清水寺": [{
    nameJa: "清水寺 秋の夜の特別拝観 2026",
    nameEn: "Kiyomizu-dera Autumn Night Special Viewing 2026",
    descJa: "世界遺産・清水寺の紅葉ライトアップ。13mの清水の舞台と境内のモミジが青白いライトと暖色で照らされる。",
    descEn: "Autumn night illumination at UNESCO Kiyomizu-dera — the 13 m wooden stage and maple foliage lit in cool blue and warm tones.",
    startDate: "2026-11-18",
    endDate: "2026-12-01",
    placeName: "清水寺 (Kyoto)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "東福寺": [{
    nameJa: "東福寺 紅葉シーズン 2026",
    nameEn: "Tofuku-ji Autumn Foliage Season 2026",
    descJa: "通天橋から眺める2,000本のモミジが朱色に染まる京都屈指の紅葉名所。",
    descEn: "Some 2,000 maples view from the Tsutenkyo bridge — one of Kyoto's premier autumn foliage destinations.",
    startDate: "2026-11-15",
    endDate: "2026-12-05",
    placeName: "東福寺 (Kyoto)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "富良野": [{
    nameJa: "ファーム富田 ラベンダー満開期 2026",
    nameEn: "Farm Tomita Lavender Peak Bloom 2026",
    descJa: "富良野ファーム富田を中心とするラベンダー畑が紫の絨毯に。7月中旬がピーク。",
    descEn: "Lavender fields centered on Farm Tomita reach a purple-carpet peak. Mid-July is the climax.",
    startDate: "2026-07-10",
    endDate: "2026-07-31",
    placeName: "ファーム富田 (Furano, Hokkaido)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "白川郷": [{
    nameJa: "白川郷ライトアップ 2026",
    nameEn: "Shirakawa-go Light-up 2026",
    descJa: "世界遺産・白川郷の合掌造り集落が雪とライトに照らされる冬限定の特別開催。",
    descEn: "UNESCO Shirakawa-go's gassho-zukuri farmhouses illuminated against snow — winter-only special event.",
    startDate: "2026-01-18",
    endDate: "2026-02-22",
    placeName: "白川郷 荻町 (Shirakawa, Gifu)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "長野県天空の楽園": [{
    nameJa: "天空の楽園 ナイトツアー 2026",
    nameEn: "Tenku no Rakuen Night Tour 2026",
    descJa: "環境省「日本一の星空」認定の阿智村で行われる、ゴンドラで標高1400mに登る星空鑑賞ツアー。",
    descEn: "Nightly stargazing tour rising by gondola to 1,400 m in Achi Village — certified «No.1 starry sky in Japan» by the Ministry of the Environment.",
    startDate: "2026-04-25",
    endDate: "2026-11-03",
    placeName: "富士見台高原 (Achi, Nagano)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "新倉山浅間公園": [{
    nameJa: "新倉山浅間公園 桜まつり 2026",
    nameEn: "Arakurayama Sengen Park Sakura Festival 2026",
    descJa: "富士山と五重塔と桜の三段構図が世界的に有名なフォトスポット。4月中旬の桜満開期に夜間ライトアップも実施。",
    descEn: "Site of the world-famous «Mt. Fuji + pagoda + cherry blossoms» three-tier composition. Night illumination during peak bloom in mid-April.",
    startDate: "2026-04-08",
    endDate: "2026-04-20",
    placeName: "新倉山浅間公園 (Fujiyoshida, Yamanashi)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "諏訪湖": [{
    nameJa: "諏訪湖祭湖上花火大会 2026",
    nameEn: "Lake Suwa Fireworks Festival 2026",
    descJa: "毎年8月15日開催、約4万発の花火が諏訪湖の湖面に映る日本屈指の花火大会。",
    descEn: "Held annually on August 15. Some 40,000 fireworks reflected on Lake Suwa — one of Japan's most spectacular fireworks displays.",
    startDate: "2026-08-15",
    endDate: "2026-08-15",
    placeName: "諏訪湖 (Suwa, Nagano)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  },
  {
    nameJa: "御神渡り (おみわたり) 寒期 2026",
    nameEn: "Lake Suwa Omiwatari Sacred Ice Ridges Season 2026",
    descJa: "厳冬期、湖面が結氷と融解を繰り返してできる氷の隆起「御神渡り」。神事として代々記録され、できた年は数年に一度の希少現象。",
    descEn: "In deep winter, freeze-and-thaw cycles form sacred ridges called «omiwatari» across Lake Suwa's frozen surface. Recorded as a Shinto event for centuries; the ridges form only in particularly cold years.",
    startDate: "2026-01-15",
    endDate: "2026-02-20",
    placeName: "諏訪湖 (Suwa, Nagano)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "知床": [{
    nameJa: "知床 流氷シーズン 2026",
    nameEn: "Shiretoko Drift Ice Season 2026",
    descJa: "オホーツク海から流れ着く流氷が世界自然遺産・知床半島の沿岸を覆う冬限定の景観。流氷ウォークやクルーズで間近に体験できる。",
    descEn: "Drift ice arrives from the Sea of Okhotsk and covers the UNESCO-listed Shiretoko Peninsula's coast — a winter-only spectacle viewable on guided ice walks and boat tours.",
    startDate: "2026-01-20",
    endDate: "2026-03-15",
    placeName: "知床半島・ウトロ (Shari, Hokkaido)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "北竜町": [{
    nameJa: "北竜町ひまわりまつり 2026",
    nameEn: "Hokuryū Sunflower Festival 2026",
    descJa: "23ヘクタールの大地に約200万本のひまわりが咲く日本最大級のひまわり畑。7月下旬〜8月中旬が見頃。",
    descEn: "About 2 million sunflowers spread across 23 hectares — one of Japan's largest sunflower fields. Late July to mid-August is peak.",
    startDate: "2026-07-20",
    endDate: "2026-08-20",
    placeName: "ひまわりの里 (Hokuryū, Hokkaido)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "夫婦岩": [{
    nameJa: "夫婦岩 夏至前後の日の出 2026",
    nameEn: "Meoto-iwa Summer Solstice Sunrise 2026",
    descJa: "二見興玉神社の沖合に立つ夫婦岩の間から朝日が昇る限られた時期。夏至前後(5〜7月)が最も真ん中に昇る。",
    descEn: "The sun rises between the «wedded rocks» off Futami Okitama Shrine — a brief window peaking around the summer solstice (May–July).",
    startDate: "2026-05-10",
    endDate: "2026-07-20",
    placeName: "夫婦岩・二見興玉神社 (Ise, Mie)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "鳴門海峡": [{
    nameJa: "鳴門の渦潮 大潮期 2026 春",
    nameEn: "Naruto Whirlpools Spring Tide Peak 2026",
    descJa: "世界三大潮流の一つ、最大直径20mに達する渦潮。春の大潮(3〜4月)が最も大きく、観潮船とうずしお橋から間近に見られる。",
    descEn: "One of the world's three great tidal currents — whirlpools up to 20 m across. Spring tides (March–April) produce the largest swirls; viewable from Uzunomichi promenade or sightseeing boats.",
    startDate: "2026-03-15",
    endDate: "2026-04-30",
    placeName: "鳴門海峡 (Naruto, Tokushima)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "父母ヶ浜": [{
    nameJa: "父母ヶ浜 ミラー夕景シーズン 2026",
    nameEn: "Chichibugahama Mirror Sunset Season 2026",
    descJa: "干潮と夕日が重なる日に「日本のウユニ塩湖」と称される鏡張りの夕景が出現。三豊市観光公式サイトが月別のベスト日カレンダーを公開。",
    descEn: "On days when low tide and sunset align, the beach becomes the «Uyuni Salt Flats of Japan» with perfect mirror reflections. Mitoyo City publishes a monthly best-day calendar.",
    startDate: "2026-03-01",
    endDate: "2026-10-31",
    placeName: "父母ヶ浜 (Mitoyo, Kagawa)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "別府": [{
    nameJa: "別府八湯温泉まつり 2026",
    nameEn: "Beppu Hatto Onsen Festival 2026",
    descJa: "年に一度、別府の8つの温泉地で同時開催される温泉感謝祭。期間中は一部の市営温泉が無料開放。",
    descEn: "Annual festival across Beppu's eight hot-spring districts. During the festival, some city-run onsen are free to enter.",
    startDate: "2026-04-01",
    endDate: "2026-04-03",
    placeName: "別府市 各温泉地 (Beppu, Oita)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
};

export const getEvents = (locJp) => EVENTS[locJp] || [];
