/**
 * 撮影地 → 関連イベントマップ (schema.org Event 用)
 * 各 loc に対して 0個以上のイベント (祭り、ライトアップ、シーズン)。
 * 名称・概要は ja/en (他言語は en フォールバック)。
 * 開催日は2026年シーズン (毎年シーズン繰り上げ更新を想定)。
 */
export const EVENTS = {
  "さっぽろ雪まつり": [{
    nameJa: "さっぽろ雪まつり 2026",
    nameEn: "Sapporo Snow Festival 2026",
    descJa: "札幌大通公園・すすきの・つどーむの3会場で開催される日本最大級の雪と氷の祭典。15mを超える巨大雪像と夜のライトアップが見どころ。",
    descEn: "Japan's largest snow-and-ice festival across three Sapporo venues — Odori Park, Susukino, and Tsudome. Massive 15m+ sculptures and night illumination.",
    startDate: "2026-02-04",
    endDate: "2026-02-11",
    placeName: "大通公園・すすきの・つどーむ (Sapporo, Hokkaido)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "高遠城址公園": [{
    nameJa: "高遠さくら祭り 2026",
    nameEn: "Takato Sakura Festival 2026",
    descJa: "「天下第一の桜」と称される高遠城址公園で約1500本のタカトオコヒガンザクラが咲く春の祭典。夜のライトアップも開催。",
    descEn: "Spring festival at Takato Castle Park with ~1,500 Takato Kohigan cherry trees, dubbed «No.1 cherry under heaven.» Includes evening illumination.",
    startDate: "2026-04-01",
    endDate: "2026-04-15",
    placeName: "高遠城址公園 (Ina, Nagano)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "清水寺": [{
    nameJa: "清水寺 秋の夜の特別拝観 2026",
    nameEn: "Kiyomizu-dera Autumn Night Special Viewing 2026",
    descJa: "世界遺産・清水寺の紅葉ライトアップ。13mの清水の舞台と境内のモミジが青白いライトと暖色で照らされる。",
    descEn: "Autumn night illumination at UNESCO Kiyomizu-dera — the 13 m wooden stage and maple foliage lit in cool blue and warm tones.",
    startDate: "2026-11-18",
    endDate: "2026-12-01",
    placeName: "清水寺 (Kyoto)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "東福寺": [{
    nameJa: "東福寺 紅葉シーズン 2026",
    nameEn: "Tofuku-ji Autumn Foliage Season 2026",
    descJa: "通天橋から眺める2,000本のモミジが朱色に染まる京都屈指の紅葉名所。",
    descEn: "Some 2,000 maples view from the Tsutenkyo bridge — one of Kyoto's premier autumn foliage destinations.",
    startDate: "2026-11-15",
    endDate: "2026-12-05",
    placeName: "東福寺 (Kyoto)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "富良野": [{
    nameJa: "ファーム富田 ラベンダー満開期 2026",
    nameEn: "Farm Tomita Lavender Peak Bloom 2026",
    descJa: "富良野ファーム富田を中心とするラベンダー畑が紫の絨毯に。7月中旬がピーク。",
    descEn: "Lavender fields centered on Farm Tomita reach a purple-carpet peak. Mid-July is the climax.",
    startDate: "2026-07-10",
    endDate: "2026-07-31",
    placeName: "ファーム富田 (Furano, Hokkaido)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "白川郷": [{
    nameJa: "白川郷ライトアップ 2026",
    nameEn: "Shirakawa-go Light-up 2026",
    descJa: "世界遺産・白川郷の合掌造り集落が雪とライトに照らされる冬限定の特別開催。",
    descEn: "UNESCO Shirakawa-go's gassho-zukuri farmhouses illuminated against snow — winter-only special event.",
    startDate: "2026-01-18",
    endDate: "2026-02-22",
    placeName: "白川郷 荻町 (Shirakawa, Gifu)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "長野県天空の楽園": [{
    nameJa: "天空の楽園 ナイトツアー 2026",
    nameEn: "Tenku no Rakuen Night Tour 2026",
    descJa: "環境省「日本一の星空」認定の阿智村で行われる、ゴンドラで標高1400mに登る星空鑑賞ツアー。",
    descEn: "Nightly stargazing tour rising by gondola to 1,400 m in Achi Village — certified «No.1 starry sky in Japan» by the Ministry of the Environment.",
    startDate: "2026-04-25",
    endDate: "2026-11-03",
    placeName: "富士見台高原 (Achi, Nagano)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "新倉山浅間公園": [{
    nameJa: "新倉山浅間公園 桜まつり 2026",
    nameEn: "Arakurayama Sengen Park Sakura Festival 2026",
    descJa: "富士山と五重塔と桜の三段構図が世界的に有名なフォトスポット。4月中旬の桜満開期に夜間ライトアップも実施。",
    descEn: "Site of the world-famous «Mt. Fuji + pagoda + cherry blossoms» three-tier composition. Night illumination during peak bloom in mid-April.",
    startDate: "2026-04-08",
    endDate: "2026-04-20",
    placeName: "新倉山浅間公園 (Fujiyoshida, Yamanashi)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
  "諏訪湖": [{
    nameJa: "諏訪湖祭湖上花火大会 2026",
    nameEn: "Lake Suwa Fireworks Festival 2026",
    descJa: "毎年8月15日開催、約4万発の花火が諏訪湖の湖面に映る日本屈指の花火大会。",
    descEn: "Held annually on August 15. Some 40,000 fireworks reflected on Lake Suwa — one of Japan's most spectacular fireworks displays.",
    startDate: "2026-08-15",
    endDate: "2026-08-15",
    placeName: "諏訪湖 (Suwa, Nagano)",
    eventStatus: "EventScheduled",
    eventAttendanceMode: "OfflineEventAttendanceMode",
  }],
};

export const getEvents = (locJp) => EVENTS[locJp] || [];
