/**
 * 撮影テクニックHowTo schema用ステップ定義 (Google Rich Results対応)
 * post slug → 撮影手順のマップ。記事本文と並行して構造化データ提供。
 */
export const HOWTO = {
  "lake-kawaguchi-fuji": {
    nameJa: "河口湖で逆さ富士を撮影する方法",
    nameEn: "How to Photograph the Inverted Fuji at Lake Kawaguchi",
    totalTime: "PT2H",
    supplyJa: ["カメラ本体", "三脚", "PLフィルター", "防寒着"],
    supplyEn: ["Camera body", "Tripod", "CPL filter", "Warm clothing"],
    steps: [
      { nameJa: "撮影スポット選定", textJa: "湖の北岸にある大石公園、産屋ヶ崎、長崎公園、八木崎公園のいずれかに移動する。富士山が南東方向に見える位置を選ぶ。", nameEn: "Choose your spot", textEn: "Head to one of the north-shore vantages: Oishi Park, Ubuyagasaki, Nagasaki Park, or Yagisaki Park. Pick a position with Mt. Fuji to the southeast." },
      { nameJa: "条件確認", textJa: "風速1m/秒以下、晴天、日の出前到着の3条件を満たす日を選ぶ。冬（12〜2月）が最も成功率が高い。", nameEn: "Verify conditions", textEn: "Aim for a day with under 1 m/s wind, clear skies, and arrival before sunrise. Winter (Dec–Feb) has the highest success rate." },
      { nameJa: "三脚と機材設置", textJa: "日の出30分前に到着し三脚を設置。標準ズーム（24-70mm）にPLフィルターを装着、PLは弱めに調整して逆さ富士の像を残す。", nameEn: "Set up gear", textEn: "Arrive 30 min before sunrise. Mount a 24–70 mm zoom on a tripod and attach a CPL filter — set the polarization weakly to preserve the reflection." },
      { nameJa: "露出決定", textJa: "マニュアルF8・ISO100・SS自動 (Av or M)、HDRブラケット3枚撮影設定。RAW記録ON。", nameEn: "Set exposure", textEn: "Manual mode at f/8, ISO 100, auto shutter (Av or M), with 3-frame HDR bracketing. RAW capture on." },
      { nameJa: "シャッターレリーズ", textJa: "風が止んだ瞬間にレリーズかセルフタイマーで撮影。マジックアワー (日の出前後30分) に集中して撮る。", nameEn: "Trigger the shutter", textEn: "Wait for windless moments and trigger via remote or self-timer. Concentrate shooting during the magic hour (30 min around sunrise)." },
    ],
  },
  "mt-fuji-arakurayama": {
    nameJa: "新倉山浅間公園で富士山+五重塔+桜の三段構図を撮る方法",
    nameEn: "How to Shoot the Mt. Fuji + Pagoda + Cherry Blossoms Three-Tier Frame at Arakurayama Sengen Park",
    totalTime: "PT3H",
    supplyJa: ["カメラ本体", "標準〜中望遠ズーム", "三脚", "防寒・暖かい飲み物"],
    supplyEn: ["Camera body", "Normal-to-short telephoto zoom", "Tripod", "Warm clothing & drinks"],
    steps: [
      { nameJa: "アクセス", textJa: "富士急行線「下吉田駅」から徒歩10分で新倉富士浅間神社到着。社殿を経て398段の咲くや姫階段を登る（迂回スロープあり）。", nameEn: "Access", textEn: "From Shimo-Yoshida Station on the Fujikyu Line, walk 10 min to Arakura Fuji Sengen Shrine. From the shrine grounds, climb the 398 «Sakuyahime» steps (a gentler slope path is also available)." },
      { nameJa: "早朝到着", textJa: "夜明け前到着が必須。日の出30分前から場所取り、三脚位置を確保する。", nameEn: "Arrive predawn", textEn: "Predawn arrival is essential. Secure your tripod position 30 minutes before sunrise." },
      { nameJa: "構図決定", textJa: "70mm前後で五重塔・桜・富士山を一フレームに圧縮。広角は塔と富士の間が空きすぎるため避ける。", nameEn: "Compose", textEn: "Use ~70 mm to compress the pagoda, cherry blossoms, and Mt. Fuji into a single frame. Avoid wide angles, which create too much space between elements." },
      { nameJa: "露出設定", textJa: "F8〜F11、ISO100、SSはマジックアワーの空に合わせる。RAW撮影必須。", nameEn: "Exposure", textEn: "f/8–f/11, ISO 100, with shutter speed metered for the magic-hour sky. RAW is essential." },
      { nameJa: "ベストモーメント撮影", textJa: "日の出直後の朝焼けで富士山が赤く染まる「赤富士」の瞬間が最高。連写でブラケット記録。", nameEn: "Capture the peak moment", textEn: "Just after sunrise, Mt. Fuji glows red — the famous «aka-fuji.» Burst-shoot to capture every variation." },
    ],
  },
  "chichibugahama-uyuni": {
    nameJa: "父母ヶ浜で「日本のウユニ塩湖」夕景を撮影する方法",
    nameEn: "How to Capture the «Uyuni-of-Japan» Sunset at Chichibugahama",
    totalTime: "PT2H",
    supplyJa: ["カメラ本体", "広角レンズ", "三脚", "着替え・敷物"],
    supplyEn: ["Camera body", "Wide-angle lens", "Tripod", "Change of clothes and tarp"],
    steps: [
      { nameJa: "三条件チェック", textJa: "干潮時刻と日没が重なる日、無風（風速2m/秒以下）、晴天の三条件を三豊市観光交流局公式カレンダーで確認。", nameEn: "Check three conditions", textEn: "Verify on Mitoyo City's tourism calendar that low tide coincides with sunset, wind is under 2 m/s, and skies are clear." },
      { nameJa: "現地到着", textJa: "日没30分前に到着し、潮が引いた干潟に薄く水が残るエリアを見つける。", nameEn: "Arrive on site", textEn: "Arrive 30 min before sunset and find a shallow tidepool where the retreating tide leaves a thin water layer." },
      { nameJa: "ローアングル設定", textJa: "膝立ちか地面スレスレに広角レンズ（16-35mm）で構える。チルト液晶があればさらに低い視点が可能。", nameEn: "Get low", textEn: "Kneel or get nearly ground-level with a 16–35 mm wide angle. A tilting LCD enables even lower angles." },
      { nameJa: "シルエット撮影", textJa: "人物を逆光シルエットに、カメラはマニュアルF8・SS1/60〜1/125・ISO200。HDRブラケット3〜5枚。", nameEn: "Shoot silhouettes", textEn: "Place subjects as backlit silhouettes. Manual mode at f/8, 1/60–1/125 s, ISO 200. Bracket 3–5 HDR frames." },
      { nameJa: "マジックアワー", textJa: "日没後10〜30分のマジックアワーが色彩のピーク。RAWで残し後処理で空と地面のバランスを整える。", nameEn: "Magic hour", textEn: "10–30 min after sunset is color peak. Capture in RAW and balance sky-vs-ground in post." },
    ],
  },
  "achi-stargazing": {
    nameJa: "阿智村で天の川と星空を撮影する方法",
    nameEn: "How to Photograph the Milky Way and Stars in Achi Village",
    totalTime: "PT4H",
    supplyJa: ["カメラ (高ISO耐性)", "広角単焦点 or F2.8ズーム", "三脚", "ヘッドライト (赤色LED)", "レンズヒーター"],
    supplyEn: ["High-ISO camera", "Fast wide prime or f/2.8 zoom", "Tripod", "Red-LED headlamp", "Lens heater"],
    steps: [
      { nameJa: "新月期の予約", textJa: "月齢カレンダーで新月±3日以内の晴天を狙い、スタービレッジ阿智ナイトツアーを1ヶ月前から予約する。", nameEn: "Book during new moon", textEn: "Target a clear night within ±3 days of new moon and book the Star Village Achi night tour a month ahead." },
      { nameJa: "ロープウェイ移動", textJa: "富士見台高原ロープウェイで標高1400mの山頂駅へ。消灯時間帯まで暗順応を待つ。", nameEn: "Take the ropeway", textEn: "Ride the Fujimidai Highland Ropeway to the 1,400 m summit station. Allow eyes to dark-adapt during the lights-out period." },
      { nameJa: "三脚と構図", textJa: "三脚を設置し広角レンズ（14-24mm or 20mm単焦点）で水平。前景に山稜や木を入れて奥行き表現。", nameEn: "Tripod and composition", textEn: "Set up the tripod with a wide lens (14–24 mm or 20 mm prime), level it. Include ridgeline or trees as foreground for depth." },
      { nameJa: "設定値", textJa: "マニュアル: ISO3200〜6400、F2.8、SS15〜25秒（500ルール）、ホワイトバランス3500〜4000K、RAW。", nameEn: "Settings", textEn: "Manual: ISO 3200–6400, f/2.8, 15–25 s (500 rule), white balance 3500–4000 K, RAW." },
      { nameJa: "比較明合成", textJa: "前景と星空をそれぞれ最適露出で撮影し、Photoshopで比較明合成。または1枚撮りでLEDで微弱補光。", nameEn: "Brightness blending", textEn: "Shoot foreground and stars separately at their optimal exposures and blend in Photoshop. Alternatively, light-paint the foreground with a soft LED in a single frame." },
    ],
  },
  "takato-castle-cherry": {
    nameJa: "高遠城址公園で「天下第一の桜」を撮影する方法",
    nameEn: "How to Photograph the «No.1 Cherry Under Heaven» at Takato Castle Park",
    totalTime: "PT2H30M",
    supplyJa: ["カメラ本体", "標準ズーム", "中望遠ズーム", "三脚", "防寒着 (夜間)"],
    supplyEn: ["Camera body", "Standard zoom", "Short telephoto", "Tripod", "Warm clothing for night"],
    steps: [
      { nameJa: "アクセス", textJa: "JR伊那市駅からタクシー15分。週末早朝なら 6:00 までに駐車場確保。", nameEn: "Access", textEn: "15-min taxi from JR Ina-shi Station. On weekends, secure parking by 6 a.m." },
      { nameJa: "南ゲート構図", textJa: "太鼓櫓と桜のトンネルを縦35mmで。順光は午前中。", nameEn: "South Gate composition", textEn: "Vertical at 35 mm framing Taiko Yagura and the cherry tunnel. Front light comes in the morning." },
      { nameJa: "本丸構図", textJa: "高遠閣を背景に標準〜中望遠で桜雲を撮る。", nameEn: "Main bailey", textEn: "Use 50–85 mm to capture clouds of blossoms with the Takato-kaku pavilion behind." },
      { nameJa: "中央アルプス背景", textJa: "白山観音から70-200mm望遠圧縮で雪のアルプスと桜の三段構図。", nameEn: "Central Alps backdrop", textEn: "From Hakusan Kannon, compress with 70–200 mm to layer Alps + cherry clouds + park." },
      { nameJa: "ライトアップ", textJa: "18時開園。三脚OK。ISO400・F4・1/4秒前後で人通りをブラす。", nameEn: "Night illumination", textEn: "18:00 opening. Tripod allowed. ISO 400, f/4, ~1/4 s blurs passersby." },
    ],
  },
  "matsumoto-castle-seasons": {
    nameJa: "国宝・松本城を四季ごとに撮影する方法",
    nameEn: "How to Photograph National Treasure Matsumoto Castle Through the Seasons",
    totalTime: "PT2H",
    supplyJa: ["カメラ本体", "標準ズーム", "70-200mm望遠", "三脚 (許可エリア)", "PLフィルター"],
    supplyEn: ["Camera body", "Standard zoom", "70–200 mm telephoto", "Tripod (permitted areas)", "CPL filter"],
    steps: [
      { nameJa: "埋橋ベスト構図", textJa: "内堀北西の埋橋から縦構図で天守を撮る。これが王道。", nameEn: "Uzumi Bridge classic", textEn: "Vertical from Uzumi Bridge on the NW inner moat — the iconic shot." },
      { nameJa: "アルプスを圧縮", textJa: "70-200mmで天守背後の北アルプスを引き寄せる。早朝モルゲンロート狙い。", nameEn: "Compress the Alps", textEn: "Use 70–200 mm to compress the Northern Alps behind the keep. Target alpenglow at sunrise." },
      { nameJa: "PLで反射制御", textJa: "内堀の水鏡。PLを弱めて天守の倒影を残す。", nameEn: "Manage reflections", textEn: "Light CPL keeps the keep's reflection in the moat clear." },
      { nameJa: "黒門の桜", textJa: "4月中旬、黒門の桜トンネルから天守を覗く構図。", nameEn: "Black Gate sakura", textEn: "Mid-April: shoot through the Kuromon cherry tunnel toward the keep." },
      { nameJa: "ライトアップ", textJa: "桜まつり期間と冬の特別ライトアップ。三脚指定エリアのみ可。", nameEn: "Illumination", textEn: "During Sakura Festival and winter special illumination. Tripods in designated areas only." },
    ],
  },
  "lake-suwa-omiwatari": {
    nameJa: "諏訪湖の御神渡りを撮影する方法",
    nameEn: "How to Photograph Omiwatari Ice Ridges on Lake Suwa",
    totalTime: "PT3H",
    supplyJa: ["カメラ本体", "広角〜標準ズーム", "三脚", "極寒装備", "予備バッテリー"],
    supplyEn: ["Camera body", "Wide-to-standard zoom", "Tripod", "Extreme cold gear", "Spare batteries"],
    steps: [
      { nameJa: "出現確認", textJa: "1月下旬〜2月中旬、最低気温-10℃以下が3〜5日続いた後の早朝、八剱神社や諏訪市公式SNSで御神渡り出現状況を確認。", nameEn: "Check appearance", textEn: "From late January to mid-February, after 3–5 consecutive days below −10 °C, check Yatsurugi Shrine or Suwa City SNS for the latest Omiwatari status." },
      { nameJa: "撮影地選定", textJa: "諏訪市湖岸通りの間欠泉センター周辺（接近撮影）か、立石公園展望台（俯瞰）を選ぶ。", nameEn: "Choose vantage", textEn: "Pick the Geyser Center area on the lakeshore (close shots) or Tateishi Park observatory (elevated overview)." },
      { nameJa: "防寒準備", textJa: "氷点下20℃以下になることもあるため、本格的冬山装備、カメラ予備バッテリー2〜3個を保温ポケットに入れて持参。", nameEn: "Prepare for cold", textEn: "Temperatures can drop below −20 °C — wear serious winter mountaineering gear and keep 2–3 spare batteries warm in inner pockets." },
      { nameJa: "日の出前到着", textJa: "日の出30分前到着、三脚を陸上に設置（氷上は厳禁）。広角〜標準（16-70mm）で氷の隆起ラインを構図。", nameEn: "Arrive predawn", textEn: "Be on site 30 min before sunrise. Tripod on shore only — never on ice. Compose with 16–70 mm to capture the ridge lines." },
      { nameJa: "サイドライト撮影", textJa: "朝日の横方向の光線（サイドライト）が氷の質感を最大化。ISO200・F8・SSは適正で霜と氷を露光。", nameEn: "Capture in side light", textEn: "Morning side light maximizes ice texture. ISO 200, f/8, with shutter speed metered for proper exposure of frost and ice." },
    ],
  },
  "sapporo-snow-festival": {
    nameJa: "さっぽろ雪まつりを撮影する方法",
    nameEn: "How to Photograph the Sapporo Snow Festival",
    totalTime: "PT3H",
    supplyJa: ["カメラ本体", "広角〜標準ズーム", "三脚 (指定区域のみ)", "防寒装備一式", "予備バッテリー"],
    supplyEn: ["Camera body", "Wide-to-standard zoom", "Tripod (designated zones only)", "Full winter gear", "Spare batteries"],
    steps: [
      { nameJa: "会場別の役割を理解", textJa: "大通公園 (大雪像)、すすきの (氷彫刻)、つどーむ (雪遊び) — 大通会場が main。", nameEn: "Know the venues", textEn: "Odori Park (mass sculptures), Susukino (ice carvings), Tsudome (snow play). Odori is the main." },
      { nameJa: "マジックアワーを狙う", textJa: "日没直後〜18時のブルーアワーが青の空+暖色イルミで最美。", nameEn: "Target magic hour", textEn: "Just after sunset to 18:00 — blue sky and warm illumination contrast peaks." },
      { nameJa: "露出補正", textJa: "雪は白飛びしやすい。+1〜+1.5EV補正、ISO100-400、F8。", nameEn: "Exposure compensation", textEn: "Snow tricks the meter; +1 to +1.5 EV, ISO 100–400, f/8." },
      { nameJa: "三脚利用", textJa: "公式三脚OKエリアのみ使用。手持ち時はISO上げて手ブレ補正ON。", nameEn: "Tripod use", textEn: "Only in official tripod-allowed zones. Otherwise raise ISO and use IS." },
      { nameJa: "防寒徹底", textJa: "氷点下5-10℃、カイロ3個必携、バッテリー予備2個を保温ポケットへ。", nameEn: "Stay warm", textEn: "−5 to −10 °C — three heat packs, two spare batteries in inner pockets." },
    ],
  },
  "shiretoko-drift-ice": {
    nameJa: "知床の流氷を撮影する方法",
    nameEn: "How to Photograph Drift Ice at Shiretoko",
    totalTime: "PT4H",
    supplyJa: ["カメラ本体", "70-200mm望遠 (野鳥用)", "標準ズーム", "防水カバー", "極寒装備", "予備バッテリー3個"],
    supplyEn: ["Camera body", "70–200 mm telephoto (for raptors)", "Standard zoom", "Rain cover", "Extreme cold gear", "Three spare batteries"],
    steps: [
      { nameJa: "シーズン確認", textJa: "1月下旬〜3月上旬。流氷接岸状況を毎日確認。", nameEn: "Check season", textEn: "Late January to early March. Verify daily drift-ice arrival status." },
      { nameJa: "クルーズ予約", textJa: "ウトロ港発「おーろら」を前日までに予約。早朝便がベスト光線。", nameEn: "Book cruise", textEn: "Reserve the «Aurora» from Utoro Port a day ahead. Early morning has best light." },
      { nameJa: "露出+1EV", textJa: "白い氷で測光が暗く出る。+1EV補正、スポット測光で岩肌に合わせる。", nameEn: "+1 EV correction", textEn: "Ice underexposes. Apply +1 EV or spot-meter on dark rocks." },
      { nameJa: "野生動物狙い", textJa: "70-200mmでオオワシ、オジロワシ、シャチ。連写ON、SS1/1000以上。", nameEn: "Wildlife", textEn: "70–200 mm for Steller's eagles, white-tailed eagles, orcas. Burst, 1/1000+ shutter." },
      { nameJa: "結露防止", textJa: "船室から外に出る前にレンズフードでカバー、室内戻る時はジップロック密封。", nameEn: "Avoid condensation", textEn: "Hood up before going outside; ziplock seal before re-entering warm cabin." },
    ],
  },
  "furano-lavender": {
    nameJa: "富良野ラベンダー畑を撮影する方法",
    nameEn: "How to Photograph Furano Lavender Fields",
    totalTime: "PT2H",
    supplyJa: ["カメラ本体", "24-70mm標準ズーム", "70-200mm望遠", "PLフィルター", "マクロレンズ (ミツバチ用)"],
    supplyEn: ["Camera body", "24–70 mm zoom", "70–200 mm telephoto", "CPL filter", "Macro (for bees)"],
    steps: [
      { nameJa: "シーズン確認", textJa: "7月中旬-下旬がピーク。ファーム富田公式サイトで開花状況確認。", nameEn: "Check bloom", textEn: "Mid-to-late July peaks. Verify on Farm Tomita's official site." },
      { nameJa: "早朝5:30到着", textJa: "8時以降は観光バスで混雑。早朝の柔らかい順光が最美。", nameEn: "Arrive 5:30 a.m.", textEn: "After 8 a.m. tour buses pack the place. Early front light is best." },
      { nameJa: "彩りの畑構図", textJa: "7色のしましま花畑を35-85mmで圧縮。背景に十勝岳。", nameEn: "Rainbow stripe field", textEn: "35–85 mm compresses the 7-color stripes. Tokachi mountains as backdrop." },
      { nameJa: "PL強調", textJa: "PLで葉の反射を抑え、ラベンダー紫を鮮やかに。", nameEn: "CPL", textEn: "CPL kills leaf glare and saturates lavender purple." },
      { nameJa: "通路から外れない", textJa: "私有地踏み込み厳禁。指定通路から望遠で入り込む。", nameEn: "Stay on paths", textEn: "No stepping into beds. Reach in with telephoto only." },
    ],
  },
  "shirakawa-go-snow": {
    nameJa: "白川郷の雪景色を撮影する方法",
    nameEn: "How to Photograph Shirakawa-go in Snow",
    totalTime: "PT3H",
    supplyJa: ["カメラ本体", "24-70mm標準", "70-200mm望遠", "三脚 (ライトアップ時)", "雪上対応ブーツ", "手袋"],
    supplyEn: ["Camera body", "24–70 mm", "70–200 mm telephoto", "Tripod (illumination only)", "Snow boots", "Gloves"],
    steps: [
      { nameJa: "ライトアップ予約", textJa: "1月中旬〜2月の指定日。完全予約制、1ヶ月前から。", nameEn: "Book light-up", textEn: "Selected days from mid-Jan to Feb. Fully reservation-only, plan a month ahead." },
      { nameJa: "荻町城跡展望台", textJa: "村営シャトルバス5分。集落全景の王道アングル。", nameEn: "Ogimachi observatory", textEn: "5-min village shuttle. The classic full-village vantage." },
      { nameJa: "露出+1EV", textJa: "雪で測光が暗くなる。+1EV補正必須。", nameEn: "+1 EV", textEn: "Snow underexposes; always +1 EV." },
      { nameJa: "ライトアップ設定", textJa: "ブルーアワー (17:30-18:00)、ISO400、F8、SS5-15秒、三脚必須。", nameEn: "Illumination settings", textEn: "Blue hour 17:30–18:00, ISO 400, f/8, 5–15 s, tripod essential." },
      { nameJa: "村内マナー", textJa: "住民の生活集落。私有地不可、フラッシュ禁止。", nameEn: "Etiquette", textEn: "Live-in village — no private property entry, no flash." },
    ],
  },
  "kyoto-autumn-temples": {
    nameJa: "京都の紅葉と寺社を1日で撮影する方法",
    nameEn: "How to Photograph Kyoto's Autumn Temples in One Day",
    totalTime: "PT8H",
    supplyJa: ["カメラ本体", "標準ズーム", "中望遠", "PLフィルター", "歩きやすい靴"],
    supplyEn: ["Camera body", "Standard zoom", "Short telephoto", "CPL filter", "Comfortable walking shoes"],
    steps: [
      { nameJa: "06:30 東福寺", textJa: "通天橋の2,000本紅葉を真っ先に。橋上立ち止まり禁止。", nameEn: "06:30 Tofuku-ji", textEn: "Hit Tsutenkyo bridge first for 2,000 maples. No stopping on bridge." },
      { nameJa: "10:30 清水寺", textJa: "舞台と紅葉。手持ち、PL使用。", nameEn: "10:30 Kiyomizu-dera", textEn: "Stage with foliage. Handheld + CPL." },
      { nameJa: "14:00 金閣寺", textJa: "鏡湖池の金閣と紅葉。逆光ドラマチック。", nameEn: "14:00 Kinkaku-ji", textEn: "Golden Pavilion with autumn reflection. Backlit drama." },
      { nameJa: "夕方 永観堂", textJa: "時間あれば京都モミジNo.1の永観堂で締め。", nameEn: "Evening Eikando", textEn: "If time, finish at Kyoto's #1 maple spot." },
      { nameJa: "三脚不可", textJa: "ほぼ全寺社で三脚禁止。手持ちISO400-800で機動性確保。", nameEn: "No tripods", textEn: "Almost all temples ban tripods. Handheld at ISO 400–800." },
    ],
  },
  "kiyomizu-illumination": {
    nameJa: "清水寺の紅葉ライトアップを撮影する方法",
    nameEn: "How to Photograph Kiyomizu-dera Autumn Illumination",
    totalTime: "PT2H",
    supplyJa: ["カメラ本体", "F2.8明るい標準ズーム", "単焦点 (35mm/50mm F1.8)", "防寒着"],
    supplyEn: ["Camera body", "f/2.8 standard zoom", "Fast prime (35/50mm f/1.8)", "Warm clothing"],
    steps: [
      { nameJa: "17時受付", textJa: "17:00受付前に並ぶ。17:30開場で奥の院へ直行。", nameEn: "Queue at 17:00", textEn: "Line up before 17:00. At 17:30 opening, head to Okuno-in fast." },
      { nameJa: "ブルーアワーが命", textJa: "17:50-18:30が最美。空が黒くなる前に主構図完成。", nameEn: "Blue hour is key", textEn: "17:50–18:30 is peak. Lock down compositions before sky goes black." },
      { nameJa: "三脚不可", textJa: "境内全域三脚禁止。ISO3200-6400、F2.8、SS1/30以上、手ブレ補正。", nameEn: "No tripods", textEn: "Banned everywhere. ISO 3200–6400, f/2.8, ≥1/30, image stabilization." },
      { nameJa: "三重塔も", textJa: "舞台撮影後は三重塔と子安の塔も巡る。", nameEn: "Pagodas too", textEn: "After the stage, photograph the three-story and Koyasu pagodas." },
      { nameJa: "20:30受付終了", textJa: "音羽の滝で締めて 21:00 退出。", nameEn: "Last entry 20:30", textEn: "Finish at Otowa Falls and exit by 21:00." },
    ],
  },
  "byodoin-phoenix-hall": {
    nameJa: "平等院鳳凰堂の対称美を撮影する方法",
    nameEn: "How to Photograph Byodo-in Phoenix Hall's Symmetry",
    totalTime: "PT1H",
    supplyJa: ["カメラ本体", "24-70mm標準ズーム", "三脚 (許可エリア)", "PLフィルター", "水平器"],
    supplyEn: ["Camera body", "24–70 mm zoom", "Tripod (permitted areas)", "CPL filter", "Bubble level"],
    steps: [
      { nameJa: "08:30開門", textJa: "開門と同時に阿字池南東岸へ。鏡面状態を狙う。", nameEn: "08:30 opening", textEn: "Head to the SE pond bank at opening for mirror-still water." },
      { nameJa: "対称構図", textJa: "水平器か三脚で完全対称構図。50mm前後標準。", nameEn: "Perfect symmetry", textEn: "Use level or tripod for true symmetry. ~50 mm." },
      { nameJa: "PL弱め", textJa: "PLは弱めに。強すぎると逆さ鳳凰堂が消える。", nameEn: "Light CPL", textEn: "Use CPL gently — too strong erases the inverted reflection." },
      { nameJa: "風待ち", textJa: "風が止んだ瞬間に撮影。1時間に5-10秒のチャンスがある。", nameEn: "Wait for stillness", textEn: "Shoot when wind drops. 5–10 s windows occur every hour." },
      { nameJa: "夕方シルエット", textJa: "14時以降は逆光。鳳凰堂シルエット+夕焼けの構図も。", nameEn: "Evening silhouette", textEn: "After 14:00 it backlights — try silhouette + sunset framing." },
    ],
  },
  "ise-jingu-pilgrimage": {
    nameJa: "伊勢神宮を参拝順に撮影する方法",
    nameEn: "How to Photograph Ise Jingu in Proper Pilgrimage Order",
    totalTime: "PT4H",
    supplyJa: ["カメラ本体", "明るい標準ズーム F2.8-4", "PLフィルター", "歩きやすい靴"],
    supplyEn: ["Camera body", "Fast standard zoom f/2.8–4", "CPL filter", "Walking shoes"],
    steps: [
      { nameJa: "07:30 外宮", textJa: "豊受大神宮 (外宮) から開始。北御門口から30-45分参拝。", nameEn: "07:30 Geku", textEn: "Start at Outer Shrine (Toyouke). North gate, 30–45 min." },
      { nameJa: "本殿撮影禁止", textJa: "ご正宮の階段から先・白い御幌は撮影禁止。", nameEn: "No main hall photos", textEn: "Forbidden past Goshogu steps and white curtain." },
      { nameJa: "09:00 内宮へ", textJa: "外宮から内宮までバス20分。宇治橋・五十鈴川御手洗場を撮影。", nameEn: "09:00 to Naiku", textEn: "20-min bus. Photograph Uji Bridge and Mitarashi pavilion." },
      { nameJa: "杉並木", textJa: "千年杉の縦構図、奥行き表現。F4-5.6で背景の柔らかさ。", nameEn: "Cedar avenue", textEn: "Vertical of 1000-year cedars. f/4–5.6 for soft depth." },
      { nameJa: "おかげ横丁", textJa: "11時以降は参拝後にカジュアル撮影。江戸-明治の町並み再現。", nameEn: "Okage Yokocho", textEn: "After 11:00, casual shooting in the recreated Edo-Meiji street." },
    ],
  },
  "miyakojima-blue": {
    nameJa: "宮古ブルーを撮影する方法",
    nameEn: "How to Capture Miyako Blue",
    totalTime: "PT5H",
    supplyJa: ["カメラ本体", "16-35mm広角", "70-200mm望遠", "PLフィルター必須", "ND8/16フィルター", "ドローン (任意)"],
    supplyEn: ["Camera body", "16–35 mm wide", "70–200 mm telephoto", "CPL (essential)", "ND 8/16 filters", "Drone (optional)"],
    steps: [
      { nameJa: "10時-14時に撮る", textJa: "太陽が高く海底まで光が届く時間が最強の発色。", nameEn: "Shoot 10–14", textEn: "Sun-high hours penetrate light to the seafloor for maximum color." },
      { nameJa: "PL必須", textJa: "海面の反射を抑えると海底のサンゴが透ける。", nameEn: "CPL is essential", textEn: "Cuts surface glare so corals are visible." },
      { nameJa: "与那覇前浜", textJa: "日本一の白砂7km。来間大橋とのコラボが王道。", nameEn: "Yonaha Maehama", textEn: "Japan's #1 white-sand beach 7 km. Pair with Kurima Bridge." },
      { nameJa: "伊良部大橋", textJa: "3,540m日本最長無料橋。NDで橋を長秒露光、波を滑らかに。", nameEn: "Irabu Bridge", textEn: "Japan's longest toll-free bridge at 3,540 m. ND for long-exposure smooth water." },
      { nameJa: "ドローン活用", textJa: "規制が緩く、上空からのターコイズが映える。ローカルルール確認。", nameEn: "Drone use", textEn: "Less restricted; aerial turquoise shines. Verify local rules." },
    ],
  },
  "himeji-castle-spring": {
    nameJa: "姫路城と桜を撮影する方法",
    nameEn: "How to Photograph Himeji Castle with Cherry Blossoms",
    totalTime: "PT3H",
    supplyJa: ["カメラ本体", "24-70mm標準", "70-200mm望遠", "PLフィルター", "三脚 (許可エリア)"],
    supplyEn: ["Camera body", "24–70 mm", "70–200 mm telephoto", "CPL", "Tripod (permitted areas)"],
    steps: [
      { nameJa: "08:00開園前到着", textJa: "8:30開園、9時以降は混雑。早朝の青空+白漆喰のコントラスト◎。", nameEn: "Arrive 08:00", textEn: "Opens 8:30; after 9 it's packed. Early blue sky + white plaster pop." },
      { nameJa: "三の丸広場 (王道)", textJa: "広い芝生越しの天守と桜。35-50mm。", nameEn: "Sannomaru Plaza (classic)", textEn: "Lawn-cross with keep and cherry. 35–50 mm." },
      { nameJa: "西の丸庭園 (高所)", textJa: "天守を見下ろす構図。桜越しに俯瞰。", nameEn: "Nishi-no-maru (elevated)", textEn: "Look down on the keep through cherry blossoms." },
      { nameJa: "シロトピア記念公園", textJa: "北東から人少なめ。穴場の構図。", nameEn: "Shirotopia Memorial Park", textEn: "NE side, less crowded — hidden vantage." },
      { nameJa: "夜のライトアップ", textJa: "開花期間のみ実施。三脚OKエリアで長秒露光。", nameEn: "Night illumination", textEn: "Only during bloom period. Tripod-allowed zones for long exposure." },
    ],
  },
  "otaru-canal-night": {
    nameJa: "小樽運河の夜景を撮影する方法",
    nameEn: "How to Photograph Otaru Canal at Night",
    totalTime: "PT2H",
    supplyJa: ["カメラ本体", "24-70mm標準", "三脚必須", "NDフィルター", "防寒着"],
    supplyEn: ["Camera body", "24–70 mm", "Tripod required", "ND filter", "Warm clothing"],
    steps: [
      { nameJa: "ブルーアワー狙い", textJa: "日没30-40分後の青の時間帯。ガス灯の暖色とのコントラストが最美。", nameEn: "Target blue hour", textEn: "30–40 min after sunset. Warm gas-lamp + blue sky contrast peaks." },
      { nameJa: "浅草橋から", textJa: "中央橋の南、浅草橋からの王道アングル。倉庫と運河と橋を一枚に。", nameEn: "From Asakusa Bridge", textEn: "South of Chuo Bridge. Classic angle: warehouses, canal, bridge in one frame." },
      { nameJa: "長秒露光", textJa: "ISO100、F8、SS15秒。NDで光量調整しつつ水面を滑らかに。", nameEn: "Long exposure", textEn: "ISO 100, f/8, 15 s. ND smooths water and balances light." },
      { nameJa: "雪の日", textJa: "シャッター4-8秒で雪の流れを線で表現。", nameEn: "Snow days", textEn: "4–8 s captures snowfall as gentle streaks." },
      { nameJa: "結露対策", textJa: "屋外から店内戻る時はジップロック密封。", nameEn: "Anti-condensation", textEn: "Ziplock seal when re-entering warm shops." },
    ],
  },
  "noboribetsu-jigokudani": {
    nameJa: "登別 地獄谷の湯けむりを撮影する方法",
    nameEn: "How to Photograph Noboribetsu Jigokudani Steam",
    totalTime: "PT2H",
    supplyJa: ["カメラ本体", "16-35mm広角", "70-200mm望遠", "ND8-16フィルター", "UVフィルター (硫黄対策)"],
    supplyEn: ["Camera body", "16–35 mm wide", "70–200 mm telephoto", "ND 8–16 filter", "UV filter (sulfur protection)"],
    steps: [
      { nameJa: "早朝7時到着", textJa: "観光客がほぼいない時間帯。湯気が朝日に金色に染まる。", nameEn: "Arrive 07:00", textEn: "Almost empty. Steam turns gold in dawn light." },
      { nameJa: "展望台王道", textJa: "駐車場から徒歩5分の展望台が main アングル。", nameEn: "Main observation deck", textEn: "5-min walk from parking — the prime vantage." },
      { nameJa: "露出は岩で測光", textJa: "湯気で測光すると暗くなる。スポット測光で岩肌に合わせる。", nameEn: "Meter on rock", textEn: "Steam fools the meter. Spot-meter on dark rock for accurate exposure." },
      { nameJa: "ND長秒で湯気を流す", textJa: "ND8-16で1-4秒露光。湯気が幻想的に流れる。", nameEn: "ND for flowing steam", textEn: "ND 8–16 for 1–4 s exposures — steam becomes dreamlike streams." },
      { nameJa: "硫黄からカメラ保護", textJa: "UVフィルター必須。長時間の露出は避け、こまめにレンズクリーニング。", nameEn: "Protect from sulfur", textEn: "UV filter mandatory. Limit exposure time and clean often." },
    ],
  },
};

export const getHowTo = (slug) => HOWTO[slug];
