/**
 * 撮影地の実用情報 — アクセス、駐車場、入場料、所要時間、ベスト時間帯
 * 主要 24 loc を網羅。情報は2026年4月時点。
 * UX/SEO の両方に効く: 旅行検索ヒット↑、滞在時間↑
 */
export const LOC_INFO = {
  "新倉山浅間公園": {
    access:   { ja: "富士急行線「下吉田駅」より徒歩約10分。高速バスは「富士山駅」下車徒歩15分。", en: "10-min walk from Shimo-Yoshida Station (Fujikyu Line). Or 15-min walk from Fuji-san Station via highway bus." },
    parking:  { ja: "無料駐車場100台。桜満開期は早朝4-5時で満車。", en: "Free parking for 100 cars. Fills by 4-5 a.m. during peak bloom." },
    fee:      { ja: "入園無料。", en: "Free admission." },
    duration: { ja: "撮影込で1.5〜2時間。", en: "1.5–2 hours including photography." },
    bestTime: { ja: "4月中旬の日の出 (5-6時)。", en: "Mid-April sunrise (5-6 a.m.)." },
  },
  "河口湖": {
    access:   { ja: "富士急行線「河口湖駅」が起点。駅前から周遊バス (オムニバス)。", en: "Kawaguchiko Station (Fujikyu Line). Take the local sightseeing «Omni Bus» from the station." },
    parking:  { ja: "湖畔各所に無料駐車場。大石公園は最も整備。", en: "Free parking at various lakeside spots. Oishi Park is best-equipped." },
    fee:      { ja: "湖周遊・公園は無料。遊覧船は1,000円〜。", en: "Lake tour and parks are free. Sightseeing boats from ¥1,000." },
    duration: { ja: "撮影地巡りで半日〜1日。", en: "Half day to full day for the major spots." },
    bestTime: { ja: "早朝6-8時の無風・冬季の透明度ピーク。", en: "Early morning 6-8 a.m. when winds are still; winter offers peak clarity." },
  },
  "松本城": {
    access:   { ja: "JR中央本線「松本駅」から徒歩15分。バスは「松本城・市役所前」下車。", en: "15-min walk from JR Matsumoto Station. Or take a bus to «Matsumoto-jo / Shiyakusho-mae»." },
    parking:  { ja: "松本城大手門駐車場 (有料、30分150円)。", en: "Otemon Parking (paid, ¥150/30 min)." },
    fee:      { ja: "天守入場700円 (大人)。外周は無料。", en: "Keep entry ¥700 (adult). Outer grounds free." },
    duration: { ja: "外観撮影30分、天守内部含めて1.5時間。", en: "30 min for exterior; 1.5 hr including the keep interior." },
    bestTime: { ja: "4月中旬桜と早朝のモルゲンロート。", en: "Mid-April cherry blossoms with morning alpenglow." },
  },
  "高遠城址公園": {
    access:   { ja: "JR飯田線「伊那市駅」よりバス・タクシー15分。中央道伊那ICから車25分。", en: "15-min bus/taxi from JR Ina-shi Station. 25-min drive from Ina IC on Chuo Expressway." },
    parking:  { ja: "桜まつり期間中は有料 (700円)。徒歩15分の無料臨時駐車場あり。", en: "Paid (¥700) during Sakura Festival; free temporary parking 15-min walk away." },
    fee:      { ja: "桜まつり期間500円、それ以外無料。", en: "¥500 during Sakura Festival; free other times." },
    duration: { ja: "1.5〜2時間。夜のライトアップなら3時間。", en: "1.5–2 hr; add 1 hr for evening illumination." },
    bestTime: { ja: "4月10日前後の早朝 (5-7時) と18-21時のライトアップ。", en: "Around April 10, early morning (5-7 a.m.) and night illumination (18-21)." },
  },
  "駒つなぎの桜": {
    access:   { ja: "JR飯田線「飯田駅」からタクシー40分。中央道飯田山本ICから車30分。", en: "40-min taxi from JR Iida Station. 30-min drive from Iida-Yamamoto IC." },
    parking:  { ja: "5-10台の小規模駐車場。週末早朝は競争激しい。", en: "Small lot for 5-10 cars. Competitive on weekend dawns." },
    fee:      { ja: "無料。地元の方の生活集落のため、マナー厳守。", en: "Free, but be respectful — this is a residential village." },
    duration: { ja: "撮影のみで1〜1.5時間。", en: "1–1.5 hr for shooting only." },
    bestTime: { ja: "4月下旬、新月期の星空+水鏡 (薄明〜深夜)。", en: "Late April, new moon nights for stars + paddy reflection." },
  },
  "長野県天空の楽園": {
    access:   { ja: "中央道飯田山本ICから車25分。富士見台高原ロープウェイ「ヘブンスそのはら」へ。", en: "25-min drive from Iida-Yamamoto IC to «Heavens Sonohara» ropeway." },
    parking:  { ja: "ロープウェイ駐車場無料 (800台)。", en: "Free parking at ropeway base (800 cars)." },
    fee:      { ja: "ナイトツアー大人3,800円〜 (夏は4,800円)。要事前予約。", en: "Night tour from ¥3,800 (¥4,800 in summer). Advance booking required." },
    duration: { ja: "ロープウェイ往復+山頂滞在で3時間。", en: "3 hr including ropeway and summit time." },
    bestTime: { ja: "新月期の春・夏・秋の20-22時。", en: "New moon nights, spring/summer/autumn 20:00-22:00." },
  },
  "諏訪湖": {
    access:   { ja: "JR中央本線「上諏訪駅」から徒歩7分で湖岸。", en: "7-min walk from JR Kamisuwa Station to the lakeshore." },
    parking:  { ja: "諏訪湖畔の無料駐車場多数。", en: "Multiple free lakeside lots." },
    fee:      { ja: "湖周遊無料。間欠泉センター入館500円。", en: "Free; Geyser Center admission ¥500." },
    duration: { ja: "湖一周ドライブ40分、撮影スポット数か所で2時間。", en: "40-min drive around the lake; 2 hr for several photo spots." },
    bestTime: { ja: "夏: 8月15日花火大会。冬: 1-2月の早朝 (御神渡り)。", en: "Summer: Aug 15 fireworks. Winter: Jan-Feb early mornings (Omiwatari)." },
  },
  "立石公園": {
    access:   { ja: "上諏訪駅から車10分 or タクシー。バス便なし。", en: "10-min taxi or drive from Kamisuwa Station. No bus service." },
    parking:  { ja: "無料駐車場20台。夜間も利用可。", en: "Free parking for ~20 cars, accessible at night." },
    fee:      { ja: "無料。", en: "Free." },
    duration: { ja: "撮影で1時間。", en: "1 hr for shooting." },
    bestTime: { ja: "夕方〜青の時間帯。新月期の星空も。", en: "Sunset to blue hour; new-moon nights for stargazing." },
  },
  "弘法山古墳": {
    access:   { ja: "JR松本駅からバス20分+徒歩20分で登山口。", en: "20-min bus + 20-min walk from JR Matsumoto Station to trailhead." },
    parking:  { ja: "登山口に無料駐車場20台。桜満開期は混雑。", en: "Free parking for 20 cars at trailhead. Crowded at peak bloom." },
    fee:      { ja: "無料。", en: "Free." },
    duration: { ja: "登山15-20分+撮影で1.5時間。", en: "15-20 min hike + 1.5 hr photo time." },
    bestTime: { ja: "4月中旬の日の出 (5-6時)。", en: "Mid-April sunrise (5-6 a.m.)." },
  },
  "城山公園(松本市)": {
    access:   { ja: "JR松本駅からバス15分+徒歩10分。", en: "15-min bus + 10-min walk from JR Matsumoto Station." },
    parking:  { ja: "公園駐車場無料 (30台)。", en: "Free park lot for 30 cars." },
    fee:      { ja: "無料。", en: "Free." },
    duration: { ja: "1.5時間。", en: "1.5 hr." },
    bestTime: { ja: "4月10-15日の桜+モルゲンロート。", en: "April 10-15 with cherry blossoms and morning alpenglow." },
  },
  "さっぽろ雪まつり": {
    access:   { ja: "札幌市営地下鉄「大通駅」直結 (大通会場)。すすきの駅 (氷彫刻会場)。", en: "Sapporo Subway «Odori» station (Odori venue) or «Susukino» (ice carvings)." },
    parking:  { ja: "公共交通機関推奨。周辺有料駐車場は混雑。", en: "Public transit recommended; surrounding paid lots fill up." },
    fee:      { ja: "観覧無料。", en: "Free viewing." },
    duration: { ja: "全会場巡りで4-5時間。", en: "4-5 hr to cover all venues." },
    bestTime: { ja: "2月初旬、日没後〜21時のライトアップ。", en: "Early February, post-sunset to 21:00 illumination." },
  },
  "知床": {
    access:   { ja: "女満別空港よりバス2時間で「ウトロ温泉」。釧路空港経由も可。", en: "2-hr bus from Memanbetsu Airport to Utoro Onsen. Via Kushiro Airport also possible." },
    parking:  { ja: "ウトロ各観光施設に無料駐車場。", en: "Free parking at most Utoro tourist facilities." },
    fee:      { ja: "知床五湖トレッキング 250円-3,500円 (時期で異なる)。流氷クルーズ4,500円〜。", en: "Shiretoko Goko trekking ¥250-3,500 (varies by season). Drift-ice cruise from ¥4,500." },
    duration: { ja: "1日 (流氷シーズンは早朝出発)。", en: "Full day (early start in drift-ice season)." },
    bestTime: { ja: "1-3月の流氷シーズン早朝 (8-10時)。夏は知床五湖。", en: "Drift-ice season Jan-Mar early mornings (8-10). Summer for Goko." },
  },
  "富良野": {
    access:   { ja: "JR根室本線「富良野駅」より中富良野駅まで7分。ファーム富田まで徒歩7分。", en: "JR Furano Station → Naka-Furano (7 min). Then 7-min walk to Farm Tomita." },
    parking:  { ja: "ファーム富田無料駐車場大規模 (500台)。", en: "Large free parking at Farm Tomita (500 cars)." },
    fee:      { ja: "無料。", en: "Free." },
    duration: { ja: "ファーム富田で1-2時間。周辺花畑巡りで半日。", en: "1-2 hr at Farm Tomita; half-day to tour nearby fields." },
    bestTime: { ja: "7月中旬-下旬の早朝 (5-7時)。", en: "Mid-to-late July early morning (5-7 a.m.)." },
  },
  "白川郷": {
    access:   { ja: "JR金沢駅・高山駅から濃飛バス1.5-2時間。冬期は予約推奨。", en: "1.5-2 hr Nohi Bus from Kanazawa or Takayama. Reservation recommended in winter." },
    parking:  { ja: "せせらぎ公園駐車場有料 (普通車1,000円)。", en: "Seseragi Park lot (¥1,000 per car)." },
    fee:      { ja: "集落散策無料。荻町城跡展望台への送迎バス200円。", en: "Free village walk. Shuttle to observatory ¥200." },
    duration: { ja: "3-4時間 (展望台含む)。", en: "3-4 hr including observatory." },
    bestTime: { ja: "1-2月の冬季ライトアップ要予約。早朝の雪景色。", en: "Winter light-up Jan-Feb requires advance booking. Snowy mornings are best." },
  },
  "清水寺": {
    access:   { ja: "京都市バス「五条坂」または「清水道」下車徒歩10分。", en: "10-min walk from «Gojozaka» or «Kiyomizu-michi» bus stops." },
    parking:  { ja: "市営駐車場有料 (1日1,000円)。混雑期は徒歩アクセス推奨。", en: "Public lot ¥1,000/day. Walking recommended during peak seasons." },
    fee:      { ja: "本堂参拝500円。秋の特別拝観は別途。", en: "Main hall ¥500. Autumn special viewing extra fee." },
    duration: { ja: "境内全体で1.5-2時間。", en: "1.5-2 hr for the full grounds." },
    bestTime: { ja: "11月中旬-12月初旬の紅葉ライトアップ (17:30-21時)。", en: "Mid-Nov to early Dec autumn illumination (17:30-21)." },
  },
  "金閣寺": {
    access:   { ja: "京都市バス「金閣寺道」下車徒歩3分。", en: "3-min walk from «Kinkakuji-michi» bus stop." },
    parking:  { ja: "有料駐車場あり (40分300円)。", en: "Paid parking (¥300/40 min)." },
    fee:      { ja: "拝観料500円 (大人)。", en: "Admission ¥500 (adult)." },
    duration: { ja: "30-45分。", en: "30-45 min." },
    bestTime: { ja: "9時開門直後の朝。冬の雪景色は別格。", en: "Right at 9 a.m. opening. Winter snow scenes are unrivaled." },
  },
  "平等院鳳凰堂": {
    access:   { ja: "JR奈良線「宇治駅」より徒歩10分。京阪宇治駅も近い。", en: "10-min walk from JR Uji Station. Keihan Uji Station also nearby." },
    parking:  { ja: "周辺民営駐車場 (1日500-700円)。", en: "Private lots ¥500-700/day." },
    fee:      { ja: "庭園拝観600円。鳳凰堂内部別途300円 (要予約)。", en: "Garden ¥600. Interior of Phoenix Hall additional ¥300 (reservation required)." },
    duration: { ja: "1時間。鳳翔館博物館も含めて1.5時間。", en: "1 hr; 1.5 hr including the Hosho-kan museum." },
    bestTime: { ja: "8:30開門直後の鏡面朝。", en: "Right after 8:30 opening for mirror-still water." },
  },
  "東福寺": {
    access:   { ja: "JR奈良線・京阪本線「東福寺駅」より徒歩10分。", en: "10-min walk from Tofuku-ji Station (JR Nara Line / Keihan)." },
    parking:  { ja: "通常時は無料、紅葉期は閉鎖。公共交通機関推奨。", en: "Free in normal times; closed during autumn — use public transit." },
    fee:      { ja: "通天橋・本坊500円。秋季のみ。", en: "Tsutenkyo bridge + abbot's hall ¥500. Autumn season only." },
    duration: { ja: "1-1.5時間。", en: "1-1.5 hr." },
    bestTime: { ja: "11月20日-12月5日の早朝 (8:30開門)。", en: "Nov 20 - Dec 5, right at 8:30 opening." },
  },
  "伊勢神宮": {
    access:   { ja: "近鉄「伊勢市駅」または「宇治山田駅」。外宮は徒歩5分、内宮はバス20分。", en: "Kintetsu Iseshi or Ujiyamada Station. Geku is 5-min walk; Naiku is 20-min bus." },
    parking:  { ja: "外宮・内宮ともに無料駐車場大規模。連休は混雑。", en: "Large free parking at both Geku and Naiku. Crowded on holidays." },
    fee:      { ja: "参拝無料。", en: "Free admission." },
    duration: { ja: "外宮+内宮+おかげ横丁で半日。", en: "Half day for Geku + Naiku + Okage Yokocho." },
    bestTime: { ja: "早朝6時の開門直後。新月の朝は神聖。", en: "Right at 6 a.m. opening. New moon mornings feel sacred." },
  },
  "姫路城": {
    access:   { ja: "JR姫路駅より徒歩15分。新大阪から新幹線50分。", en: "15-min walk from JR Himeji Station. 50 min by Shinkansen from Shin-Osaka." },
    parking:  { ja: "城周辺有料駐車場多数 (1日600-1,000円)。", en: "Multiple paid lots ¥600-1,000/day." },
    fee:      { ja: "登閣1,000円。好古園との共通券1,050円。", en: "Castle ¥1,000. Combined with Kokoen ¥1,050." },
    duration: { ja: "天守内部含めて2時間。桜期は3時間。", en: "2 hr including keep interior; 3 hr in cherry season." },
    bestTime: { ja: "4月初旬の桜と9時開門前の到着。", en: "Early April cherry blossoms; arrive before 9 a.m. opening." },
  },
  "父母ヶ浜": {
    access:   { ja: "JR予讃線「詫間駅」よりタクシー15分。高松空港から車1時間。", en: "15-min taxi from JR Takuma Station. 1 hr drive from Takamatsu Airport." },
    parking:  { ja: "有料駐車場500円。日没3時間前で満車になる週末あり。", en: "Paid parking ¥500. Fills 3 hr before sunset on weekends." },
    fee:      { ja: "ビーチ無料。", en: "Free beach access." },
    duration: { ja: "夕暮れ撮影で1.5-2時間。", en: "1.5-2 hr for sunset shoot." },
    bestTime: { ja: "干潮+日没+無風の重なる日 (公式カレンダーで確認)。", en: "Days when low tide + sunset + windless align (check official calendar)." },
  },
  "宮古島": {
    access:   { ja: "宮古空港 (那覇から55分、東京から3時間)。レンタカーで島内移動。", en: "Miyako Airport (55 min from Naha, 3 hr from Tokyo). Rental car for getting around." },
    parking:  { ja: "主要観光地は無料駐車場完備。", en: "Free parking at most major spots." },
    fee:      { ja: "無料。レンタカー1日4,000円〜。", en: "Free. Rental cars from ¥4,000/day." },
    duration: { ja: "島一周で2-3日。", en: "2-3 days to circle the island." },
    bestTime: { ja: "5-9月の10-14時 (海の透明度ピーク)。", en: "May-September, 10-14 (peak water clarity)." },
  },
  "道後温泉": {
    access:   { ja: "JR松山駅から伊予鉄道「道後温泉駅」徒歩2分。", en: "Take Iyotetsu tram to Dogo Onsen Station (2-min walk)." },
    parking:  { ja: "市営駐車場400円/時間。混雑期は遠方推奨。", en: "Municipal lot ¥400/hr. Park further out during peaks." },
    fee:      { ja: "本館入浴460円。", en: "Honkan bath admission ¥460." },
    duration: { ja: "入浴+周辺撮影で2時間。", en: "2 hr for bath + photography." },
    bestTime: { ja: "夕方の建物撮影と夜のライトアップ。", en: "Late afternoon for the building, plus evening illumination." },
  },
  "別府": {
    access:   { ja: "JR別府駅よりバス20分で鉄輪温泉 (地獄巡り起点)。", en: "20-min bus from JR Beppu Station to Kannawa Onsen (Hells tour base)." },
    parking:  { ja: "各地獄に無料駐車場。共通券利用者は推奨。", en: "Free parking at each Hell. Recommended for combo-ticket holders." },
    fee:      { ja: "地獄巡り共通券2,200円 (7地獄)、個別450円。", en: "Hells Tour combo ¥2,200 (7 Hells); individual ¥450." },
    duration: { ja: "全7地獄巡りで2-3時間。", en: "2-3 hr for all 7 Hells." },
    bestTime: { ja: "冬期の早朝 (湯けむり最大)。", en: "Winter mornings for maximum steam." },
  },
};

export const getLocInfo = (locJp) => LOC_INFO[locJp] || null;
