/**
 * UI label strings for SEO-augmenting page sections rendered server-side
 * (separate from the in-app `TR` table which is consumed by client components).
 */

export const UI_STRINGS = {
  relatedGuides: {
    ja: "撮影ガイド", en: "Photography Guides", zh: "摄影指南", "zh-tw": "攝影指南", ko: "촬영 가이드",
    es: "Guías de fotografía", fr: "Guides de photographie", de: "Fotografie-Guides", pt: "Guias de fotografia",
    it: "Guide di fotografia", ru: "Фото-гайды", ar: "أدلة التصوير", hi: "फोटोग्राफी गाइड",
    th: "คู่มือถ่ายภาพ", vi: "Hướng dẫn chụp ảnh", id: "Panduan Fotografi", tr: "Fotoğraf Rehberleri",
    nl: "Fotografiegidsen", pl: "Przewodniki fotograficzne", sv: "Fotoguider", fa: "راهنماهای عکاسی",
    he: "מדריכי צילום", bn: "ফটোগ্রাফি গাইড", tl: "Mga Gabay sa Photography", uk: "Фото-гіди",
  },
  aboutThisLocation: {
    ja: "この撮影地について", en: "About this location", zh: "关于这个地点", "zh-tw": "關於這個地點", ko: "이 촬영지 소개",
    es: "Sobre este lugar", fr: "À propos de ce lieu", de: "Über diesen Ort", pt: "Sobre este local",
    it: "Informazioni su questo luogo", ru: "Об этом месте", ar: "حول هذا المكان", hi: "इस स्थान के बारे में",
    th: "เกี่ยวกับสถานที่นี้", vi: "Về địa điểm này", id: "Tentang lokasi ini", tr: "Bu konum hakkında",
    nl: "Over deze locatie", pl: "O tym miejscu", sv: "Om denna plats", fa: "درباره این مکان",
    he: "אודות מיקום זה", bn: "এই স্থান সম্পর্কে", tl: "Tungkol sa lokasyong ito", uk: "Про це місце",
  },
  keyFeatures: {
    ja: "撮影ポイント", en: "Key features", zh: "主要看点", "zh-tw": "主要看點", ko: "주요 포인트",
    es: "Aspectos destacados", fr: "Points forts", de: "Highlights", pt: "Destaques",
    it: "Punti salienti", ru: "Особенности", ar: "أبرز المعالم", hi: "मुख्य विशेषताएं",
    th: "จุดเด่น", vi: "Điểm nổi bật", id: "Sorotan utama", tr: "Öne çıkanlar",
    nl: "Kenmerken", pl: "Kluczowe cechy", sv: "Höjdpunkter", fa: "ویژگی‌های کلیدی",
    he: "תכונות עיקריות", bn: "মূল বৈশিষ্ট্য", tl: "Mga pangunahing tampok", uk: "Ключові особливості",
  },
  theater: {
    ja: "シアター", en: "Theater", zh: "剧场", "zh-tw": "劇場", ko: "시어터",
    es: "Teatro", fr: "Théâtre", de: "Theater", pt: "Teatro",
    it: "Teatro", ru: "Театр", ar: "مسرح", hi: "थिएटर",
    th: "โรงละคร", vi: "Trình chiếu", id: "Teater", tr: "Tiyatro",
    nl: "Theater", pl: "Teatr", sv: "Teater", fa: "تئاتر",
    he: "תיאטרון", bn: "থিয়েটার", tl: "Teatro", uk: "Театр",
  },
};

/* ⑦ 見た目から探す */
UI_STRINGS.byLook = {"ja":"見た目から","en":"By look","zh":"按画面内容","zh-tw":"依畫面內容","ko":"화면 내용으로","es":"Por aspecto","fr":"Par aspect","de":"Nach Bildinhalt","pt":"Pela aparência","it":"Per aspetto","ru":"По содержанию","ar":"حسب المظهر","hi":"दिखावट से","th":"จากภาพ","vi":"Theo hình ảnh","id":"Dari tampilan","tr":"Görünüme göre","nl":"Op beeld","pl":"Po wyglądzie","sv":"Efter utseende","fa":"بر اساس ظاهر","he":"לפי המראה","bn":"চেহারা অনুসারে","tl":"Ayon sa hitsura","uk":"За виглядом"};
UI_STRINGS.lookPlaceholder = {"ja":"霧、夕焼け、星空…","en":"mist, sunset, starry sky…","zh":"雾、日落、星空…","zh-tw":"霧、日落、星空…","ko":"안개, 노을, 별하늘…","es":"niebla, atardecer, cielo estrellado…","fr":"brume, coucher de soleil, ciel étoilé…","de":"Nebel, Sonnenuntergang, Sternenhimmel…","pt":"névoa, pôr do sol, céu estrelado…","it":"nebbia, tramonto, cielo stellato…","ru":"туман, закат, звёздное небо…","ar":"ضباب، غروب، سماء مرصعة بالنجوم…","hi":"कोहरा, सूर्यास्त, तारों भरा आकाश…","th":"หมอก พระอาทิตย์ตก ท้องฟ้าเต็มไปด้วยดาว…","vi":"sương mù, hoàng hôn, bầu trời đầy sao…","id":"kabut, matahari terbenam, langit berbintang…","tr":"sis, gün batımı, yıldızlı gökyüzü…","nl":"mist, zonsondergang, sterrenhemel…","pl":"mgła, zachód słońca, rozgwieżdżone niebo…","sv":"dimma, solnedgång, stjärnhimmel…","fa":"مه، غروب آفتاب، آسمان پرستاره…","he":"ערפל, שקיעה, שמיים זרועי כוכבים…","bn":"কুয়াশা, সূর্যাস্ত, তারাভরা আকাশ…","tl":"hamog, paglubog ng araw, mabituing langit…","uk":"туман, захід сонця, зоряне небо…"};
UI_STRINGS.lookNoMatch = {"ja":"この言葉に当たる見た目はありません","en":"No matching look for that word","zh":"没有与该词对应的画面内容","zh-tw":"沒有與該詞對應的畫面內容","ko":"그 단어에 해당하는 화면 내용이 없습니다","es":"Ninguna coincidencia para esa palabra","fr":"Aucune correspondance pour ce mot","de":"Kein passender Bildinhalt zu diesem Wort","pt":"Nenhuma correspondência para essa palavra","it":"Nessuna corrispondenza per questa parola","ru":"Для этого слова нет совпадений","ar":"لا يوجد مظهر مطابق لهذه الكلمة","hi":"इस शब्द के लिए कोई मिलान नहीं","th":"ไม่พบภาพที่ตรงกับคำนี้","vi":"Không có hình ảnh khớp với từ này","id":"Tidak ada yang cocok dengan kata itu","tr":"Bu kelimeye uyan görünüm yok","nl":"Geen overeenkomend beeld voor dat woord","pl":"Brak dopasowania do tego słowa","sv":"Ingen matchning för det ordet","fa":"برای این واژه موردی یافت نشد","he":"אין התאמה למילה הזו","bn":"এই শব্দের সাথে কিছু মেলেনি","tl":"Walang tugma sa salitang iyon","uk":"Немає відповідників для цього слова"};
UI_STRINGS.lookUnavailable = {"ja":"見た目の検索を読み込めませんでした","en":"Could not load look search","zh":"无法加载画面内容检索","zh-tw":"無法載入畫面內容檢索","ko":"화면 내용 검색을 불러오지 못했습니다","es":"No se pudo cargar la búsqueda por aspecto","fr":"Impossible de charger la recherche par aspect","de":"Bildinhalt-Suche konnte nicht geladen werden","pt":"Não foi possível carregar a busca por aparência","it":"Impossibile caricare la ricerca per aspetto","ru":"Не удалось загрузить поиск по содержанию","ar":"تعذر تحميل البحث حسب المظهر","hi":"दिखावट खोज लोड नहीं हो सकी","th":"โหลดการค้นหาจากภาพไม่สำเร็จ","vi":"Không tải được tìm kiếm theo hình ảnh","id":"Gagal memuat pencarian tampilan","tr":"Görünüme göre arama yüklenemedi","nl":"Beeldzoeken kon niet worden geladen","pl":"Nie udało się wczytać wyszukiwania po wyglądzie","sv":"Kunde inte ladda utseendesökning","fa":"جست‌وجوی ظاهری بارگذاری نشد","he":"לא ניתן לטעון חיפוש לפי מראה","bn":"চেহারা অনুসন্ধান লোড করা যায়নি","tl":"Hindi ma-load ang paghahanap ayon sa hitsura","uk":"Не вдалося завантажити пошук за виглядом"};

export function ui(key, lang) {
  const m = UI_STRINGS[key];
  if (!m) return key;
  return m[lang] || m.en || key;
}

/* ①②⑤ で追加した UI 文言 (25言語)。既存の UI_STRINGS と同じ方式。 */
UI_STRINGS.explore = { "ja": "探す", "en": "Explore", "zh": "探索", "zh-tw": "探索", "ko": "탐색", "es": "Explorar", "fr": "Explorer", "de": "Entdecken", "pt": "Explorar", "it": "Esplora", "ru": "Обзор", "ar": "استكشاف", "hi": "खोजें", "th": "สำรวจ", "vi": "Khám phá", "id": "Jelajahi", "tr": "Keşfet", "nl": "Ontdekken", "pl": "Odkrywaj", "sv": "Utforska", "fa": "کاوش", "he": "גלה", "bn": "অন্বেষণ", "tl": "Tuklasin", "uk": "Огляд" };
UI_STRINGS.collections = { "ja": "コレクション", "en": "Collections", "zh": "合集", "zh-tw": "合集", "ko": "컬렉션", "es": "Colecciones", "fr": "Collections", "de": "Kollektionen", "pt": "Coleções", "it": "Collezioni", "ru": "Коллекции", "ar": "المجموعات", "hi": "संग्रह", "th": "คอลเลกชัน", "vi": "Bộ sưu tập", "id": "Koleksi", "tr": "Koleksiyonlar", "nl": "Collecties", "pl": "Kolekcje", "sv": "Samlingar", "fa": "مجموعه‌ها", "he": "אוספים", "bn": "সংগ্রহ", "tl": "Mga Koleksyon", "uk": "Колекції" };
UI_STRINGS.search = { "ja": "検索", "en": "Search", "zh": "搜索", "zh-tw": "搜尋", "ko": "검색", "es": "Buscar", "fr": "Rechercher", "de": "Suche", "pt": "Buscar", "it": "Cerca", "ru": "Поиск", "ar": "بحث", "hi": "खोज", "th": "ค้นหา", "vi": "Tìm kiếm", "id": "Cari", "tr": "Ara", "nl": "Zoeken", "pl": "Szukaj", "sv": "Sök", "fa": "جستجو", "he": "חיפוש", "bn": "অনুসন্ধান", "tl": "Maghanap", "uk": "Пошук" };
UI_STRINGS.random = { "ja": "ランダム", "en": "Random", "zh": "随机", "zh-tw": "隨機", "ko": "랜덤", "es": "Aleatorio", "fr": "Aléatoire", "de": "Zufällig", "pt": "Aleatório", "it": "Casuale", "ru": "Случайно", "ar": "عشوائي", "hi": "यादृच्छिक", "th": "สุ่ม", "vi": "Ngẫu nhiên", "id": "Acak", "tr": "Rastgele", "nl": "Willekeurig", "pl": "Losowo", "sv": "Slumpmässigt", "fa": "تصادفی", "he": "אקראי", "bn": "এলোমেলো", "tl": "Random", "uk": "Випадково" };
UI_STRINGS.contact = { "ja": "お問い合わせ", "en": "Contact", "zh": "联系", "zh-tw": "聯絡", "ko": "문의", "es": "Contacto", "fr": "Contact", "de": "Kontakt", "pt": "Contato", "it": "Contatti", "ru": "Контакты", "ar": "اتصل بنا", "hi": "संपर्क", "th": "ติดต่อ", "vi": "Liên hệ", "id": "Kontak", "tr": "İletişim", "nl": "Contact", "pl": "Kontakt", "sv": "Kontakt", "fa": "تماس", "he": "צור קשר", "bn": "যোগাযোগ", "tl": "Kontak", "uk": "Контакти" };
UI_STRINGS.menu = { "ja": "メニュー", "en": "Menu", "zh": "菜单", "zh-tw": "選單", "ko": "메뉴", "es": "Menú", "fr": "Menu", "de": "Menü", "pt": "Menu", "it": "Menu", "ru": "Меню", "ar": "القائمة", "hi": "मेन्यू", "th": "เมนู", "vi": "Menu", "id": "Menu", "tr": "Menü", "nl": "Menu", "pl": "Menu", "sv": "Meny", "fa": "منو", "he": "תפריט", "bn": "মেনু", "tl": "Menu", "uk": "Меню" };
UI_STRINGS.close = { "ja": "閉じる", "en": "Close", "zh": "关闭", "zh-tw": "關閉", "ko": "닫기", "es": "Cerrar", "fr": "Fermer", "de": "Schließen", "pt": "Fechar", "it": "Chiudi", "ru": "Закрыть", "ar": "إغلاق", "hi": "बंद करें", "th": "ปิด", "vi": "Đóng", "id": "Tutup", "tr": "Kapat", "nl": "Sluiten", "pl": "Zamknij", "sv": "Stäng", "fa": "بستن", "he": "סגור", "bn": "বন্ধ", "tl": "Isara", "uk": "Закрити" };
UI_STRINGS.language = { "ja": "言語", "en": "Language", "zh": "语言", "zh-tw": "語言", "ko": "언어", "es": "Idioma", "fr": "Langue", "de": "Sprache", "pt": "Idioma", "it": "Lingua", "ru": "Язык", "ar": "اللغة", "hi": "भाषा", "th": "ภาษา", "vi": "Ngôn ngữ", "id": "Bahasa", "tr": "Dil", "nl": "Taal", "pl": "Język", "sv": "Språk", "fa": "زبان", "he": "שפה", "bn": "ভাষা", "tl": "Wika", "uk": "Мова" };
UI_STRINGS.findPhotos = { "ja": "写真を探す", "en": "Find photos", "zh": "查找照片", "zh-tw": "尋找照片", "ko": "사진 찾기", "es": "Buscar fotos", "fr": "Trouver des photos", "de": "Fotos finden", "pt": "Encontrar fotos", "it": "Trova foto", "ru": "Найти фото", "ar": "ابحث عن الصور", "hi": "फ़ोटो खोजें", "th": "ค้นหารูปภาพ", "vi": "Tìm ảnh", "id": "Cari foto", "tr": "Fotoğraf bul", "nl": "Fotos vinden", "pl": "Znajdź zdjęcia", "sv": "Hitta foton", "fa": "یافتن عکس", "he": "מצא תמונות", "bn": "ছবি খুঁজুন", "tl": "Maghanap ng litrato", "uk": "Знайти фото" };
UI_STRINGS.byRegion = { "ja": "地域から", "en": "By region", "zh": "按地区", "zh-tw": "按地區", "ko": "지역으로", "es": "Por región", "fr": "Par région", "de": "Nach Region", "pt": "Por região", "it": "Per regione", "ru": "По регионам", "ar": "حسب المنطقة", "hi": "क्षेत्र से", "th": "ตามภูมิภาค", "vi": "Theo vùng", "id": "Menurut wilayah", "tr": "Bölgeye göre", "nl": "Per regio", "pl": "Wedługregionu", "sv": "Efter region", "fa": "بر اساس منطقه", "he": "לפי אזור", "bn": "অঞ্চল অনুসারে", "tl": "Ayon sa rehiyon", "uk": "За регіоном" };
UI_STRINGS.byColor = { "ja": "色から", "en": "By colour", "zh": "按颜色", "zh-tw": "按顏色", "ko": "색으로", "es": "Por color", "fr": "Par couleur", "de": "Nach Farbe", "pt": "Por cor", "it": "Per colore", "ru": "По цвету", "ar": "حسب اللون", "hi": "रंग से", "th": "ตามสี", "vi": "Theo màu", "id": "Menurut warna", "tr": "Renge göre", "nl": "Op kleur", "pl": "Według koloru", "sv": "Efter färg", "fa": "بر اساس رنگ", "he": "לפי צבע", "bn": "রঙ অনুসারে", "tl": "Ayon sa kulay", "uk": "За кольором" };
UI_STRINGS.noResults = { "ja": "該当する写真がありません", "en": "No photos match", "zh": "没有匹配的照片", "zh-tw": "沒有符合的照片", "ko": "일치하는 사진이 없습니다", "es": "No hay fotos", "fr": "Aucune photo", "de": "Keine Fotos gefunden", "pt": "Nenhuma foto", "it": "Nessuna foto", "ru": "Нет фотографий", "ar": "لا توجد صور", "hi": "कोई फ़ोटो नहीं", "th": "ไม่พบรูปภาพ", "vi": "Không có ảnh", "id": "Tidak ada foto", "tr": "Fotoğraf yok", "nl": "Geen fotos", "pl": "Brak zdjęć", "sv": "Inga foton", "fa": "عکسی یافت نشد", "he": "אין תמונות", "bn": "কোনো ছবি নেই", "tl": "Walang litrato", "uk": "Немає фото" };
UI_STRINGS.clearColor = { "ja": "色の選択を解除", "en": "Clear colour", "zh": "清除颜色", "zh-tw": "清除顏色", "ko": "색상 해제", "es": "Quitar color", "fr": "Effacer la couleur", "de": "Farbe zurücksetzen", "pt": "Limpar cor", "it": "Rimuovi colore", "ru": "Сбросить цвет", "ar": "مسح اللون", "hi": "रंग हटाएं", "th": "ล้างสี", "vi": "Bỏ chọn màu", "id": "Hapus warna", "tr": "Rengi temizle", "nl": "Kleur wissen", "pl": "Wyczyść kolor", "sv": "Rensa färg", "fa": "پاک کردن رنگ", "he": "נקה צבע", "bn": "রঙ মুছুন", "tl": "Alisin ang kulay", "uk": "Скинути колір" };
UI_STRINGS.loading = { "ja": "読み込み中", "en": "Loading", "zh": "加载中", "zh-tw": "載入中", "ko": "불러오는 중", "es": "Cargando", "fr": "Chargement", "de": "Wird geladen", "pt": "Carregando", "it": "Caricamento", "ru": "Загрузка", "ar": "جارٍ التحميل", "hi": "लोड हो रहा है", "th": "กำลังโหลด", "vi": "Đang tải", "id": "Memuat", "tr": "Yükleniyor", "nl": "Laden", "pl": "Ładowanie", "sv": "Laddar", "fa": "در حال بارگذاری", "he": "טוען", "bn": "লোড হচ্ছে", "tl": "Naglo-load", "uk": "Завантаження" };

/* ②③④⑤⑦⑧ で追加した UI 文言 (25言語)。既存の UI_STRINGS と同じ方式。
   画面に文字を増やすためではなく、操作名を各言語で持つためのもの。 */
UI_STRINGS.newArrivals = {"ja":"新着","en":"New arrivals","zh":"最新添加","zh-tw":"最新新增","ko":"새로 추가됨","es":"Novedades","fr":"Nouveautés","de":"Neu hinzugefügt","pt":"Novidades","it":"Novità","ru":"Новые","ar":"الأحدث إضافة","hi":"नए जोड़े गए","th":"มาใหม่","vi":"Mới thêm","id":"Baru ditambahkan","tr":"Yeni eklenenler","nl":"Nieuw toegevoegd","pl":"Nowości","sv":"Nytt","fa":"تازه‌ها","he":"חדשים","bn":"নতুন যোগ","tl":"Bago","uk":"Нові"};
UI_STRINGS.filter = {"ja":"絞り込み","en":"Filter","zh":"筛选","zh-tw":"篩選","ko":"필터","es":"Filtrar","fr":"Filtrer","de":"Filter","pt":"Filtrar","it":"Filtra","ru":"Фильтр","ar":"تصفية","hi":"फ़िल्टर","th":"ตัวกรอง","vi":"Lọc","id":"Saring","tr":"Filtre","nl":"Filter","pl":"Filtr","sv":"Filter","fa":"فیلتر","he":"סינון","bn":"ফিল্টার","tl":"Salain","uk":"Фільтр"};
UI_STRINGS.clearFilter = {"ja":"条件を解除","en":"Clear","zh":"清除","zh-tw":"清除","ko":"해제","es":"Borrar","fr":"Effacer","de":"Zurücksetzen","pt":"Limpar","it":"Azzera","ru":"Сбросить","ar":"مسح","hi":"हटाएं","th":"ล้าง","vi":"Xóa","id":"Hapus","tr":"Temizle","nl":"Wissen","pl":"Wyczyść","sv":"Rensa","fa":"پاک کردن","he":"נקה","bn":"মুছুন","tl":"Alisin","uk":"Скинути"};
UI_STRINGS.theme = {"ja":"テーマ","en":"Theme","zh":"主题","zh-tw":"主題","ko":"테마","es":"Tema","fr":"Thème","de":"Thema","pt":"Tema","it":"Tema","ru":"Тема","ar":"الموضوع","hi":"थीम","th":"ธีม","vi":"Chủ đề","id":"Tema","tr":"Tema","nl":"Thema","pl":"Temat","sv":"Tema","fa":"موضوع","he":"נושא","bn":"থিম","tl":"Tema","uk":"Тема"};
UI_STRINGS.region = {"ja":"地域","en":"Region","zh":"地区","zh-tw":"地區","ko":"지역","es":"Región","fr":"Région","de":"Region","pt":"Região","it":"Regione","ru":"Регион","ar":"المنطقة","hi":"क्षेत्र","th":"ภูมิภาค","vi":"Vùng","id":"Wilayah","tr":"Bölge","nl":"Regio","pl":"Region","sv":"Region","fa":"منطقه","he":"אזור","bn":"অঞ্চল","tl":"Rehiyon","uk":"Регіон"};
UI_STRINGS.favorite = {"ja":"お気に入りに追加","en":"Add to favourites","zh":"加入收藏","zh-tw":"加入收藏","ko":"즐겨찾기에 추가","es":"Añadir a favoritos","fr":"Ajouter aux favoris","de":"Zu Favoriten hinzufügen","pt":"Adicionar aos favoritos","it":"Aggiungi ai preferiti","ru":"В избранное","ar":"إضافة إلى المفضلة","hi":"पसंदीदा में जोड़ें","th":"เพิ่มในรายการโปรด","vi":"Thêm vào yêu thích","id":"Tambah ke favorit","tr":"Favorilere ekle","nl":"Aan favorieten toevoegen","pl":"Dodaj do ulubionych","sv":"Lägg till i favoriter","fa":"افزودن به علاقه‌مندی‌ها","he":"הוסף למועדפים","bn":"প্রিয়তে যোগ করুন","tl":"Idagdag sa paborito","uk":"Додати в обране"};
UI_STRINGS.unfavorite = {"ja":"お気に入りから削除","en":"Remove from favourites","zh":"取消收藏","zh-tw":"取消收藏","ko":"즐겨찾기에서 제거","es":"Quitar de favoritos","fr":"Retirer des favoris","de":"Aus Favoriten entfernen","pt":"Remover dos favoritos","it":"Rimuovi dai preferiti","ru":"Убрать из избранного","ar":"إزالة من المفضلة","hi":"पसंदीदा से हटाएं","th":"นำออกจากรายการโปรด","vi":"Bỏ khỏi yêu thích","id":"Hapus dari favorit","tr":"Favorilerden çıkar","nl":"Uit favorieten verwijderen","pl":"Usuń z ulubionych","sv":"Ta bort från favoriter","fa":"حذف از علاقه‌مندی‌ها","he":"הסר מהמועדפים","bn":"প্রিয় থেকে সরান","tl":"Alisin sa paborito","uk":"Прибрати з обраного"};
UI_STRINGS.favorites = {"ja":"お気に入り","en":"Favourites","zh":"收藏","zh-tw":"收藏","ko":"즐겨찾기","es":"Favoritos","fr":"Favoris","de":"Favoriten","pt":"Favoritos","it":"Preferiti","ru":"Избранное","ar":"المفضلة","hi":"पसंदीदा","th":"รายการโปรด","vi":"Yêu thích","id":"Favorit","tr":"Favoriler","nl":"Favorieten","pl":"Ulubione","sv":"Favoriter","fa":"علاقه‌مندی‌ها","he":"מועדפים","bn":"প্রিয়","tl":"Mga paborito","uk":"Обране"};
UI_STRINGS.recentlyViewed = {"ja":"最近見た写真","en":"Recently viewed","zh":"最近浏览","zh-tw":"最近瀏覽","ko":"최근 본 사진","es":"Vistas recientemente","fr":"Vues récemment","de":"Zuletzt angesehen","pt":"Vistas recentemente","it":"Viste di recente","ru":"Недавно просмотренные","ar":"شوهدت مؤخرًا","hi":"हाल में देखे गए","th":"ดูล่าสุด","vi":"Đã xem gần đây","id":"Baru dilihat","tr":"Son görüntülenenler","nl":"Recent bekeken","pl":"Ostatnio oglądane","sv":"Nyligen visade","fa":"اخیراً دیده‌شده","he":"נצפו לאחרונה","bn":"সম্প্রতি দেখা","tl":"Kamakailang tiningnan","uk":"Нещодавно переглянуті"};
UI_STRINGS.clearAll = {"ja":"すべて消す","en":"Clear all","zh":"全部清除","zh-tw":"全部清除","ko":"모두 지우기","es":"Borrar todo","fr":"Tout effacer","de":"Alle löschen","pt":"Limpar tudo","it":"Cancella tutto","ru":"Очистить всё","ar":"مسح الكل","hi":"सभी हटाएं","th":"ล้างทั้งหมด","vi":"Xóa tất cả","id":"Hapus semua","tr":"Tümünü temizle","nl":"Alles wissen","pl":"Wyczyść wszystko","sv":"Rensa allt","fa":"پاک کردن همه","he":"נקה הכל","bn":"সব মুছুন","tl":"Alisin lahat","uk":"Очистити все"};
UI_STRINGS.storedInThisBrowser = {"ja":"このブラウザに保存","en":"Saved in this browser","zh":"保存在此浏览器","zh-tw":"儲存在此瀏覽器","ko":"이 브라우저에 저장","es":"Guardado en este navegador","fr":"Enregistré dans ce navigateur","de":"In diesem Browser gespeichert","pt":"Salvo neste navegador","it":"Salvato in questo browser","ru":"Сохранено в этом браузере","ar":"محفوظ في هذا المتصفح","hi":"इस ब्राउज़र में सहेजा गया","th":"บันทึกในเบราว์เซอร์นี้","vi":"Lưu trong trình duyệt này","id":"Disimpan di peramban ini","tr":"Bu tarayıcıda kayıtlı","nl":"Opgeslagen in deze browser","pl":"Zapisane w tej przeglądarce","sv":"Sparat i denna webbläsare","fa":"ذخیره در همین مرورگر","he":"נשמר בדפדפן זה","bn":"এই ব্রাউজারে সংরক্ষিত","tl":"Nakaimbak sa browser na ito","uk":"Збережено в цьому браузері"};
UI_STRINGS.share = {"ja":"共有","en":"Share","zh":"分享","zh-tw":"分享","ko":"공유","es":"Compartir","fr":"Partager","de":"Teilen","pt":"Compartilhar","it":"Condividi","ru":"Поделиться","ar":"مشاركة","hi":"साझा करें","th":"แชร์","vi":"Chia sẻ","id":"Bagikan","tr":"Paylaş","nl":"Delen","pl":"Udostępnij","sv":"Dela","fa":"اشتراک‌گذاری","he":"שתף","bn":"শেয়ার","tl":"Ibahagi","uk":"Поділитися"};
UI_STRINGS.linkCopied = {"ja":"リンクをコピーしました","en":"Link copied","zh":"链接已复制","zh-tw":"連結已複製","ko":"링크를 복사했습니다","es":"Enlace copiado","fr":"Lien copié","de":"Link kopiert","pt":"Link copiado","it":"Link copiato","ru":"Ссылка скопирована","ar":"تم نسخ الرابط","hi":"लिंक कॉपी हो गया","th":"คัดลอกลิงก์แล้ว","vi":"Đã sao chép liên kết","id":"Tautan disalin","tr":"Bağlantı kopyalandı","nl":"Link gekopieerd","pl":"Skopiowano link","sv":"Länk kopierad","fa":"پیوند کپی شد","he":"הקישור הועתק","bn":"লিঙ্ক কপি হয়েছে","tl":"Nakopya ang link","uk":"Посилання скопійовано"};
UI_STRINGS.copyFailed = {"ja":"コピーできませんでした","en":"Could not copy","zh":"无法复制","zh-tw":"無法複製","ko":"복사하지 못했습니다","es":"No se pudo copiar","fr":"Copie impossible","de":"Kopieren fehlgeschlagen","pt":"Não foi possível copiar","it":"Impossibile copiare","ru":"Не удалось скопировать","ar":"تعذّر النسخ","hi":"कॉपी नहीं हो सका","th":"คัดลอกไม่สำเร็จ","vi":"Không sao chép được","id":"Gagal menyalin","tr":"Kopyalanamadı","nl":"Kopiëren mislukt","pl":"Nie udało się skopiować","sv":"Kunde inte kopiera","fa":"کپی نشد","he":"ההעתקה נכשלה","bn":"কপি করা যায়নি","tl":"Hindi nakopya","uk":"Не вдалося скопіювати"};
UI_STRINGS.askAboutPhoto = {"ja":"この写真について問い合わせる","en":"Ask about this photo","zh":"咨询这张照片","zh-tw":"詢問這張照片","ko":"이 사진에 대해 문의","es":"Preguntar sobre esta foto","fr":"Question sur cette photo","de":"Zu diesem Foto anfragen","pt":"Perguntar sobre esta foto","it":"Chiedi info su questa foto","ru":"Спросить об этом фото","ar":"استفسر عن هذه الصورة","hi":"इस फ़ोटो के बारे में पूछें","th":"สอบถามเกี่ยวกับภาพนี้","vi":"Hỏi về ảnh này","id":"Tanya tentang foto ini","tr":"Bu fotoğraf hakkında sor","nl":"Vraag over deze foto","pl":"Zapytaj o to zdjęcie","sv":"Fråga om detta foto","fa":"درباره این عکس بپرسید","he":"שאל על תמונה זו","bn":"এই ছবি সম্পর্কে জিজ্ঞাসা","tl":"Magtanong tungkol sa larawang ito","uk":"Запитати про це фото"};
UI_STRINGS.photoInQuestion = {"ja":"対象の写真","en":"Photo in question","zh":"相关照片","zh-tw":"相關照片","ko":"대상 사진","es":"Foto en cuestión","fr":"Photo concernée","de":"Betreffendes Foto","pt":"Foto em questão","it":"Foto in questione","ru":"Фото","ar":"الصورة المعنية","hi":"संबंधित फ़ोटो","th":"ภาพที่เกี่ยวข้อง","vi":"Ảnh liên quan","id":"Foto terkait","tr":"İlgili fotoğraf","nl":"Betreffende foto","pl":"Zdjęcie","sv":"Aktuellt foto","fa":"عکس مورد نظر","he":"התמונה הנדונה","bn":"সংশ্লিষ্ট ছবি","tl":"Larawang tinutukoy","uk":"Відповідне фото"};
UI_STRINGS.previousPhoto = {"ja":"前の写真","en":"Previous photo","zh":"上一张","zh-tw":"上一張","ko":"이전 사진","es":"Foto anterior","fr":"Photo précédente","de":"Vorheriges Foto","pt":"Foto anterior","it":"Foto precedente","ru":"Предыдущее фото","ar":"الصورة السابقة","hi":"पिछली फ़ोटो","th":"ภาพก่อนหน้า","vi":"Ảnh trước","id":"Foto sebelumnya","tr":"Önceki fotoğraf","nl":"Vorige foto","pl":"Poprzednie zdjęcie","sv":"Föregående foto","fa":"عکس قبلی","he":"התמונה הקודמת","bn":"আগের ছবি","tl":"Nakaraang larawan","uk":"Попереднє фото"};
UI_STRINGS.nextPhoto = {"ja":"次の写真","en":"Next photo","zh":"下一张","zh-tw":"下一張","ko":"다음 사진","es":"Foto siguiente","fr":"Photo suivante","de":"Nächstes Foto","pt":"Próxima foto","it":"Foto successiva","ru":"Следующее фото","ar":"الصورة التالية","hi":"अगली फ़ोटो","th":"ภาพถัดไป","vi":"Ảnh tiếp theo","id":"Foto berikutnya","tr":"Sonraki fotoğraf","nl":"Volgende foto","pl":"Następne zdjęcie","sv":"Nästa foto","fa":"عکس بعدی","he":"התמונה הבאה","bn":"পরের ছবি","tl":"Susunod na larawan","uk":"Наступне фото"};
UI_STRINGS.scrollLeft = {"ja":"左へスクロール","en":"Scroll left","zh":"向左滚动","zh-tw":"向左捲動","ko":"왼쪽으로 스크롤","es":"Desplazar a la izquierda","fr":"Défiler vers la gauche","de":"Nach links scrollen","pt":"Rolar para a esquerda","it":"Scorri a sinistra","ru":"Прокрутить влево","ar":"التمرير لليسار","hi":"बाईं ओर स्क्रॉल करें","th":"เลื่อนไปทางซ้าย","vi":"Cuộn sang trái","id":"Gulir ke kiri","tr":"Sola kaydır","nl":"Naar links scrollen","pl":"Przewiń w lewo","sv":"Rulla åt vänster","fa":"پیمایش به چپ","he":"גלול שמאלה","bn":"বাঁ দিকে স্ক্রল","tl":"Mag-scroll pakaliwa","uk":"Прокрутити ліворуч"};
UI_STRINGS.scrollRight = {"ja":"右へスクロール","en":"Scroll right","zh":"向右滚动","zh-tw":"向右捲動","ko":"오른쪽으로 스크롤","es":"Desplazar a la derecha","fr":"Défiler vers la droite","de":"Nach rechts scrollen","pt":"Rolar para a direita","it":"Scorri a destra","ru":"Прокрутить вправо","ar":"التمرير لليمين","hi":"दाईं ओर स्क्रॉल करें","th":"เลื่อนไปทางขวา","vi":"Cuộn sang phải","id":"Gulir ke kanan","tr":"Sağa kaydır","nl":"Naar rechts scrollen","pl":"Przewiń w prawo","sv":"Rulla åt höger","fa":"پیمایش به راست","he":"גלול ימינה","bn":"ডান দিকে স্ক্রল","tl":"Mag-scroll pakanan","uk":"Прокрутити праворуч"};
UI_STRINGS.galleryOrder = {"ja":"表示順","en":"Gallery order","zh":"排列顺序","zh-tw":"排列順序","ko":"표시 순서","es":"Orden de la galería","fr":"Ordre d affichage","de":"Anzeigereihenfolge","pt":"Ordem da galeria","it":"Ordine della galleria","ru":"Порядок показа","ar":"ترتيب العرض","hi":"प्रदर्शन क्रम","th":"ลำดับการแสดง","vi":"Thứ tự hiển thị","id":"Urutan tampilan","tr":"Görüntüleme sırası","nl":"Weergavevolgorde","pl":"Kolejność wyświetlania","sv":"Visningsordning","fa":"ترتیب نمایش","he":"סדר תצוגה","bn":"প্রদর্শনের ক্রম","tl":"Pagkakasunod-sunod","uk":"Порядок показу"};

/* ⑧ 追加の操作名 (25言語) */
UI_STRINGS.breadcrumb = {"ja":"現在位置","en":"Breadcrumb","zh":"面包屑导航","zh-tw":"麵包屑導航","ko":"현재 위치","es":"Ruta de navegación","fr":"Fil d ariane","de":"Brotkrümelnavigation","pt":"Trilha de navegação","it":"Percorso di navigazione","ru":"Навигационная цепочка","ar":"مسار التنقل","hi":"ब्रेडक्रंब","th":"เส้นทางนำทาง","vi":"Đường dẫn","id":"Tautan navigasi","tr":"Gezinti yolu","nl":"Kruimelpad","pl":"Ścieżka nawigacji","sv":"Sökväg","fa":"مسیر راهبری","he":"נתיב ניווט","bn":"ব্রেডক্রাম্ব","tl":"Breadcrumb","uk":"Навігаційний ланцюжок"};
UI_STRINGS.shuffle = {"ja":"シャッフル","en":"Shuffle","zh":"随机播放","zh-tw":"隨機播放","ko":"셔플","es":"Aleatorio","fr":"Lecture aléatoire","de":"Zufallswiedergabe","pt":"Aleatório","it":"Casuale","ru":"Перемешать","ar":"ترتيب عشوائي","hi":"शफ़ल","th":"สุ่มลำดับ","vi":"Xáo trộn","id":"Acak","tr":"Karıştır","nl":"Shuffle","pl":"Losowo","sv":"Blanda","fa":"درهم‌سازی","he":"ערבוב","bn":"শাফল","tl":"Shuffle","uk":"Перемішати"};
UI_STRINGS.backToTop = {"ja":"先頭へ戻る","en":"Back to top","zh":"返回顶部","zh-tw":"返回頂部","ko":"맨 위로","es":"Volver arriba","fr":"Retour en haut","de":"Nach oben","pt":"Voltar ao topo","it":"Torna su","ru":"Наверх","ar":"العودة إلى الأعلى","hi":"ऊपर जाएं","th":"กลับขึ้นบน","vi":"Lên đầu trang","id":"Kembali ke atas","tr":"Başa dön","nl":"Terug naar boven","pl":"Do góry","sv":"Till toppen","fa":"بازگشت به بالا","he":"חזרה למעלה","bn":"উপরে ফিরুন","tl":"Balik sa itaas","uk":"Догори"};
UI_STRINGS.dismiss = {"ja":"閉じる","en":"Dismiss","zh":"关闭提示","zh-tw":"關閉提示","ko":"닫기","es":"Descartar","fr":"Ignorer","de":"Ausblenden","pt":"Dispensar","it":"Ignora","ru":"Скрыть","ar":"تجاهل","hi":"खारिज करें","th":"ปิดข้อความ","vi":"Bỏ qua","id":"Tutup","tr":"Kapat","nl":"Sluiten","pl":"Odrzuć","sv":"Avfärda","fa":"نادیده گرفتن","he":"סגור","bn":"বন্ধ করুন","tl":"Isara","uk":"Сховати"};
UI_STRINGS.theaterMode = {"ja":"シアター表示","en":"Theater mode","zh":"剧场模式","zh-tw":"劇場模式","ko":"시어터 모드","es":"Modo teatro","fr":"Mode théâtre","de":"Theatermodus","pt":"Modo teatro","it":"Modalità teatro","ru":"Режим театра","ar":"وضع المسرح","hi":"थिएटर मोड","th":"โหมดโรงละคร","vi":"Chế độ trình chiếu","id":"Mode teater","tr":"Tiyatro modu","nl":"Theatermodus","pl":"Tryb teatru","sv":"Teaterläge","fa":"حالت تئاتر","he":"מצב תיאטרון","bn":"থিয়েটার মোড","tl":"Teatro mode","uk":"Режим театру"};

/* ⑧ 写真ページへのリンク文言 (25言語)。以前は4言語しか無く、他は英語のままだった */
UI_STRINGS.photoPage = {"ja":"写真ページ","en":"Photo page","zh":"照片页","zh-tw":"照片頁","ko":"사진 페이지","es":"Página de la foto","fr":"Page de la photo","de":"Fotoseite","pt":"Página da foto","it":"Pagina della foto","ru":"Страница фото","ar":"صفحة الصورة","hi":"फ़ोटो पेज","th":"หน้ารูปภาพ","vi":"Trang ảnh","id":"Halaman foto","tr":"Fotoğraf sayfası","nl":"Fotopagina","pl":"Strona zdjęcia","sv":"Fotosida","fa":"صفحه عکس","he":"עמוד התמונה","bn":"ছবির পাতা","tl":"Pahina ng litrato","uk":"Сторінка фото"};

/* ① 統合探索で追加した UI 文言 (25言語) */
UI_STRINGS.season = {"ja":"季節","en":"Season","zh":"季节","zh-tw":"季節","ko":"계절","es":"Estación","fr":"Saison","de":"Jahreszeit","pt":"Estação","it":"Stagione","ru":"Сезон","ar":"الفصل","hi":"मौसम","th":"ฤดูกาล","vi":"Mùa","id":"Musim","tr":"Mevsim","nl":"Seizoen","pl":"Pora roku","sv":"Årstid","fa":"فصل","he":"עונה","bn":"ঋতু","tl":"Panahon","uk":"Пора року"};
UI_STRINGS.orientation = {"ja":"写真の向き","en":"Orientation","zh":"照片方向","zh-tw":"照片方向","ko":"사진 방향","es":"Orientación","fr":"Orientation","de":"Ausrichtung","pt":"Orientação","it":"Orientamento","ru":"Ориентация","ar":"الاتجاه","hi":"दिशा","th":"แนวภาพ","vi":"Hướng ảnh","id":"Orientasi","tr":"Yönelim","nl":"Oriëntatie","pl":"Orientacja","sv":"Orientering","fa":"جهت","he":"כיוון","bn":"অভিমুখ","tl":"Oryentasyon","uk":"Орієнтація"};
UI_STRINGS.orientation_landscape = {"ja":"横","en":"Landscape","zh":"横向","zh-tw":"橫向","ko":"가로","es":"Horizontal","fr":"Paysage","de":"Querformat","pt":"Horizontal","it":"Orizzontale","ru":"Горизонтальные","ar":"أفقي","hi":"क्षैतिज","th":"แนวนอน","vi":"Ngang","id":"Mendatar","tr":"Yatay","nl":"Liggend","pl":"Poziome","sv":"Liggande","fa":"افقی","he":"לרוחב","bn":"অনুভূমিক","tl":"Pahiga","uk":"Горизонтальні"};
UI_STRINGS.orientation_portrait = {"ja":"縦","en":"Portrait","zh":"竖向","zh-tw":"豎向","ko":"세로","es":"Vertical","fr":"Portrait","de":"Hochformat","pt":"Vertical","it":"Verticale","ru":"Вертикальные","ar":"عمودي","hi":"लंबवत","th":"แนวตั้ง","vi":"Dọc","id":"Tegak","tr":"Dikey","nl":"Staand","pl":"Pionowe","sv":"Stående","fa":"عمودی","he":"לאורך","bn":"উল্লম্ব","tl":"Patayo","uk":"Вертикальні"};
UI_STRINGS.orientation_square = {"ja":"正方形","en":"Square","zh":"方形","zh-tw":"方形","ko":"정사각형","es":"Cuadrado","fr":"Carré","de":"Quadratisch","pt":"Quadrado","it":"Quadrato","ru":"Квадратные","ar":"مربع","hi":"वर्गाकार","th":"สี่เหลี่ยมจัตุรัส","vi":"Vuông","id":"Persegi","tr":"Kare","nl":"Vierkant","pl":"Kwadratowe","sv":"Kvadratiska","fa":"مربع","he":"ריבועי","bn":"বর্গাকার","tl":"Parisukat","uk":"Квадратні"};
UI_STRINGS.byDate = {"ja":"撮影日順","en":"By date","zh":"按拍摄日期","zh-tw":"按拍攝日期","ko":"촬영일순","es":"Por fecha","fr":"Par date","de":"Nach Datum","pt":"Por data","it":"Per data","ru":"По дате","ar":"حسب التاريخ","hi":"तिथि अनुसार","th":"ตามวันที่","vi":"Theo ngày","id":"Per tanggal","tr":"Tarihe göre","nl":"Op datum","pl":"Wg daty","sv":"Efter datum","fa":"بر اساس تاریخ","he":"לפי תאריך","bn":"তারিখ অনুসারে","tl":"Ayon sa petsa","uk":"За датою"};
UI_STRINGS.mapArea = {"ja":"地図の範囲","en":"Map area","zh":"地图范围","zh-tw":"地圖範圍","ko":"지도 범위","es":"Área del mapa","fr":"Zone de la carte","de":"Kartenausschnitt","pt":"Área do mapa","it":"Area della mappa","ru":"Область карты","ar":"نطاق الخريطة","hi":"मानचित्र क्षेत्र","th":"ขอบเขตแผนที่","vi":"Vùng bản đồ","id":"Area peta","tr":"Harita alanı","nl":"Kaartgebied","pl":"Obszar mapy","sv":"Kartområde","fa":"محدوده نقشه","he":"אזור המפה","bn":"মানচিত্র এলাকা","tl":"Lugar sa mapa","uk":"Область карти"};
UI_STRINGS.explorePhotos = {"ja":"写真を絞り込む","en":"Filter photos","zh":"筛选照片","zh-tw":"篩選照片","ko":"사진 필터","es":"Filtrar fotos","fr":"Filtrer les photos","de":"Fotos filtern","pt":"Filtrar fotos","it":"Filtra foto","ru":"Фильтр фото","ar":"تصفية الصور","hi":"फ़ोटो फ़िल्टर","th":"กรองรูปภาพ","vi":"Lọc ảnh","id":"Saring foto","tr":"Fotoğrafları filtrele","nl":"Fotos filteren","pl":"Filtruj zdjęcia","sv":"Filtrera foton","fa":"فیلتر عکس‌ها","he":"סינון תמונות","bn":"ছবি ফিল্টার","tl":"Salain ang mga litrato","uk":"Фільтр фото"};
UI_STRINGS.showMore = {"ja":"もっと見る","en":"Show more","zh":"显示更多","zh-tw":"顯示更多","ko":"더 보기","es":"Ver más","fr":"Voir plus","de":"Mehr anzeigen","pt":"Ver mais","it":"Mostra altro","ru":"Показать ещё","ar":"عرض المزيد","hi":"और दिखाएं","th":"แสดงเพิ่ม","vi":"Xem thêm","id":"Tampilkan lagi","tr":"Daha fazla","nl":"Meer tonen","pl":"Pokaż więcej","sv":"Visa fler","fa":"نمایش بیشتر","he":"הצג עוד","bn":"আরও দেখুন","tl":"Magpakita pa","uk":"Показати більше"};

/* ③⑥⑦ で追加した UI 文言 (25言語) */
UI_STRINGS.actualSize = {"ja":"等倍表示","en":"Actual size","zh":"原始尺寸","zh-tw":"原始尺寸","ko":"실제 크기","es":"Tamaño real","fr":"Taille réelle","de":"Originalgröße","pt":"Tamanho real","it":"Dimensione reale","ru":"Реальный размер","ar":"الحجم الفعلي","hi":"वास्तविक आकार","th":"ขนาดจริง","vi":"Kích thước thật","id":"Ukuran asli","tr":"Gerçek boyut","nl":"Werkelijke grootte","pl":"Rzeczywisty rozmiar","sv":"Verklig storlek","fa":"اندازه واقعی","he":"גודל מקורי","bn":"প্রকৃত আকার","tl":"Tunay na sukat","uk":"Реальний розмір"};
UI_STRINGS.fullscreen = {"ja":"全画面","en":"Fullscreen","zh":"全屏","zh-tw":"全螢幕","ko":"전체 화면","es":"Pantalla completa","fr":"Plein écran","de":"Vollbild","pt":"Tela cheia","it":"Schermo intero","ru":"Полный экран","ar":"ملء الشاشة","hi":"पूर्ण स्क्रीन","th":"เต็มจอ","vi":"Toàn màn hình","id":"Layar penuh","tr":"Tam ekran","nl":"Volledig scherm","pl":"Pełny ekran","sv":"Helskärm","fa":"تمام‌صفحه","he":"מסך מלא","bn":"পূর্ণ স্ক্রিন","tl":"Buong screen","uk":"Повний екран"};
UI_STRINGS.hideControls = {"ja":"操作を隠す","en":"Hide controls","zh":"隐藏控件","zh-tw":"隱藏控制項","ko":"컨트롤 숨기기","es":"Ocultar controles","fr":"Masquer les commandes","de":"Bedienelemente ausblenden","pt":"Ocultar controles","it":"Nascondi comandi","ru":"Скрыть элементы","ar":"إخفاء عناصر التحكم","hi":"नियंत्रण छिपाएं","th":"ซ่อนตัวควบคุม","vi":"Ẩn điều khiển","id":"Sembunyikan kontrol","tr":"Kontrolleri gizle","nl":"Bediening verbergen","pl":"Ukryj elementy","sv":"Dölj kontroller","fa":"پنهان کردن کنترل‌ها","he":"הסתר פקדים","bn":"নিয়ন্ত্রণ লুকান","tl":"Itago ang kontrol","uk":"Сховати елементи"};
UI_STRINGS.showControls = {"ja":"操作を表示","en":"Show controls","zh":"显示控件","zh-tw":"顯示控制項","ko":"컨트롤 표시","es":"Mostrar controles","fr":"Afficher les commandes","de":"Bedienelemente anzeigen","pt":"Mostrar controles","it":"Mostra comandi","ru":"Показать элементы","ar":"إظهار عناصر التحكم","hi":"नियंत्रण दिखाएं","th":"แสดงตัวควบคุม","vi":"Hiện điều khiển","id":"Tampilkan kontrol","tr":"Kontrolleri göster","nl":"Bediening tonen","pl":"Pokaż elementy","sv":"Visa kontroller","fa":"نمایش کنترل‌ها","he":"הצג פקדים","bn":"নিয়ন্ত্রণ দেখান","tl":"Ipakita ang kontrol","uk":"Показати елементи"};
UI_STRINGS.compare = {"ja":"2枚を比べる","en":"Compare two","zh":"对比两张","zh-tw":"比較兩張","ko":"두 장 비교","es":"Comparar dos","fr":"Comparer deux","de":"Zwei vergleichen","pt":"Comparar duas","it":"Confronta due","ru":"Сравнить два","ar":"قارن صورتين","hi":"दो की तुलना","th":"เปรียบเทียบสองภาพ","vi":"So sánh hai ảnh","id":"Bandingkan dua","tr":"İkisini karşılaştır","nl":"Twee vergelijken","pl":"Porównaj dwa","sv":"Jämför två","fa":"مقایسه دو عکس","he":"השווה שתיים","bn":"দুটি তুলনা","tl":"Ihambing ang dalawa","uk":"Порівняти два"};
UI_STRINGS.sideBySide = {"ja":"横に並べる","en":"Side by side","zh":"并排","zh-tw":"並排","ko":"가로 배치","es":"Lado a lado","fr":"Côte à côte","de":"Nebeneinander","pt":"Lado a lado","it":"Affiancate","ru":"Рядом","ar":"جنبًا إلى جنب","hi":"अगल-बगल","th":"เรียงข้างกัน","vi":"Cạnh nhau","id":"Berdampingan","tr":"Yan yana","nl":"Naast elkaar","pl":"Obok siebie","sv":"Sida vid sida","fa":"کنار هم","he":"זה לצד זה","bn":"পাশাপাশি","tl":"Magkatabi","uk":"Поруч"};
UI_STRINGS.stackView = {"ja":"縦に並べる","en":"Stacked","zh":"上下排列","zh-tw":"上下排列","ko":"세로 배치","es":"Apiladas","fr":"Empilées","de":"Übereinander","pt":"Empilhadas","it":"Impilate","ru":"Друг под другом","ar":"فوق بعضهما","hi":"ऊपर-नीचे","th":"เรียงบนล่าง","vi":"Xếp chồng","id":"Bertumpuk","tr":"Üst üste","nl":"Onder elkaar","pl":"Jedno pod drugim","sv":"Staplade","fa":"روی هم","he":"זו מעל זו","bn":"উপর-নিচে","tl":"Nakasalansan","uk":"Одне під одним"};
UI_STRINGS.swap = {"ja":"入れ替える","en":"Swap","zh":"交换","zh-tw":"交換","ko":"교체","es":"Intercambiar","fr":"Échanger","de":"Tauschen","pt":"Trocar","it":"Scambia","ru":"Поменять","ar":"تبديل","hi":"अदला-बदली","th":"สลับ","vi":"Hoán đổi","id":"Tukar","tr":"Yer değiştir","nl":"Verwisselen","pl":"Zamień","sv":"Byt plats","fa":"جابه‌جایی","he":"החלף","bn":"অদলবদল","tl":"Palitan","uk":"Поміняти"};
UI_STRINGS.album = {"ja":"アルバム","en":"Album","zh":"相册","zh-tw":"相簿","ko":"앨범","es":"Álbum","fr":"Album","de":"Album","pt":"Álbum","it":"Album","ru":"Альбом","ar":"ألبوم","hi":"एल्बम","th":"อัลบั้ม","vi":"Album","id":"Album","tr":"Albüm","nl":"Album","pl":"Album","sv":"Album","fa":"آلبوم","he":"אלבום","bn":"অ্যালবাম","tl":"Album","uk":"Альбом"};
UI_STRINGS.shareAlbum = {"ja":"アルバムを共有","en":"Share album","zh":"分享相册","zh-tw":"分享相簿","ko":"앨범 공유","es":"Compartir álbum","fr":"Partager l album","de":"Album teilen","pt":"Compartilhar álbum","it":"Condividi album","ru":"Поделиться альбомом","ar":"مشاركة الألبوم","hi":"एल्बम साझा करें","th":"แชร์อัลบั้ม","vi":"Chia sẻ album","id":"Bagikan album","tr":"Albümü paylaş","nl":"Album delen","pl":"Udostępnij album","sv":"Dela album","fa":"اشتراک آلبوم","he":"שתף אלבום","bn":"অ্যালবাম শেয়ার","tl":"Ibahagi ang album","uk":"Поділитися альбомом"};
UI_STRINGS.albumLimit = {"ja":"この枚数まで","en":"Up to this many","zh":"最多这么多","zh-tw":"最多這麼多","ko":"최대 이만큼","es":"Hasta esta cantidad","fr":"Jusqu à ce nombre","de":"Bis zu dieser Anzahl","pt":"Até esta quantidade","it":"Fino a questo numero","ru":"Не больше","ar":"حتى هذا العدد","hi":"इतने तक","th":"สูงสุดเท่านี้","vi":"Tối đa","id":"Maksimal","tr":"Bu sayıya kadar","nl":"Tot dit aantal","pl":"Do tylu","sv":"Upp till så många","fa":"تا این تعداد","he":"עד כמות זו","bn":"এতগুলো পর্যন্ত","tl":"Hanggang dito","uk":"До цієї кількості"};
UI_STRINGS.moveUp = {"ja":"前へ移動","en":"Move earlier","zh":"前移","zh-tw":"前移","ko":"앞으로 이동","es":"Mover antes","fr":"Déplacer avant","de":"Nach vorne","pt":"Mover antes","it":"Sposta prima","ru":"Переместить вперёд","ar":"نقل للأمام","hi":"आगे ले जाएं","th":"เลื่อนขึ้น","vi":"Chuyển lên","id":"Pindah ke atas","tr":"Öne taşı","nl":"Naar voren","pl":"Przesuń w przód","sv":"Flytta framåt","fa":"انتقال به جلو","he":"הזז קדימה","bn":"আগে সরান","tl":"Ilipat pauna","uk":"Перемістити вперед"};
UI_STRINGS.moveDown = {"ja":"後へ移動","en":"Move later","zh":"后移","zh-tw":"後移","ko":"뒤로 이동","es":"Mover después","fr":"Déplacer après","de":"Nach hinten","pt":"Mover depois","it":"Sposta dopo","ru":"Переместить назад","ar":"نقل للخلف","hi":"पीछे ले जाएं","th":"เลื่อนลง","vi":"Chuyển xuống","id":"Pindah ke bawah","tr":"Arkaya taşı","nl":"Naar achteren","pl":"Przesuń w tył","sv":"Flytta bakåt","fa":"انتقال به عقب","he":"הזז אחורה","bn":"পরে সরান","tl":"Ilipat pahuli","uk":"Перемістити назад"};
UI_STRINGS.similarPhotos = {"ja":"似た写真","en":"Similar photos","zh":"相似照片","zh-tw":"相似照片","ko":"비슷한 사진","es":"Fotos similares","fr":"Photos similaires","de":"Ähnliche Fotos","pt":"Fotos semelhantes","it":"Foto simili","ru":"Похожие фото","ar":"صور مشابهة","hi":"समान फ़ोटो","th":"ภาพที่คล้ายกัน","vi":"Ảnh tương tự","id":"Foto serupa","tr":"Benzer fotoğraflar","nl":"Vergelijkbare fotos","pl":"Podobne zdjęcia","sv":"Liknande foton","fa":"عکس‌های مشابه","he":"תמונות דומות","bn":"অনুরূপ ছবি","tl":"Katulad na litrato","uk":"Схожі фото"};

/* ⑤ 色検索の色名。色だけで意味を伝えないための表示ラベル。 */
export const COLOR_LABELS = {
  red: { "ja": "赤", "en": "Red", "zh": "红", "zh-tw": "紅", "ko": "빨강", "es": "Rojo", "fr": "Rouge", "de": "Rot", "pt": "Vermelho", "it": "Rosso", "ru": "Красный", "ar": "أحمر", "hi": "लाल", "th": "แดง", "vi": "Đỏ", "id": "Merah", "tr": "Kırmızı", "nl": "Rood", "pl": "Czerwony", "sv": "Röd", "fa": "قرمز", "he": "אדום", "bn": "লাল", "tl": "Pula", "uk": "Червоний" },
  orange: { "ja": "橙", "en": "Orange", "zh": "橙", "zh-tw": "橙", "ko": "주황", "es": "Naranja", "fr": "Orange", "de": "Orange", "pt": "Laranja", "it": "Arancione", "ru": "Оранжевый", "ar": "برتقالي", "hi": "नारंगी", "th": "ส้ม", "vi": "Cam", "id": "Oranye", "tr": "Turuncu", "nl": "Oranje", "pl": "Pomarańczowy", "sv": "Orange", "fa": "نارنجی", "he": "כתום", "bn": "কমলা", "tl": "Kahel", "uk": "Помаранчевий" },
  yellow: { "ja": "黄", "en": "Yellow", "zh": "黄", "zh-tw": "黃", "ko": "노랑", "es": "Amarillo", "fr": "Jaune", "de": "Gelb", "pt": "Amarelo", "it": "Giallo", "ru": "Жёлтый", "ar": "أصفر", "hi": "पीला", "th": "เหลือง", "vi": "Vàng", "id": "Kuning", "tr": "Sarı", "nl": "Geel", "pl": "Żółty", "sv": "Gul", "fa": "زرد", "he": "צהוב", "bn": "হলুদ", "tl": "Dilaw", "uk": "Жовтий" },
  green: { "ja": "緑", "en": "Green", "zh": "绿", "zh-tw": "綠", "ko": "초록", "es": "Verde", "fr": "Vert", "de": "Grün", "pt": "Verde", "it": "Verde", "ru": "Зелёный", "ar": "أخضر", "hi": "हरा", "th": "เขียว", "vi": "Xanh lá", "id": "Hijau", "tr": "Yeşil", "nl": "Groen", "pl": "Zielony", "sv": "Grön", "fa": "سبز", "he": "ירוק", "bn": "সবুজ", "tl": "Berde", "uk": "Зелений" },
  blue: { "ja": "青", "en": "Blue", "zh": "蓝", "zh-tw": "藍", "ko": "파랑", "es": "Azul", "fr": "Bleu", "de": "Blau", "pt": "Azul", "it": "Blu", "ru": "Синий", "ar": "أزرق", "hi": "नीला", "th": "น้ำเงิน", "vi": "Xanh dương", "id": "Biru", "tr": "Mavi", "nl": "Blauw", "pl": "Niebieski", "sv": "Blå", "fa": "آبی", "he": "כחול", "bn": "নীল", "tl": "Asul", "uk": "Синій" },
  purple: { "ja": "紫", "en": "Purple", "zh": "紫", "zh-tw": "紫", "ko": "보라", "es": "Morado", "fr": "Violet", "de": "Violett", "pt": "Roxo", "it": "Viola", "ru": "Фиолетовый", "ar": "بنفسجي", "hi": "बैंगनी", "th": "ม่วง", "vi": "Tím", "id": "Ungu", "tr": "Mor", "nl": "Paars", "pl": "Fioletowy", "sv": "Lila", "fa": "بنفش", "he": "סגול", "bn": "বেগুনি", "tl": "Lila", "uk": "Фіолетовий" },
  pink: { "ja": "ピンク", "en": "Pink", "zh": "粉", "zh-tw": "粉", "ko": "분홍", "es": "Rosa", "fr": "Rose", "de": "Rosa", "pt": "Rosa", "it": "Rosa", "ru": "Розовый", "ar": "وردي", "hi": "गुलाबी", "th": "ชมพู", "vi": "Hồng", "id": "Merah muda", "tr": "Pembe", "nl": "Roze", "pl": "Różowy", "sv": "Rosa", "fa": "صورتی", "he": "ורוד", "bn": "গোলাপি", "tl": "Rosas", "uk": "Рожевий" },
  brown: { "ja": "茶", "en": "Brown", "zh": "棕", "zh-tw": "棕", "ko": "갈색", "es": "Marrón", "fr": "Marron", "de": "Braun", "pt": "Marrom", "it": "Marrone", "ru": "Коричневый", "ar": "بني", "hi": "भूरा", "th": "น้ำตาล", "vi": "Nâu", "id": "Cokelat", "tr": "Kahverengi", "nl": "Bruin", "pl": "Brązowy", "sv": "Brun", "fa": "قهوه‌ای", "he": "חום", "bn": "বাদামী", "tl": "Kayumanggi", "uk": "Коричневий" },
  white: { "ja": "白", "en": "White", "zh": "白", "zh-tw": "白", "ko": "하양", "es": "Blanco", "fr": "Blanc", "de": "Weiß", "pt": "Branco", "it": "Bianco", "ru": "Белый", "ar": "أبيض", "hi": "सफ़ेद", "th": "ขาว", "vi": "Trắng", "id": "Putih", "tr": "Beyaz", "nl": "Wit", "pl": "Biały", "sv": "Vit", "fa": "سفید", "he": "לבן", "bn": "সাদা", "tl": "Puti", "uk": "Білий" },
  gray: { "ja": "灰", "en": "Grey", "zh": "灰", "zh-tw": "灰", "ko": "회색", "es": "Gris", "fr": "Gris", "de": "Grau", "pt": "Cinza", "it": "Grigio", "ru": "Серый", "ar": "رمادي", "hi": "धूसर", "th": "เทา", "vi": "Xám", "id": "Abu-abu", "tr": "Gri", "nl": "Grijs", "pl": "Szary", "sv": "Grå", "fa": "خاکستری", "he": "אפור", "bn": "ধূসর", "tl": "Kulay-abo", "uk": "Сірий" },
  black: { "ja": "黒", "en": "Black", "zh": "黑", "zh-tw": "黑", "ko": "검정", "es": "Negro", "fr": "Noir", "de": "Schwarz", "pt": "Preto", "it": "Nero", "ru": "Чёрный", "ar": "أسود", "hi": "काला", "th": "ดำ", "vi": "Đen", "id": "Hitam", "tr": "Siyah", "nl": "Zwart", "pl": "Czarny", "sv": "Svart", "fa": "سیاه", "he": "שחור", "bn": "কালো", "tl": "Itim", "uk": "Чорний" },
};
export function colorLabel(key, lang) {
  const m = COLOR_LABELS[key];
  return m ? (m[lang] || m.en || key) : key;
}
